### ISSUE TITLE
Support for adding HTTP authentication inside an URL

### ISSUE THREAD

**Issue by ad-m** [thp/urlwatch#10]
```
$ urlwatch -e
***************************************************************************
ERROR: http://Student:**REMOVED STH LIKE "aBc"**@annaw.ii.uph.edu.pl/dydaktyka_pliki/PP/
***************************************************************************
InvalidURL("nonnumeric port: '**REMOVED STH LIKE "aBc"**@annaw.ii.uph.edu.pl'",)
nonnumeric port: ''**REMOVED STH LIKE "aBc"**@annaw.ii.uph.edu.pl'
***************************************************************************
```
What's there wrong? 

Some workaround is use curl like that:
```| curl 'http://Student:**REMOVED STH LIKE "aBc"**@annaw.ii.uph.edu.pl/dydaktyka_pliki/PP/' 2>/dev/null ```

**Comment by thp** [comment]
Is there a ":" or an "@" in your password? Those might have to be escaped with %

**Comment by ad-m** [comment]
No. There is no password "@" in password.

**Comment by thp** [comment]
Oh yeah, looks like we don't support this at the moment, and probably need to extract the authentication information from the URL before sending it to the HTTP library and then providing the authentication information separately in the request (as header). Keeping this bug open until it's implemented.
