### ISSUE TITLE
Use sensible-editor

### ISSUE THREAD

**Issue by ad-m** [thp/urlwatch#101]
Hello,

It is unusual to provide environment variables (standard, but not common) for select editor. There exists standard ```sensible-editor``` on Linux for that. There is ```editor``` executables very common too.

Greetings,

**Comment by thp** [comment]
As far as I know, `sensible-editor` is a Debianism? I don't have a problem with adding that as a fallback if `$EDITOR` and/or `$VISUAL` are not set, feel free to provide a patch.

**Comment by jwilk** [comment]
`sensible-editor` is a Debian-specific hack. Please don't use it.
`editor` is also a Debianism, but I think some unrelated distros have it too. It would be fine to use it as a fallback, I guess.
Most upstream software I know use `vi` when `$EDITOR` is not set (which Debian people then patch to make it `s/vi/editor/`).

Source: [Debian Policy §11.14](https://www.debian.org/doc/debian-policy/ch-customized-programs.html#s11.4)

**Comment by thp** [comment]
Let's leave that as-is for now.
