### ISSUE TITLE
Git workflow unclear

### ISSUE THREAD

**Issue by lechuckcaptain** [thp/urlwatch#107]
Just a suggestion that could be useful also for other contributors: it would be nice to have a declaration of a specific Git workflow to use in order to contribute to the project. At least a development branch and a master (stable) branch with the latest released version should be nice. It should allow you also to easily accept new features before prepare a new official release. What do you think?

**Comment by thp** [comment]
I think the project at the moment has too little traffic to justify having multiple development branches. We'll merge everything that's good into master, and every now and then release from the master branch by tagging. If there are important fixes, we can branch off the latest release tag and cherry-pick fixes and do point releases from it, but so far that wasn't needed.

So, just create pull requests for master and we'll review and merge those.

**Comment by lechuckcaptain** [comment]
OK seems fair to me. Thank you for the answer.
