### ISSUE TITLE
A traceback

### ISSUE THREAD

**Issue by strauhmanis** [thp/urlwatch#113]
Hi Thomas! Thank you for the recent #110 (HTML class filter), first of all 👍 

When running the current Git master, there's a following output on my system (macOS 10.12.1):

urlwatch 2.5, Copyright 2008-2016 Thomas Perl
Website: http://thp.io/2008/urlwatch/
watched 30 URLs in 2 seconds
Traceback (most recent call last):
  File "/Users/ervsts/Git/urlwatch/urlwatch", line 101, in <module>
    urlwatch_command.run()
  File "/Users/ervsts/Git/urlwatch/lib/urlwatch/command.py", line 167, in run
    self.urlwatcher.close()
  File "/Users/ervsts/Git/urlwatch/lib/urlwatch/main.py", line 96, in close
    self.report.finish()
  File "/Users/ervsts/Git/urlwatch/lib/urlwatch/handler.py", line 125, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/Users/ervsts/Git/urlwatch/lib/urlwatch/reporters.py", line 90, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/Users/ervsts/Git/urlwatch/lib/urlwatch/reporters.py", line 445, in submit
    result = requests.post(
NameError: name 'requests' is not defined

I don't quite know what's wrong here.

Thank you!

**Comment by ad-m** [comment]
@strauhmanis , do you use mailgun reporter? Do you can provide your config file?

**Comment by ad-m** [comment]
@lechuckcaptain , did you miss ```import requests```?

**Comment by strauhmanis** [comment]
Hi Adam @ad-m ! I'm not sure what you mean about missing import requests, sorry about me not being very technical minded, but I do send email notifications about changes via mailgun service.

Below are contents of my urlwatch.yaml:

display:
  error: true
  new: true
  unchanged: false
report:
  email:
    enabled: false
    from: 'myemail@gmaill.com'
    html: false
    method: smtp
    sendmail:
      path: sendmail
    smtp:
      host: localhost
      keyring: true
      port: 25
      starttls: true
    subject: '{count} changes: {jobs}'
    to: 'myemail@gmaill.com'
  html:
    diff: unified
  mailgun:
    api_key: 'key-xxxx'
    domain: 'sandboxbxxxx.mailgun.org'
    enabled: true
    from_mail: 'myemail@gmaill.com'
    from_name: 'urlwatch'
    subject: '{count} changes: {jobs}'
    to: 'myemail@gmaill.com'
  pushbullet:
    api_key: ''
    enabled: false
  pushover:
    app: 'urlwatch'
    enabled: false
    user: 'xxxx'
  stdout:
    color: true
    enabled: true
  text:
    details: true
    footer: true
    line_length: 75

**Comment by ad-m** [comment]
Mailgun reporter was temporary broken. Fix was prepared (see #114). Ready to merge & release a fixed version.

**Comment by strauhmanis** [comment]
Ah, I see. Thanks for the heads up and a quick fix!

**Comment by ad-m** [comment]
@thp, @strauhmanis , do you can close this, please?

**Comment by ad-m** [comment]
@thp, thank you.
