### ISSUE TITLE
How to avoid numbers in differences

### ISSUE THREAD

**Issue by xgt36** [thp/urlwatch#116]
Hi,

I am monitoring a page containing links to different articles (one per line) and they all have a score. Right now, I get a notification each time scores change, but I would like to ignore that, and just get notifications when new articles appear. Is it possible to do that with urlwatch?

-a

**Comment by ad-m** [comment]
Hello,

Yes, of course. Use ```grepi``` which exclude some lines from output eg.:
```
kind: url
url: http://bip.rcl.gov.pl/rcl/rejestr/6645,dok.html
filter: html2text:lynx,grepi:data aktualizacji,grepi:godzinie,grepi:os.b
```

Provide changes report to prepare settings for your page.

Greetings,

**Comment by xgt36** [comment]
Thanks for the quick answer. I am not 100% sure, but if I understand well, I dont think that will do what I need. Here is an example to illustrate.

On day 1 , the website shows an entry as follow:
16/11/02  story A (4.1)

i.e. date when story was posted, story name, and a score

On day 2, the entry changes a follow
16/11/02  story A (3.9)

and I will get an update from url watch since the score has changed (from 4.1 to 3.9). But really I only want an update if another story, story B, was posted. If only the score changes, I dont want an update.

So can it be achieved directly from url watch?

**Comment by ad-m** [comment]
IMO it requires trival custom filter like https://github.com/thp/urlwatch/blob/master/lib/urlwatch/filters.py#L194 . Use ```urlwatch --edit-hooks``. Do you can provide URL of web page to prepare custom filter?
