### ISSUE TITLE
Include the URL in the subject of the alert e-mail

### ISSUE THREAD

**Issue by thp** [thp/urlwatch#12]
From user feedback:

was wondering if there is a way to include the name of the URL changed in the subject of the alert email?

**Comment by egroeper** [comment]
As URLs tend to be long perhaps this could be combined with shortnames for URLs/websites?
Then these shortnames could be put in the subject.
Of course this would mean to change the syntax of urls.txt.

**Comment by thp** [comment]
Yeah, I would have no problem with changing urls.txt to JSON or YAML or something (and use the opportunity to add new settings and make it extendable) - this can work nicely with changing the filename and checking for the existence of both filenames (e.g. urls.txt and urls.yaml) and making sure that existing urls.txt files continue to work as before (just not with the advanced features), so users can upgrade to the new format at their leisure.
