### ISSUE TITLE
Legacy hooks filter is always executed

### ISSUE THREAD

**Issue by Lukas0907** [thp/urlwatch#121]
Hi,

the legacy hooks filter is always executed when the file ~/.urlwatch/lib/hooks.py exists. I'm using urlwatch1 and urlwatch2 in parallel (I can't migrate from 1 to 2 for now) and the file is always executed even though the filter is not specified in urlwatch2's urls.yml.

It'd be nice if it was optional.

Thanks :)

Lukas

**Comment by thp** [comment]
What's missing in 2 that keeps you from migrating from version 1 to version 2?

**Comment by Lukas0907** [comment]
urlwatch1 is running in production (on Python 2.7), monitoring > 100 URLs with a lot of custom hooks (that I don't want to touch right now). I plan to migrate it in the beginning of next year, but it's more of an organizational issue and not related to urlwatch2 per se.

If I specify "--urls", "--cache" and "--config" the legacy files are left alone (as one would expect) but even though I explicitly specify a "--hooks" file, the old hooks are still imported. I appreciate that you want to make migrations from 1 to 2 as painless (and automated) as possible but sometimes you don't want to migrate but rather run both in parallel. The only way that I found to make this possible is to patch the importing of the old legacy file away.

**Comment by thp** [comment]
Closing this, as for now you should have probably migrated to urlwatch 2, and if not, configure urlwatch 1 to use a different hooks.py file.
