### ISSUE TITLE
Enabling pushover/HowTo?

### ISSUE THREAD

**Issue by gabrielhribeiro** [thp/urlwatch#122]
how to send e-mail? i have tried script from another issue, but i did cant.

**Comment by ad-m** [comment]
Do you want enable pushover (as in title) or email (as in content)?

I recommend two ways for email:
- use crontab build-in feature to send console output,
- execute ``urlwatch --edit-config`` and set ``report.email`` settings.

**Comment by thp** [comment]
@gabrielhribeiro does @ad-m's solution fix your problem? In that case, please let us know so we can close the issue.

**Comment by gabrielhribeiro** [comment]
@thp i'm just traying to do this config, but i have some douts.  You can close this issue, no problem!

**Comment by gabrielhribeiro** [comment]
@thp  @ad-m, i just insert my code from API and USER and i set like this: 

pushover:
  app: 'key'
  enable: true
  user:'key'
*key from website pushover

when i do:
#urlwatch 

i got: ConnectionRefusedError: [Errno 111] Connection Refused
