### ISSUE TITLE
needs workaround for sqlite3 bug in python 3.6

### ISSUE THREAD

**Issue by katylava** [thp/urlwatch#123]
```
> urlwatch                                                                                                                                                                                
Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 101, in <module>
    urlwatch_command.run()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/command.py", line 167, in run
    self.urlwatcher.close()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/main.py", line 97, in close
    self.cache_storage.close()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/storage.py", line 465, in close
    self.db.close()
  File "/usr/local/lib/python3.6/site-packages/minidb.py", line 170, in close
    self._execute('VACUUM')
  File "/usr/local/lib/python3.6/site-packages/minidb.py", line 153, in _execute
    return self.db.execute(sql)
sqlite3.OperationalError: cannot VACUUM from within a transaction
```

https://bugs.python.org/issue29003:
>  It will work if you set isolation_level=None.

**Comment by sthen** [comment]
This diff works around it (it's for minidb, not urlwatch) -

{{{
--- minidb.py.orig	Fri Jan  6 10:29:50 2017
+++ minidb.py	Fri Jan  6 10:31:03 2017
@@ -131,7 +131,7 @@ class Store(object):
     MINIDB_ATTR = '_minidb'
 
     def __init__(self, filename=':memory:', debug=False, smartupdate=False):
-        self.db = sqlite3.connect(filename, check_same_thread=False)
+        self.db = sqlite3.connect(filename, check_same_thread=False, isolation_level=None)
         self.debug = debug
         self.smartupdate = smartupdate
         self.registered = {}
}}}

**Comment by kyrias** [comment]
That belongs in the minidb repo, not this one though.

**Comment by anthraxx** [comment]
I have opened an issue at minidb, as technically this is not really a bug within urlwatch itself: https://github.com/thp/minidb/pull/2

**Comment by thp** [comment]
Merged https://github.com/thp/minidb/pull/2 and closing this one.

**Comment by thp** [comment]
minidb 2.0.2 released with the fix, the update can be installed using pip.

**Comment by anthraxx** [comment]
@thp can you also please tag a release on github and update your website? :smile_cat:

**Comment by thp** [comment]
@anthraxx Done, you might need to hit refresh in your browser (forgot to push the tag, now it's pushed):

http://thp.io/2010/minidb/
https://github.com/thp/minidb/releases/tag/2.0.2

**Comment by anthraxx** [comment]
@thp thanks a lot :heart:
