### ISSUE TITLE
JavaScript Page not working

### ISSUE THREAD

**Issue by zaico23** [thp/urlwatch#124]
I'm trying to watch a URL which uses javascript. The html shows "请开启JavaScript并刷新该页" which means "activate javascript". So I suposse javascript is not compatible with urlwatch?

This is the address: 
wzdig.pbc.gov.cn:8080/dig/ui/search.action?ty=&w=false&f=&dr=true&p=1&sr=score+desc%2Cdatetime+desc&rp=&advtime=&advrange=&fq=&ext=&q=+人民币

Any clue?

**Comment by thp** [comment]
Yes, urlwatch doesn't evaluate JavaScript, it's just used for static content. However, if you use something like Firefox' developer toolbar and check out which requests are done, chances are that you can find out the URL of the REST API endpoint that returns the result to the JavaScript code (it's usually implemented like this -- a backend server returns the data as XML or JSON to the JavaScript code for display).

**Comment by afaucon** [comment]
Hello thp.
What about javascript directly embedded in html? This is static javascript content.
Does urlwatch recognize modification in <script> element ?

**Comment by ad-m** [comment]
@afaucon, it recognize modification in JavaScript source code.
