### ISSUE TITLE
Multiple URL lists

### ISSUE THREAD

**Issue by strauhmanis** [thp/urlwatch#148]
Hi Thomas!

I found myself in need of having separate URL lists so as to check different links at different time intervals.

The way that I can think of achieving this goal now, is to create a shell script or several of them and with their help to rename `urls.yaml` back and forth between `my-urls-list1.yaml`, `my-urls-list2.yaml`, etc.

Those who can, have also an option of using urlwatch as a library to create an elegant solution, as far as I understand this, but it would be nice if at some future point it were to be possible to supply urlwatch specific lists without having to come up with a gettting-around-it-script or an app.

Thanks!

**Comment by thp** [comment]
Well the solution would probably be to have a new `interval` key in the YAML file and let urlwatch handle the different intervals with a single list?

With that said, there's also the `--urls` command line option that should do the trick?

    urlwatch --urls=my-urls-list1.yaml

**Comment by thp** [comment]
To clarify, the `interval` key isn't yet implemented, but might be a good idea, but the `--urls` option is already implemented and should work already.

**Comment by strauhmanis** [comment]
Awesome! Apparently I browsed urlwatch code not that thoroughly and missed that already-in-place feature.

For anyone else who would be reading this, remember to supply full path to the URLs list:

`urlwatch --urls=/Users/me/.urlwatch/my-urls-list1.yaml`

Many thanks Thomas!

**Comment by strauhmanis** [comment]
I've been banging my head for a past hour trying to find an answer on why is a path to a URL list in a bash script is being "adjusted" and becomes invalid, while the same command in a terminal works fine:

This is the terminal output. First I run a script (see the script below), then I simply run a command:
```________________________________________________________________________________
| ~/Dropbox/Scripts/urlwatch @ TitanPonies (ervsts) 
| => bash urlwatch-go-Apple.sh

 in order to use urlwatch.ers/ervsts/Dropbox/Scripts/urlwatch/urls-apps-Apple.yaml
    Use "urlwatch --edit" to open the file with your editor.
    
________________________________________________________________________________
| ~/Dropbox/Scripts/urlwatch @ TitanPonies (ervsts) 
| => urlwatch --urls=/Users/ervsts/Dropbox/Scripts/urlwatch/urls-apps-Apple.yaml
________________________________________________________________________________
| ~/Dropbox/Scripts/urlwatch @ TitanPonies (ervsts) 
| => 
```

The script (if I may call it that) itself:
```
#!/bin/bash
urlwatch --urls=/Users/ervsts/Dropbox/Scripts/urlwatch/urls-apps-Apple.yaml
```

Does anyone have any hints, please?

**Comment by shaun-ba** [comment]
I was going to raise a feature request for this. I also would like to have different intervals for certain URLs, so would welcome this one!

**Comment by cjohnsonuk** [comment]
Regarding different intervals I've just created different config files called daily.yaml, weekly.yaml, monthly.yaml etc and then call them in the command via a cron script at different intervals.  Works great for me
