### ISSUE TITLE
Any instruction on how to configure this?

### ISSUE THREAD

**Issue by dariushazimi** [thp/urlwatch#149]
I am trying to figure out how to configure this but no luck so far. The only instruction is a quick start which does'nt provide any info on how to get started.  

1. How to create the url files?
2. Where to store it?

Would appreciate some instruction. Thanks.

**Comment by vmassuchetto** [comment]
Hi @dariushazimi. Take a look at the [example file](https://github.com/thp/urlwatch/blob/master/share/urlwatch/examples/urls.yaml.example). You should put it on `~/.urlwatch/urls.yaml`.

The command `urlwatch --edit-config` should create those files for you.
