### ISSUE TITLE
Support for cookie auth

### ISSUE THREAD

**Issue by ealprr** [thp/urlwatch#15]
Some webpage need session cookie and currently, urlwatch does not seems to handle those case.
`urllib2` need `cookielib` to handle cookies but `requests` manage this automatically.

**Comment by sbraz** [comment]
Hi, I would love to see this as well.

**Comment by thp** [comment]
You could prepare a patch that replaces urllib usage with requests?

**Comment by sbraz** [comment]
@thp I'll look into it.

**Comment by thp** [comment]
Now that requests is in, this might be easier to implement. @ealprr can you explain for which pages this happens and what it should do exactly?

**Comment by sbraz** [comment]
@thp It's probably trivial to add a cookies dict to the YAML. Do you want me to make a PR for this?

**Comment by thp** [comment]
Yes, if you're interested in working on this, I'd be all for it :)
