### ISSUE TITLE
Advanced usage (filters)

### ISSUE THREAD

**Issue by shaun-ba** [thp/urlwatch#151]
So, my understanding is that filters, specifically in my case "element-by-id", should be used when you only want to monitor a single thing on the page, to save lots of false positives etc.

Therefore i tried this on a span element, and have:

> kind: url
> name: Item
> url: "domain.com"
> filters: element-by-id:ctl00_Content_lblAvailability

Is this the correct way to use it? It seems to still be using the whole HTML to compare against.

Thanks

**Comment by thp** [comment]
It's `filter` (singular), not `filters`.
