### ISSUE TITLE
Monitor same URL, different elements.

### ISSUE THREAD

**Issue by shaun-ba** [thp/urlwatch#153]
So after thinking i was doing something wrong for a long while, i realised that my listings were i believe overwriting each other!

So is URL the unique field in cache? maybe this should be changed to the "name:" value, this way the user can select multiple elements to monitor on a page, or filter methods.

**Comment by thp** [comment]
Workaround for now: Append "#something" to the URL (where something can be any random string).

**Comment by AdamSLevy** [comment]
I also ran into this problem and had to search to find this. I believe a note in the man page at least would be very helpful.

An actual fix would be to assign UUIDs keyed off a hash of the url and filter instead of just the url.

**Comment by thp** [comment]
Merging this into #232.
