### ISSUE TITLE
Can't use SMTP when 'from' is different from 'username'?

### ISSUE THREAD

**Issue by jsit** [thp/urlwatch#156]
I'm trying to send an email from Amazon SES, where the username required to authenticate is different from the email address from which I'm sending. I can't figure out how to configure something like that in urlwatch. Is it possible?

**Comment by jsit** [comment]
Something like this might work:

https://github.com/jsit/urlwatch/commit/982868d2d45dcbcdbd2e218902ffeff1bb4fb58c

**Comment by thp** [comment]
@jsit yes this looks good, can you submit that change as a pull request?

**Comment by jsit** [comment]
Fixed by #157

**Comment by jsit** [comment]
Hm how do I mark this as resolved?

**Comment by thp** [comment]
I think on Github, closed = resolved :)
