### ISSUE TITLE
-s flag is invalid

### ISSUE THREAD

**Issue by vaindil** [thp/urlwatch#16]
I'm trying to configure Gmail SMTP with urlwatch but the supplied example, `urlwatch -s smtp.example.com:587 -f alice@example.com --pass`, does not work on Ubuntu Server 15.04. I have all of the requisite dependencies installed, but urlwatch reports `error: no such option: -s`.

**Comment by julianofischer** [comment]
It happened to me too (ubuntu 14.04).

**Comment by thp** [comment]
Install the newest version.
