### ISSUE TITLE
Riot.im / Matrix Support?

### ISSUE THREAD

**Issue by tilllt** [thp/urlwatch#160]
Are there any plans to support Matrix / Riot.im for notification?
http://matrix.org/docs/guides/client-server.html

**Comment by thp** [comment]
If somebody writes support for it in form of a pull request, sure.

**Comment by tilllt** [comment]
Unfortunately my programming skills are not sufficient to do this (yet). Just in case somebody else is also interested in this feature: https://github.com/shawnanastasio/python-matrix-bot-api

**Comment by julianuu** [comment]
Hey, looks like @reivilibre wrote it: https://github.com/reivilibre/fork-urlwatch-matrix! Would be great to see it included also here.

And thanks for the good work all of you!

**Comment by thp** [comment]
Feel free to ask @reivilibre to create a pull request, then we can review and potentially merge it.

**Comment by julianuu** [comment]
I guess @reivilibre got a notification that he/she has been mentioned here? I don't know if there is a way to message someone. Also, I just noticed that I could also just create a pull request to merge their fork with this repository. But I am somewhat new to github, and I don't know if doing this would be appropriate.

**Comment by reivilibre** [comment]
Hi there!
I'm surprised you noticed my fork.
If you're happy with its current state, I'm happy to open a PR for it. If there are any issues, though, I am currently studying for university examinations and I don't have the time to do maintenance right now.
@julianuu If you want to take on the pull request yourself, I'm happy for you to do that.
I think I should receive messages here if they have @reivilibre in them, so feel free to get in touch that way.
Many thanks.

**Comment by julianuu** [comment]
Great! I am not in a hurry to get it merged, so I wouldn't mind waiting until you have time again @reivilibre. Otherwise I could also help merging, but I'm not sure how much sense this makes since I am not familiar with the code of urlwatch or your fork

**Comment by julianuu** [comment]
If you open the pull request that would be great, I am happy to help if you are busy!

**Comment by schildbach** [comment]
I went ahead and opened a PR for Matrix support: https://github.com/thp/urlwatch/pull/445

**Comment by thp** [comment]
#445 is now merged and available in 2.18.
