### ISSUE TITLE
Pushover User?

### ISSUE THREAD

**Issue by dinosaw** [thp/urlwatch#161]
I was wanting to enable Pushover use, but I'm a little confused by the options within the --edit-config. Basically it says "app" which I know the app name, enabled which I set to true, but then it says "user". What is this "user" option referring to? After creating an application in Pushover, I'm only presented with an API token for that application that I created. Is it wanting my login username (i.e. username@mail.com)?

**Comment by 17100073** [comment]
I think you need to put the key available on your account in the "user" part. It is a long alphanumerical one displayed on the Pushover account.
For "app", once you activate the device you have Pushover app installed in, there is a key available for the specific device. Try adding that.
