### ISSUE TITLE
is there a synonym to -u option of diff (controls number of common lines)?

### ISSUE THREAD

**Issue by alexandergalitski** [thp/urlwatch#167]
i need to cut down number of similar lines to see only added/removed lines. in command-line diff i'd use diff -u0. how can it be done with urlwatch config without wrapping it's output in something like grep -v and so on? maybe it's possible to do with hooks?

**Comment by thp** [comment]
This is where we take the diff:
https://github.com/thp/urlwatch/blob/8eec4685c7126c31444f10befe5bc6cfdfd33369/lib/urlwatch/reporters.py#L100

Apparently it has an "n" parameter that you can use:
https://docs.python.org/3.6/library/difflib.html#difflib.unified_diff

Let me know if that helps.

**Comment by alexandergalitski** [comment]
thanks for your answer.

i'm not really a coder and moreover - not a python coder at all. so the only thing that i understood is that difflib.unified_diff is called without "n" parameter so it cannot be added to config to be passed to difflib.unified_diff. probably it can be patched to pass n from config ro difflib.unified_diff but it's far over my skills. maybe i'm wrong and the things can be done easier?

for now i just fixed my bash script that calls urlwatch so the problem is solved.

**Comment by thp** [comment]
Note that with the current master branch, you can now actually pass in a diff tool:

```
name: "Some page"
url: http://example.com
diff_tool: "diff -u0"
```

This will pipe the old and new content through the diff tool (with temporary files, as if called like `diff -u0 oldfile.txt newfile.txt` in the example above), and use the diff tool output as "diff result".
