### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by tuapuikia** [thp/urlwatch#17]
when urlwatch use to monitor https site that support sni, it will fail with following error message.

got URLError while loading url: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

**Comment by tuapuikia** [comment]
Look like it is caused by old python version. Python 2.7.9 have included SNI support.

**Comment by thp** [comment]
Closing as fixed in Python 2.7.9.
