### ISSUE TITLE
Accessing past versions of Sites

### ISSUE THREAD

**Issue by MrLafarge** [thp/urlwatch#170]
Dear Thomas,

is there any easy way to access previous versions of the pages other than directly querying the database? 

What I was doing in the previous version of urlwatch: 
1. Using Mercurial to version the cache files ("hg commit *") 
2. Open the repository in the built-in web server of Mercurial ("hg serve")
3. Accessing it in the browser

With the new version this is clearly not possible anymore, is something like that planned, e.g. using a web server Python modul? What else could I do to have a similar functionality?

Thanks!

**Comment by thp** [comment]
You should be able to query it from the SQLite database.
