### ISSUE TITLE
Relative path and Absolute path comparison

### ISSUE THREAD

**Issue by xiaoheihei3211** [thp/urlwatch#172]
Hi,

I haven't got to test out the program yet. However, I want to ask if the webpage were to change dynamically in terms of the URLs, (e.g., from /example/index.html to index.html) or (index.html to /example/index.html), does urlwatch detect this type of changes and generate false positive?

Any response is appreciated.

Thank you

**Comment by thp** [comment]
If there's a HTTP redirect, this can be detected. If the file is moved on the web server and no redirect is placed, there's no way for urlwatch to detect this in the general case.

**Comment by xiaoheihei3211** [comment]
What kind of redirect does it follows? (meta refresh in the header?)

**Comment by thp** [comment]
HTML meta tag refresh headers are not followed, just the HTTP header kind.
