### ISSUE TITLE
Error running urlwatch 2 on Debian 9

### ISSUE THREAD

**Issue by neilzone** [thp/urlwatch#173]
I have upgraded my Debian installation from Debian 7 to Debian 9, and my installation of urlwatch2 now no longer works.

When I run `urlwatch`, I get:

```
Traceback (most recent call last):
  File "/root/.local/bin/urlwatch", line 79, in <module>
    from urlwatch.storage import UrlsYaml, UrlsTxt, ConfigStorage, CacheDirStorage, CacheMiniDBStorage
ImportError: cannot import name 'ConfigStorage'
```

I have tried uninstalling and reinstalling, with no success.

Is there a way I can fix this, please?

**Comment by thp** [comment]
Looks like you might be mixing different versions of urlwatch (e.g. one installed system-wide and one for the root user only). Make sure you only have one version installed.

**Comment by neilzone** [comment]
Thank you, Thomas. I'll see what I can do.

Thanks for such a quick response; I appreciate it.

**Comment by thp** [comment]
Did you fix your problem? Can this issue be closed?

**Comment by neilzone** [comment]
I:
 - uninstalled all versions of urlwatch I had installed; and
 - installed urlwatch using `python3 -m pip install urlwatch --user`

It now works as expected.

Thanks for your help, Thomas.
