### ISSUE TITLE
--urls does not parse the old txt format

### ISSUE THREAD

**Issue by CyberPK** [thp/urlwatch#174]
I'm trying to pass an url list but cannot load it automatically.
A txt list is parsed only at the first run if it's located in the config directory with the name urs.txt
Otherwise urlwatch exit with an 'ValueError: Kind is not specified, and no job matches' exception.

**Comment by thp** [comment]
Just prefix every URL with `url:` and place a `---` between each line, this should make it work as YAML-based config file.
