### ISSUE TITLE
Cannot selectively disable proxy for a given url

### ISSUE THREAD

**Issue by copernico** [thp/urlwatch#176]
I am running a configuration where I need to call some urls through my (corporate) proxy and some other urls directly (internal servers) without going through the proxy.
Can urlwatch do that? I could not find a configuration like that per-url... Am I missing something?

**Comment by thp** [comment]
You can set `http_proxy` and `https_proxy` for each URL.

This has been available since urlwatch 2.6 in commit https://github.com/thp/urlwatch/commit/15b1101737fd9db831e53a37a0a9abff7f539280.

**Comment by thp** [comment]
Example config file:

```yaml
url: http://www.example.com
http_proxy: http://username:password@localhost:8080/
```

**Comment by copernico** [comment]
Your solution does not work for me. I want to monitor 100 urls, of which 99 need to go through my corporate proxy, and one is on our internal network and must not be fetched through the proxy.
You reply seems to imply that I can selectively disable the proxy for a url (that was the title of my ticket) by doing the following:

```
url: http://www.example.com
http_proxy:
```

..which did not work for me. Or am I missing something?
Thanks for your support.

**Comment by thp** [comment]
In this case, I suggest you have two configs, one that goes through the proxy and one that doesn't and you run urlwatch twice, with `--urls` and `--config` as parameters, e.g.:

    urlwatch --urls /path/to/urllist-no-proxy.yaml --config /path/to/config-no-proxy.yaml
    env HTTP_PROXY=http://192.168.0.1:8080/ urlwatch --urls /path/to/urllist-proxy.yaml --config /path/to/config-proxy.yaml
