### ISSUE TITLE
FYI: fedora is current 

### ISSUE THREAD

**Issue by whitel** [thp/urlwatch#178]
Your webpage: https://thp.io/2008/urlwatch/ says fedora's version is out of date. I just came across your tool and want to use it and noticed:

Name         : urlwatch
Version      : 2.6
Release      : 4.fc26
Arch         : noarch
Size         : 68 k
Source       : urlwatch-2.6-4.fc26.src.rpm
Repo         : fedora
Summary      : A tool for monitoring webpages for updates
URL          : http://thpinfo.com/2008/urlwatch/
License      : BSD
Description  : This script is intended to help you watch URLs and get notified (via
             : email or in your terminal) of any changes. The change notification
             : will include the URL that has changed and a unified diff of what has
             : changed.
             : 
             : The script supports the use of a filtering hook function to strip
             : trivially-varying elements of a webpage.
             : 
             : Basic features
             : 
             : * Simple configuration (text file, one URL per line)
             : * Easily hackable (clean Python implementation)
             : * Can run as a cronjob and mail changes to you
             : * Always outputs only plaintext - no HTML mails :)
             : * Supports removing noise (always-changing website parts)
             : * Example hooks to filter content in Python

Nothing serious but, the maintainer does seem to be keeping up.

**Comment by thp** [comment]
Fixed. Thanks :)
