### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by xiaoheihei3211** [thp/urlwatch#179]
Hi, I am encountering this error: 

![issue2](https://user-images.githubusercontent.com/32118970/31208972-cab9a02e-a9ba-11e7-8c10-ac2aa75e3ce0.PNG)

This is my hooks.py file: 

```
import re
from urlwatch import filters
from urlwatch import jobs
from urlwatch import reporters
from bs4 import BeautifulSoup



class CustomMatchUrlFilter(filters.AutoMatchFilter):
    # The AutoMatchFilter will apply automatically to all filters
    # that have the given properties set
    MATCH = {'url': 'https://example.com'}

    def filter(url,data):

      if url == ("https://example.com"):
        soup = BeautifulSoup(data,'html.parser')

        for div in soup.find_all("div",{'class':'content'}):
         div.decompose()

        return str(soup)

      else:
        return None

```
May I know whats causing this error?

**Comment by thp** [comment]
You have to return `data` if you are not modifying it, not `None`.

**Comment by xiaoheihei3211** [comment]
Have solved the error, thanks! However, even though the code works, it still doesn't filter away any <div class="content">. I want to exclude this tag and class in the monitoring of my web page so that no alert is generated if contents in <div class="content"> changed. Any idea what has gone wrong?
