### ISSUE TITLE
hooks.py filtering multiple URLs 

### ISSUE THREAD

**Issue by dotox** [thp/urlwatch#182]
I want to filter multiple different URL using the same custom filter but how do I insert multiple URL in MATCH{} ? 

Have tried this but doesn't work: 

```
class CustomMatchUrlFilter(filters.AutoMatchFilter):
    # The AutoMatchFilter will apply automatically to all filters
    # that have the given properties set
    MATCH = {'url': ["https://www.example.com","https://www.example.com/about-us"]}
```
What might be the issue here?

**Comment by thp** [comment]
The `AutoMatchFilter` is really restricted in what it can do, it just matches with `==` (see https://github.com/thp/urlwatch/blob/master/lib/urlwatch/filters.py#L96), you can however subclass from `FilterBase` and do your own `match()` function, for example:

```
class CustomMatchUrlFilter(filters.FilterBase):
    def match(self):
        d = self.job.to_dict()
        return d.get('url', None) in ["https://www.example.com","https://www.example.com/about-us"]

    ...
```
