### ISSUE TITLE
Escaping : inside grep filter

### ISSUE THREAD

**Issue by gaia** [thp/urlwatch#184]
How do I escape a : inside a grep filter?

**Comment by bonanza123** [comment]
To the best of my knowledge it uses [re.search](https://docs.python.org/3/library/re.html). You should find your answer there.

**Comment by jwilk** [comment]
Unless I'm missing something, colons don't need any escaping.

Commas (which need escaping, because they would otherwise be treated as separators between filters) can be escaped as `\054`.

**Comment by thp** [comment]
Merging this one into #154.
