### ISSUE TITLE
Feature request: Different reporters for different URLs

### ISSUE THREAD

**Issue by MoonshineSG** [thp/urlwatch#186]
Is it possible to select different report method for different URLs ?

**Comment by ad-m** [comment]
No, there is no build-in way to select different report method for different URL's. Just use different config file. See example at #176.

**Comment by schildbach** [comment]
I think this would be worthwhile to have. Each `url` section could have an optional `reporter: <list>` attribute. If present, it would determine which reporters are enabled for the corresponding url. If not present, the default would be used (defined by the current enabled flags on the reporters themselves).

**Comment by MoonshineSG** [comment]
:D a feature that is requested by a second user , 4.5 years later is unlikely to be implemented... (if anyone is still maintaining this repo).
But I appreciate the tumbs up... Cheers!

**Comment by MoonshineSG** [comment]
appologies.... it is actively maintained!!!

**Comment by thp** [comment]
For now, separate (sets of) configuration files is the way to go.
