### ISSUE TITLE
Fall back to old behavior if smtp user isn't configured

### ISSUE THREAD

**Issue by kyrias** [thp/urlwatch#187]
Since https://github.com/thp/urlwatch/commit/610407d1177539b72b7b2dda1a8860a8b2613172 urlwatch will fail if your config doesn't specify `smtpd.user`.  It would be preferable if the old behavior would be preserved when one isn't specified rather than raising an exception.

**Comment by e-dschungel** [comment]
Same issue for me. My suggestion to fix that is in #188

**Comment by thp** [comment]
#188 has been merged, closing.
