### ISSUE TITLE
Question : Can I set the sender's name when sending mail using SMTP?

### ISSUE THREAD

**Issue by pstanton237** [thp/urlwatch#190]
Hello,
I set email in the urlwatch configuration as below.
And the sender name of the email I receive is just 'no-reply@example.org'.

I think it would be better if I could set the sender's name. It's like we can set our own name when we send an email.
For example, urlwarch-monitoring

Is this supported by the current urlwatch?

Thanks! :)

> report:
   email:
     enabled: true
     from: 'no-reply@example.org'
     html: true
     method: smtp
     sendmail:
       path: sendmail
     smtp:
       host: smtp.example.org
       keyring: false
       port: 25
       starttls: false
     subject: '{count} changes: {jobs}'
     to: 'someon2@example.org'

**Comment by thp** [comment]
What if you use this?

    from: 'Your Name <noreply@example.org>'

That should do the trick, no? (note that you might also need to set the SMTP username in this case.

**Comment by kbabiochSUSE** [comment]
@thp: This "work-around" does **not** work - at least for me.

**Comment by schildbach** [comment]
I'm looking for a way to set the sender name, too. If the method @thp suggested would work, that would be very convenient.

**Comment by thp** [comment]
Add a `from` item to the `email` section of the config (there's an empty one in the default config).
