### ISSUE TITLE
Handling URL errors

### ISSUE THREAD

**Issue by gaia** [thp/urlwatch#191]
if a site doesn't respond for whatever reason, you wake up to hundreds of alerts.

it would be useful to give the user the option to notify only once and/or throttle error notifications...

**Comment by maximbaz** [comment]
I have a similar suggestion, posted here: https://github.com/thp/urlwatch/pull/180#issuecomment-351417020

**Comment by gaia** [comment]
yes, this is badly needed

**Comment by gaia** [comment]
maybe this is accomplished by setting config to

```
display:
  error: false
```

?

**Comment by maximbaz** [comment]
I haven't tried it, but the risk could be that a url is permanently moved and thus not accessible anymore, and you will never know about it because all the errors are suppressed.

**Comment by thp** [comment]
Closing this as fixed now in #180, where you can specify a retry count to silence some errors while still making it possible to catch permanently-moved pages. Combined with maybe a reduced polling frequency, this should do the job just fine.
