### ISSUE TITLE
config documentation

### ISSUE THREAD

**Issue by kobeyy** [thp/urlwatch#193]
Is there some form of documentation for the config file? I'm trying to use the email option but i can't find the right setting for the authentication. 
I've tried multiple smpt servers en multiple keywords for the password but always got a message like this:
`smtplib.SMTPSenderRefused: (530, b'5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM3PR04CA0150.eurprd04.prod.outlook.com]', 'name@hotmail.com')
`

these where the settings that i used.
email:
    enabled: true
    from: 'name@hotmail.com'
    html: true
    method: smtp
    sendmail:
      path: sendmail
    smtp:
      host: 'smtp-mail.outlook.com'
      user: 'name@hotmail.com'
      password: 'password-of-outlook-account'
      keyring: false
      port: 587
      starttls: true
    subject: '{count} changes: {jobs}'
    to: 'mail@icloud.com'
  html:
    diff: unified

**Comment by jstnmchl** [comment]
If you are still struggling with this issue you could take a look at the example config file and accompanying instructions posted to a separate but related issue (found here: https://github.com/thp/urlwatch/issues/158 ).
The example is for Gmail rather than icloud but may act as a starting point.

**Comment by thp** [comment]
This is now fixed (see `README.md` for instructions how to set it up).
