### ISSUE TITLE
os.getlogin() - Inappropriate ioctl for device

### ISSUE THREAD

**Issue by ghost** [thp/urlwatch#2]
Hello. In the file `handler.py`, line 173, you use `os.getlogin()`.
According to the `os.getlogin()` doc, it « Returns the user logged in to the controlling terminal of the process. ».

It means that if there is no controlling terminal, because urlwatch is launched by cron, or by a systemd.service for example, it will fails with this error:
`OSError: [Errno 25] Inappropriate ioctl for device`

You can find a "fix" for a similar issue in the gitpython repositery: https://github.com/swallat/GitPython/commit/f362d10fa24395c21b1629923ccd705ba73ae996

Thank you for this program.

**Comment by UmutAlihan** [comment]
same issue here
