### ISSUE TITLE
How to get real time notification to telegram?

### ISSUE THREAD

**Issue by user154** [thp/urlwatch#200]
Hi , i would like to get real time notification , at the moment something changes in the url notification will be send.

Is it possible?

**Comment by ad-m** [comment]
Due to the operation of the application that checks cyclic changes, it is not possible to obtain an immediate notification. You can increase the call frequency to get almost instant notification.

**Comment by user154** [comment]
And how can i do it?

**Comment by ad-m** [comment]
Follow [Quick Start](https://github.com/thp/urlwatch#quick-start) and increase frequency time in crontab.
