### ISSUE TITLE
Is it possible to filter by changed or unchanged?

### ISSUE THREAD

**Issue by GalTurgeman** [thp/urlwatch#201]
Hi i would like to filter by if there was changes or not, if there is dont send the html file, send unique message.

I am using telegram for notification.

**Comment by kbabioch** [comment]
Could you be more specific and/or provide some examples on when you expect what? What is your configuration looking like?

Filters in the context of urlwatch are used to modify the retrieved content. This content is saved and compared against the version retrieved before. If there are changes, you will be notified, if nothing changes, you won't.

**Comment by thp** [comment]
If you set the `details` configuration option of the text/markdown reporters to `false`, you will only get the summary, maybe this is what you are after.
