### ISSUE TITLE
handle 503 requests

### ISSUE THREAD

**Issue by manuelsousa7** [thp/urlwatch#203]
It would be a good feature to handle 503 requests. Sometimes pages are under maintenance, triggering a false positive that is perfectly controllable. The cron jobs would still work normally, but every time a 503 request ou a personalised page appears, the job would ignore those pages.

**Comment by thp** [comment]
If we are going to implement it, would it make sense to specify which HTTP errors should be ignored?

**Comment by kbabioch** [comment]
Yes, @thp I think making this configurable makes the most sense, since it is impossible to know who wants what in terms of HTTP status codes.

**Comment by cfbao** [comment]
I think we can expand the `ignore_connection_errors` attribute to allow specifying error code. For example,
```yaml
ignore_connection_errors: 404, 503
```

Also, I think it's better to move the ignore logic from `worker.py` into job classes, so each class can have their own error handling logic. The code in `worker.py` becomes
```python
    ...
    elif job_state.job.ignore_exception(job_state.exception):
        logger.info(...)
    ...
```
where each class implements their own `ignore_exception` that returns `True`/`False`.
