### ISSUE TITLE
Getting Duplicate notifications via Pushbullet

### ISSUE THREAD

**Issue by shaun-ba** [thp/urlwatch#209]
Ever since i upgraded to the latest version I'm getting two notifications for the same event via pushbullet. The logs from my cronjobs only show 1 event, so why is this happening?

**Comment by ad-m** [comment]
Do you have duplicate urls?

**Comment by shaun-ba** [comment]
No, the only thing i can think is that i updated (only happened since update), and i read something about the new version updating old configs itself. Could that cause some unexpected behaviour ?

**Comment by thp** [comment]
@shaun-ba Is that still an issue with the latest version of urlwatch?

**Comment by shaun-ba** [comment]
I'm still getting duplicates so let me update today and report back

**Comment by cron410** [comment]
I am also getting duplicates. Android 8.1 on a Pixel sending notifications to Opera on Win10.

**Comment by cron410** [comment]
I am having the same issues and not using urlwatch. It may be a Pushbullet issue. I'm running Opera on Win10 to receive the notifications. Happens about 2 minutes apart for me.

**Comment by thp** [comment]
Closing this one based on the last comment, please reopen if it's something urlwatch-specific.
