### ISSUE TITLE
Filter diff results

### ISSUE THREAD

**Issue by csill1634** [thp/urlwatch#21]
It is possible to define custom hooks to "prepare" the content of the website for parsing. However, this happens before calculating the diff. I'm wondering if there is an easy way to define hooks that are executed after calculating the diff? For example, sometimes I only want to be informed if content is added to an website and do not care about the content that has been removed since the last visit. The simplest way (as I'm doing now with a quickly hacked grep parser) would be to remove any lines starting with "-" from the resulting diff. Is there any way to achieve this cleanly with urlwatch?

**Comment by thp** [comment]
Hm, in general you couldn't distinguish between stuff being added and stuff being modified (without a more advanced diff). However, I'd be happy to accept a patch that optionally allows for "diff" hooks that take both inputs and return a diff (overriding the default diff algorithm). This way, modifications could be detected as well as new additions.

**Comment by thp** [comment]
See also #25

**Comment by thp** [comment]
In urlwatch 2, diffing is part of a "Reporter" class, and you can write your own (the output of that can be something that's not even a diff, and also it can either go to stdout or sent via e-mail, etc...
