### ISSUE TITLE
question: how to set up a default filter?

### ISSUE THREAD

**Issue by monperrus** [thp/urlwatch#213]
I want to set up a default filter for all URLs that have no `filter` config.

How to do that?

**Comment by monperrus** [comment]
by creating `.urlwatch/lib/hooks.py`
For example:

```
from urlwatch import html2txt

def filter(url, data):
  return html2txt.html2text(data, method='pyhtml2text')

```

**Comment by patric-r** [comment]
Is this still valid for urlwatch 2.17?
