### ISSUE TITLE
ImportError: cannot import name 'html2text'

### ISSUE THREAD

**Issue by shaun-ba** [thp/urlwatch#214]
Thought I would log this as I assume it isn't expected!

Version 2.8
Ubuntu 16.04.4

```
  File "/usr/local/lib/python3.5/dist-packages/urlwatch-2.8-py3.5.egg/urlwatch/filters.py", line 171, in filter
    from .html2txt import html2text
ImportError: cannot import name 'html2text'
```

**Comment by thp** [comment]
`python3 -m pip install html2text`

**Comment by shaun-ba** [comment]
@thp Things have been working fine for many weeks, I've only got one trace for this but every URL entry has this html2text param.

**Comment by thp** [comment]
Try installing a newer version of urlwatch.
