### ISSUE TITLE
Sending report to multiple e-mail addresses

### ISSUE THREAD

**Issue by pipsae24** [thp/urlwatch#216]
I have tried multiple different ways to e-mail the report to multiple users via the urlwatch.yaml file; however only one user receives the report each time.  What exactly needs to be done to have this report sent to more than one person?  I am using smtp.

I have tried:

1. to: 'email1,email2'
2. to: 'email1;email2'
3. to: 'email1','email2'
4. to: 'email1';'email2'
5. to: email1,email2
6. to: email1;email2
7. to: email1
    to: email2
8. to: ['email1','email2]

and others as well and nothing has worked.  Can anyone help me?  Thanks.

**Comment by cjohnsonuk** [comment]
First one should work if you're using sendmail as the mailing method. I'm just about to start testing...

**Comment by thp** [comment]
Closing as working with sendmail.
