### ISSUE TITLE
question: how to disable notifications when network is broken

### ISSUE THREAD

**Issue by monperrus** [thp/urlwatch#218]
Sometimes, crontab starts urlwatch while network is stopped or intermittent.

I then get irrelevant notifications:

    HTTPConnectionPool(host='foo.se', port=80): Max retries exceeded with url: /ddgf/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd66c79b128>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

How to disable notifications when there is a `NewConnectionError`?

**Comment by kbabioch** [comment]
This is currently not possible. urlwatch works under the assumption that the network is available, otherwise it makes not much sense to monitor URLs, which are mostly online resources, without network connectivity. You can fix this in the code (e.g. look at the handler/worker logic), but no with the configuration.

**Comment by monperrus** [comment]
Thanks for your answer. Would you accept a pull-request adding support for this?

**Comment by kbabioch** [comment]
I'm not the maintainer (only a contributor) of this project, so it's not up to me ;). @thp is probably willing to accept a PR, if it makes sense (TM). Personally, I would make this configurable via a `ignore_network` switch. It can be implemented very similarly to a recent pull request of me (#257). 

You can add `ignore_network` as an optional argument to the `UrlJob` and check for it in the handler/worker logic. Through `job_state.exception` you can evaluate what exception was raised.

**Comment by kbabioch** [comment]
I've implemented this. See commit 7c19a6acf1e410251958074c21d3ce0416d70775. Please give it a try, and let me know if this solves your issue. I will submit this as pull request then.

**Comment by monperrus** [comment]
`curl https://github.com/thp/urlwatch/commit/7c19a6acf1e410251958074c21d3ce0416d70775.patch | git apply`

works for me!

Thanks a lot.

**Comment by thp** [comment]
#261 is merged.
