### ISSUE TITLE
Please set $VISUAL or $EDITOR

### ISSUE THREAD

**Issue by Canorus** [thp/urlwatch#222]
when I try to edit or edit-config urlwatch, it asks me to set $VISUAL or $EDITOR, but they are set in .bash_profile as `nano` and `vi`. Any suggestion?

![2018-04-01 14-41-30](https://user-images.githubusercontent.com/7209435/38170251-04b3dff6-35bb-11e8-845d-f79346684116.png)

**Comment by thp** [comment]
Did you [export](https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html#index-export) the variables so that they are visible to child processes?

```
export EDITOR
export VISUAL
```

**Comment by Canorus** [comment]
thanks. that worked.

I have to export them every terminal session though. What have I missed? or is this intended?
