### ISSUE TITLE
The coloring of the stdout is not working

### ISSUE THREAD

**Issue by fylux** [thp/urlwatch#225]
The program is supposed to print the list of changed URLs with colors (Errors in red and the rest in blue).  However this never happens because the program tries to identify lines with some prefixes (`'NEW:', 'CHANGED:', 'UNCHANGED:', 'ERROR:'`) but it doesn't take into account that the lines start with enumeration (`01. CHANGED:`) which results in executing the final else.

In the file /lib/urlwatch/reporters.py:
```python
for line in body.splitlines():
   # FIXME: This isn't ideal, but works for now...
   if line in separators:
      print(line)
   elif line.startswith('+'):
      print(self._green(line))
   elif line.startswith('-'):
      print(self._red(line))
   elif any(line.startswith(prefix) for prefix in ('NEW:', 'CHANGED:', 'UNCHANGED:', 'ERROR:')):
      first, second = line.split(' ', 1)
      if line.startswith('ERROR:'):
         print(first, self._red(second))
      else:
         print(first, self._blue(second))
   else:
      print(line)
```

**Comment by thp** [comment]
Oh yeah, that part of the code probably needs updating then. Maybe this?

    if any(re.match(r'^\d+\. %s' % prefix, line) for prefix in ...):
        ...

**Comment by thp** [comment]
Oh well, I checked again, this actually works as expected:

![screen shot 2018-06-03 at 13 43 57](https://user-images.githubusercontent.com/135241/40886208-397a38c0-6734-11e8-91d1-c5ef1f99c45a.png)

Note that the coloring is only applied to the "details" view, not the summary view.
