### ISSUE TITLE
Run the program so it loop when I run the command.

### ISSUE THREAD

**Issue by Alpflex** [thp/urlwatch#227]
How do I run the program so it loop when I run the command "/ Users / USER / Desktop / url / urlwatch-master / urlwatch" in the terminal. So when I run the command once, it will run through itself(a loop, like a while-loop).

**Comment by thp** [comment]
Best would be to install Bash on Windows (via the Linux Subsystem) and run it there, failing that, here are some suggestions: https://superuser.com/questions/66975/do-something-every-10-seconds-batch-file -- please don't use 10 seconds as the interval, but something like 30 minutes at least.

**Comment by thp** [comment]
...or you could use the Windows Task Scheduler:

https://www.makeuseof.com/tag/windows-10-task-scheduler-gives-power/

**Comment by Alpflex** [comment]
Thanks for your reply, but I'm on mac OS X and I'm also planning to host it on heroku.com for personal use. How should I do if I want to host it??
Thanks

**Comment by thp** [comment]
On macOS and Linux, you can either use it like this with a shell script:

    while : ; do
        /path/to/urlwatch
        sleep $((5 * 60))
    done

Or you can add it to cron as a cronjob (google for how to set up cron jobs).

**Comment by thp** [comment]
Closing as "fixed".
