### ISSUE TITLE
Ubuntu Package Install

### ISSUE THREAD

**Issue by gaia** [thp/urlwatch#228]
on Ubuntu 16.04

`apt install urlwatch`

followed by

`urlwatch --edit-config`

I get

```
Usage: urlwatch [options]

Watch web pages and arbitrary URLs for changes

urlwatch: error: no such option: --edit-config
```

Is the Ubuntu package (I know it is not maintained by the author of this repository) completely outdated so that it works very differently or am I missing something?

**Comment by mwerlen** [comment]
Hi,

Urlwatch package on Ubuntu 16.04 is completely outdated (version 1.15). You can find the documentation by using `man ulwatch` in your terminal.

[Urlwatch 2](https://packages.ubuntu.com/fr/bionic/urlwatch) will be landing in Ubuntu 18.04 (bionic).

Maxime

**Comment by gaia** [comment]
thanks for the update!
