### ISSUE TITLE
Hang on Starting new HTTP connection

### ISSUE THREAD

**Issue by Zitt** [thp/urlwatch#230]
Installed urlwatch 2.9 using python 3.5.1 and pip3 on a synology NAS.

Trying to monitor 
http://www.newark.com/keysight-technologies/5063-2135/test-probe/dp/66K7040
for when it goes in stock.

running urlwatch appears to hangs with the follow verbose message:

`2018-05-06 02:07:05,507 urlwatch INFO: turning on verbose logging mode`
`2018-05-06 02:07:05,534 minidb DEBUG: PRAGMA table_info(CacheEntry)`
`2018-05-06 02:07:05,536 main INFO: Using `_pathHidden_`/.urlwatch/urls.yaml as URLs file`
`2018-05-06 02:07:05,536 main INFO: Using  `_pathHidden_`/.urlwatch/hooks.py for hooks`
`2018-05-06 02:07:05,536 main INFO: Using  `_pathHidden_`/.cache/urlwatch/cache.db as cache database`
`2018-05-06 02:07:05,540 main INFO: Found 1 jobs`
`2018-05-06 02:07:05,540 worker DEBUG: Processing 1 jobs`
`2018-05-06 02:07:05,542 handler INFO: Processing: <url name='AgilentTips' url='http://www.newark.com/keysight-technologies/5063-2135/test-probe/dp/66K7040'>`
`2018-05-06 02:07:05,544 minidb DEBUG: SELECT data, timestamp FROM CacheEntry WHERE guid = ? ORDER BY timestamp DESC LIMIT ? ['e9c81c422fdb17594635be0934092a5ac358e454', 1]`
`2018-05-06 02:07:05,551 connectionpool DEBUG: Starting new HTTP connection (1):`
`www.newark.com`

Willing to help debug; just make a request

**Comment by thp** [comment]
Does it hang indefinitely? We do have a 60-second socket timeout. Or is the server itself accepting the connection but then never finishing the request?

**Comment by Zitt** [comment]
It appears to hang indefinitely. The last message is:

2018-06-03 13:31:21,900 connectionpool DEBUG: Starting new HTTP connection (1):
www.newark.com

and it's now 1:36. 
I don't know if the server is responding to python... but opening the url in chrome seems to work. 
However, I'm noticing that WGET and CURL aren't connecting to the site either. Maybe it's a setup issue on the NAS.

**Comment by Zitt** [comment]
More info... it appears the site is doing something funky with useragent.

This works:

curl --verbose https://www.newark.com/keysight-technologies/5063-2135/test-probe/dp/66K7040 -A "Mozilla/5.0 (X11; Linux x86_64)"

any thoughts on how to make urlwatch fake a user agent?

**Comment by thp** [comment]
You can do this with custom HTTP headers, as seen in #229.

**Comment by Zitt** [comment]
Perfect. Upgraded to urlwatch 2.13 via pip.
Adding the following yaml lines:

`headers:`
`  User-Agent: Mozilla/5.0 (X11; Linux x86)`

works well now.
