### ISSUE TITLE
Feature request : custom "to:" for each "url:"

### ISSUE THREAD

**Issue by cjohnsonuk** [thp/urlwatch#234]
Different people in my organisation need to be notified of changes to different web pages.  At the moment it appears I can only set "to:" in the config.

Can a "to:" be set in the urls.yaml ?
eg:
```
kind: url
name: GDPRTableOfContents1
url: https://<<URL1>>/
filter: element-by-class:toc,html2text
to: 'user1@domain.com,user3@domain.com'
---
kind: url
name: GDPRTableOfContents2
url: https://<<URL2>>/
filter: element-by-class:toc,html2text
to: 'user2@domain.com'
```

At the moment I can only see that creating a complete duplicate `config` file and `urls` file running urlwatch twice, once with each pair of files set as command line parameters would work.

**Comment by cjohnsonuk** [comment]
Tested using duplicate `config` file and `urls` file customised for each target audience and running urlwatch twice and it works fine.

**Comment by thp** [comment]
In theory this is a really good feature request, but at the moment, all detected URL changes are put into a single e-mail (to reduce the number of e-mails sent), so having different "to:" fields would make that a bit more complicated (jobs might be grouped by receiver, and probably needs to group it also in such a way that multiple users work, etc..).

Also, the "To:" in your case is specifically tailored towards e-mail notifications, and while this is probably the most-used reporting mechanism, there's also support for Pushover, Pushbullet, Telegram and others, so in that case it might make sense to override it for those as well (which makes things even more complicated..).

So maybe this is better done with duplicate files for now (then you can customize EVERYTHING :) and running urlwatch twice. If you come up with a nice "multi-urlwatch" wrapper script (that e.g. maintains pairs of config/urls files or something), that might be something that I could see shipping with urlwatch as an example auxilliary script).

Closing this feature request for now..

**Comment by cjohnsonuk** [comment]
2 files is working fine at the moment.  Thanks.  :-)
