### ISSUE TITLE
Add versions to ChangeLog

### ISSUE THREAD

**Issue by sbraz** [thp/urlwatch#235]
Hi, could you add versions to the changelog? Currently not all versions are listed, sometimes there's just the date. This forces me to use git blame to find out the matching version.

I'm also thinking of further improvements such as:
- converting it it to Markdown
- reversing it to make it easier to read

**Comment by thp** [comment]
Hm, I wonder if we should remove the ChangeLog file completely and just rely on the `git log` (and/or `git shortlog`) output?

**Comment by thp** [comment]
There you go! Now that it's there for the most recent entries, for the next release I'll probably just follow the same format please reopen if I forget to do that :)

**Comment by sbraz** [comment]
@thp What do you think of https://github.com/sbraz/urlwatch/blob/changelog/newlog.md ?

**Comment by thp** [comment]
@sbraz I went with this one now: https://github.com/thp/urlwatch/blob/master/CHANGELOG.md

**Comment by thp** [comment]
@sbraz Oh and if you want, feel free to create a pull request to re-add old ChangeLog entries in the same style to the `CHANGELOG.md` file if you feel like. I personally don't see the benefit for anything older than 2 years for this project at the moment, but then even Debian stretch (current stable) contains version 1.15, so it might be sensible to go down to even that old version, but even Debian testing already contains version 2.11, which is included in the new `CHANGELOG.md`.

**Comment by sbraz** [comment]
Yeah I don't think that will be an issue. Maybe you could provide a link [to the old changelog](https://github.com/thp/urlwatch/blob/38c5cd332c7b07f810ea85009882f4b3c110749d/ChangeLog) at the end? In case archaeologists want to read up on urlwatch 😛

Even if you don't, I find the current changelog totally satisfying!

**Comment by thp** [comment]
Done in 5f511452a432ad6e03f26c4135f1b773ef3100f1
