### ISSUE TITLE
Output captured content for new urls instead of "..."

### ISSUE THREAD

**Issue by maximbaz** [thp/urlwatch#237]
I use the `filter` extensively to select as small and relevant piece of webpage as possible. However, every time I'm not sure, what if I made a mistake in my filter and `urlwatch` grabbed a wrong output? All I get when I configure a new url is "...".

https://github.com/thp/urlwatch/blob/6d36738b1d86932bcad9872a83b23238fe09f852/lib/urlwatch/reporters.py#L193-L194

I would like `urlwatch` to print the captured content for new urls instead of "...", so that I can see and validate what it was able to retrieve. That will give me confidence that I configured everything properly.

**Comment by thp** [comment]
This is now solved in a bit of a different way, the master branch has a new command-line option `--test-filter` that allows you to run a job through the filter you have specified and see the output. I decided not to do it via the "NEW" notification, as then it would require a "real" urlwatch run, and each URL is only "new" once, whereas testing filters is something you probably want to run multiple times.

**Comment by maximbaz** [comment]
This sounds even better, thanks, I'll give it a try!
