### ISSUE TITLE
Wiki / how-to - installing urlwatch in container

### ISSUE THREAD

**Issue by coffeecer** [thp/urlwatch#238]
Dear @thp and other contributors,

URLWatch has a very good project and has interesting concept. I was looking for such open source tool because of 2 reasons - functionality (need to track changes at some static web pages) and everything related to license type. 

For a person not related to programing it is actually very hard to install URLWatch and required environment. Are there any options available for "dummies" / users with low level of competency? 

I mean - is it possible to share "container" with preinstaled framework and project in it? Google App Engine offers 1 year of free access and it might be a good option to run such container. 

Thank you in advance.

**Comment by thp** [comment]
I guess that's mostly out of scope to document all the possible deployment scenarios, but here's some guidance:

1. Make sure Python 3 + pip is installed
2. Run `python3 -m pip install --upgrade urlwatch`
3. Run `urlwatch --edit` to configure your watch list
4. Run `urlwatch --edit-config` to set up notifications
5. Run `crontab -e` or something to periodically schedule `urlwatch` runs
