### ISSUE TITLE
Documentation issue: lynx is no longer the default html2txt subfilter

### ISSUE THREAD

**Issue by sbraz** [thp/urlwatch#239]
https://github.com/thp/urlwatch/blob/a4dbfc70bda04b1761cc7694d7d20fd90bb6f8d9/lib/urlwatch/html2txt.py#L39-L46 says that the default subfilter is `lynx` when it is actually `re`, right?
https://github.com/thp/urlwatch/blob/a4dbfc70bda04b1761cc7694d7d20fd90bb6f8d9/lib/urlwatch/filters.py#L162-L163

`lynx` may still be the default value for the function's subfilter parameter but it is no longer used, is it?

**Comment by bonanza123** [comment]
It would also be nice to mentioned how the `subfilter` can be set from `urls.yaml` file.

**Comment by sbraz** [comment]
@bonanza123 That's documented here though: https://github.com/thp/urlwatch/blob/f47ec68886714e07c5ba7c04aa8bc39d38b2020a/share/urlwatch/examples/hooks.py.example#L53

**Comment by thp** [comment]
Note that the internal docstring probably didn't appear anywhere in user-facing documentation, but since we're anyway always supplying the parameters, I've removed the default parameters from there now.
