### ISSUE TITLE
urlwatch reports all urls as NEW after a network error

### ISSUE THREAD

**Issue by maximbaz** [thp/urlwatch#242]
1. Add a new URL to `urls.yaml`
1. Run `urlwatch` - the url is marked as NEW (expected)
1. Run `urlwatch` again - no changes (expected)
1. Disconnect internet
1. Run `urlwatch` - network error
1. Connect internet
1. Run `urlwatch`

Expected: no changes
Actual: all urls are marked as NEW

Started to happen after upgrading from 2.9 to 2.11 (ArchLinux package skipped 2.10).

**Comment by thp** [comment]
Fixed in version 2.12, thank you for the bug report!
