### ISSUE TITLE
Parse for differences by sentence, rather that HTML block from HTML2TEXT

### ISSUE THREAD

**Issue by cjohnsonuk** [thp/urlwatch#243]
Sometimes html2text results in long blocks of text as a single line.  If a change is made to one sentence then diff highlights the whole block as a change making it take longer to find exactly where the difference is.  I used `urlwatch --edit-hook`
and added this code
```
import re
from urlwatch import filters
from urlwatch import jobs
from urlwatch import reporters
class ToSentences(filters.FilterBase):
    """Convert plain text to one sentence per line so diffs are per sentence rather than per html line"""
    __kind__ = 'tosentences'
    def filter(self, data, subfilter=None):
        self._no_subfilters(subfilter)
        return re.sub("(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s","\n", data)
```
to create a new filter called `tosentences` that splits each sentence onto a new line so diff now only highlights the sentences that have changed, not the whole paragraph.  

This is my first python coding in ages and I've basically googled my way to a working result.  In basic testing it seems to work OK, it doesn't split URLs on the . character, it splits on ? but not currently on ! or : or ; or other similar sentence endings.  I did try to use a different reg exp 
```
import re
from urlwatch import filters
from urlwatch import jobs
from urlwatch import reporters
class ToSentences2(filters.FilterBase):
    """Convert plain text to one sentence per line so diffs are per sentence rather than per html line"""
    __kind__ = 'tosentences2'
    def filter(self, data, subfilter=None):
        self._no_subfilters(subfilter)
        sentence_regex = ur'([\.\?!][\'\"\u2018\u2019\u201c\u201d\)\]]*\s*(?<!\w\.\w.)(?<![A-Z][a-z][a-z]\.)(?<![A-Z][a-z]\.)(?<![A-Z]\.)\s+)'
        regex = re.compile(sentence_regex, flags=re.UNICODE)
        return regex.split(data)
```
from https://mikedombrowski.com/2017/04/regex-sentence-splitter/
but it threw a syntax error that I couldn't identify and don't have time to work around.

It would be good if `<li>` elements on one line in HTML were split but this, i think, is a function of the html2text  not this filter.  I guess a similar reg exp filter could be created to run BEFORE html2text to split adjacent `</li><li>` with a \n to preserve the line feeds in plain text that the list elements create in HTML.  I'm not sure if html2text preserves other "new lines" eg for `<p><br></h{n}></tr>`

Hopefully this will be useful to someone...
... or maybe tidied up and included as a new standard filter...

**Comment by thp** [comment]
Wouldn't something like [wdiff](https://www.gnu.org/software/wdiff/) be better suited in that case? Like, maybe being able to customize the diffing algorithm used on a per-job basis?

**Comment by cjohnsonuk** [comment]
I've not used wdiff to know whether it would be better.... ;-)

**Comment by thp** [comment]
This should now be possible with the current Git master branch (not yet released) by adding a `diff_tool: wdiff` config option to each job where you want to do this (and installing `wdiff` somehow, e.g. `apt install wdiff` or `brew install wdiff` or something).

**Comment by cjohnsonuk** [comment]
Just upgraded to v 2.21.  My tosentences hook has been working great but its throwing an error now.  
This is my urls.yaml:
```
kind: url
name: DevTest
url: https://my.domain.com/
filter:
  - element-by-id: pagelist
  - html2text
  - tosentences
---
```
If there are no differences it runs without error.
If there is a difference I get this:
```
===========================================================================
01. ERROR: DevTest
===========================================================================

---------------------------------------------------------------------------
ERROR: DevTest ( https://my.domain.com/ )
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urlwatch/handler.py", line 113, in process
    data = FilterBase.process(filter_kind, subfilter, self, data)
  File "/usr/local/lib/python3.6/site-packages/urlwatch/filters.py", line 146, in process
    return filtercls(state.job, state).filter(data, subfilter)
  File "/root/.config/urlwatch/hooks.py", line 13, in filter
    self._no_subfilters(subfilter)
AttributeError: 'ToSentences' object has no attribute '_no_subfilters'
---------------------------------------------------------------------------

```

and this is the hooks file it refers to : 

```
import re

from urlwatch import filters
from urlwatch import jobs
from urlwatch import reporters

class ToSentences(filters.FilterBase):
    """Convert plain text to one sentence per line so diffs are per sentence rather than per html line"""

    __kind__ = 'tosentences'

    def filter(self, data, subfilter=None):
        self._no_subfilters(subfilter)
        #pattern = "(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s"
        #repl = "\n"
        return re.sub("(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s","\n", data)

```
I've removed the line
```
self._no_subfilters(subfilter)
```
and it appears to work but I'm not sure what this line does or whether an alternative is needed.

I'm guessing I could replace my tosentences in my yaml file with the re.sub from the hooks file, I'm looking into that today but  I use this in many places and it looks a lot neater with the tosentences in the filter list

Still a python noob so open to your recommendations / suggestions

**Comment by thp** [comment]
This was unfortunately not mentioned in the changelogs, but it's now:

```python3
class ToSentences(filters.FilterBase):
    """Convert plain text to one sentence per line so diffs are per sentence rather than per html line"""

    __kind__ = 'tosentences'

    __no_subfilter__ = True 

    ...
```

**Comment by thp** [comment]
And yes, you can replace this with a YAML filter (untested, but assumed working):

```yaml
url: https://example.com/
filter:
    - re.sub:
        pattern: '(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s'
        repl: '\\n'     
```

**Comment by cjohnsonuk** [comment]
Thanks for getting back so quickly with a fix!  This tool is saving me so much time!  My next job is to put the contents of all my url yaml files in a DB so I can manage them more easily and then create a script that dynamically creates the config and url files for each run so I can more easily determine the email recipients for each batch of URLs.

I've added the line  `__no_subfilter__ = True ` to `hooks.py`

but when I run `urlwatch --edit-hooks` I get this 
```
urlwatch --edit-hooks
Traceback (most recent call last):
  File "/bin/urlwatch", line 107, in <module>
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "/usr/local/lib/python3.6/site-packages/urlwatch/main.py", line 66, in __init__
    self.load_jobs()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/main.py", line 87, in load_jobs
    jobs = self.urls_storage.load_secure()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/storage.py", line 303, in load_secure
    if shelljob_errors and any(is_shell_job(job) for job in jobs):
  File "/usr/local/lib/python3.6/site-packages/urlwatch/storage.py", line 303, in <genexpr>
    if shelljob_errors and any(is_shell_job(job) for job in jobs):
  File "/usr/local/lib/python3.6/site-packages/urlwatch/storage.py", line 291, in is_shell_job
    for filter_kind, subfilter in FilterBase.normalize_filter_list(job.filter):
  File "/usr/local/lib/python3.6/site-packages/urlwatch/filters.py", line 95, in normalize_filter_list
    raise ValueError('Unknown filter kind: {} (subfilter {})'.format(filter_kind, subfilter))
ValueError: Unknown filter kind: tosentences (subfilter {})
```

**Comment by thp** [comment]
Interesting, can you share a minimal set of files for which this happens? (Also, maybe create a new issue, as this seems unrelated to this issue here.)

**Comment by cjohnsonuk** [comment]
I'll log a new call. What files would help diagnose this?
