### ISSUE TITLE
Warning when content is empty

### ISSUE THREAD

**Issue by kbabioch** [thp/urlwatch#245]
Due to a misconfiguration of my filters, the actual content for some jobs was empty. I haven't realized this for a while, so I've missed some change(s). I think it is safe to assume that there is a misconfiguration in case of empty content, so there should be a warning.

In case someone wants to actually monitor empty pages, there might be some additional attribute and/or filter to disable this warning and to let urlwatch know that you expect empty content for a particular job. It should **not** be the default, though.

**Comment by thp** [comment]
There is a `--test-filter` option that can be used to test the filters.

**Comment by mentalstring** [comment]
I agree with @kbabioch that it would be useful to have an option (perhaps per job?) to be warned when result of the job is empty. The `--test-filter` requires testing it manually on the command line, but doesn't help when an existing working job stops being able to capture something (eg: an `element-by-id` that no longer exists on the page).

**Comment by thp** [comment]
It might be a per-job option (feel free to create a pull request). In some cases there might also be a situation where an empty filter output is expected (watching for some element to appear on a webpage, for example).
