### ISSUE TITLE
Add support for watching GitHub repositories

### ISSUE THREAD

**Issue by kbabioch** [thp/urlwatch#246]
Not sure if it makes sense to add this into this project itself, or whether it should live as some kind of third-party addon somewhere else, but I'm using this tool to monitor several GitHub repositories for new releases/tags. There is an official [API](https://developer.github.com/v3/?), so this is pretty easy.

The prototype looks something like this:

    class GitHubJob(jobs.Job):
        """Retrieves information about releases and tags from a GitHub repository using the GitHub REST API v3"""

        __API__ = 'https://api.github.com'

        __kind__ = 'github'
        __required__ = ('repo',)

        def get_location(self):
            return self.repo

        def retrieve(self, job_state):
            releases = requests.get('{}/repos/{}/releases'.format(self.__API__, self.repo)).json()
            tags = requests.get('{}/repos/{}/tags'.format(self.__API__, self.repo)).json()
            return releases + tags

An entry in the configuration looks something like this:

    ---
    kind: github
    repo: thp/urlwatch
    ---

This could be improved, though. For instance it does not use authentication, so there is a rate limit (currently 60 requests per hour). It would be easy to add it to the request, although it probably also needs some changes to the configuration, since you don't want to specify the credentials for each entry, but only once globally.

Furthermore it might be interesting to also monitor for new commits using the [repos/commits](https://developer.github.com/v3/repos/commits/) endpoint.

Also a configuration would be nice, so you could specify for each entry whether you want to monitor commits, tags and/or releases.

I'm happy to provide pull requests, just let me know if this is something of interest to this project and how you want the configuration, etc. to look like.

**Comment by thp** [comment]
Yeah, I think something like that could be added if you make a pull request. Maybe even add an option to add a Github API Key to the config (which would then be used for all Github requests), since some of the Github API calls are rate-limited, in which case the API Key would help to not get an error.

**Comment by kbabioch** [comment]
Ok, I will work on that and also implement a global configuration key for the token. However, I'm still not sure how to best tackle the filter issue. I think it should be configurable what aspects of a repository should be monitored (e.g. tags, releases and commits).

To my understanding a filter is not really the right tool, since filters only act after the retrieve() method from the job was executed. However I want to only ask for attributes that the user wants.

Do you have any suggestion what to do about this? I was thinking about another attribute, e.g. something like `monitor`, which can take any combination of `commits`, `tags`, `releases` as value (the default might be `tags,releases`) e.g.:

    kind: github
    repo: tph/urlwatch
    monitor: tags,releases

What do you think about this? Any suggestion about the naming of this attribute? I don't quite like `monitor` but cannot think about anything better right now :-).

**Comment by kbabioch** [comment]
For the time being I've created a [gist](https://gist.github.com/kbabioch/94751f2c7b5005e2aa4c36aca1889dc0). It is only configurable by directly editing it, but it might be good enough for most of us. Will work on a more generic and configurable approach and submit it as a pull request, though.

**Comment by kbabioch** [comment]
I'm currently working on this. You can track my progress [here](https://github.com/kbabioch/urlwatch/tree/feat/github). For now it is the prototype mentioned beforehand plus ETag support for conserving bandwidth. Still looking into ways to properly filter for releases/commits/tags. Input would be appreciated.

**Comment by thp** [comment]
There is now a "WATCHING GITHUB RELEASES" section in the `README.md`:

```yaml
url: "https://github.com/thp/urlwatch/releases/latest"
filter:
  - xpath: '(//div[contains(@class,"release-timeline-tags")]//h4)[1]/a'
  - html2text: re
```
