### ISSUE TITLE
Add support for HTTP ETag

### ISSUE THREAD

**Issue by kbabioch** [thp/urlwatch#248]
Currently there is an `ignored_cached` option to deal with servers that return different content unexpectedly. However there seems to be no support for the ETag. urlwatch should support it, since most modern webservers and public APIs offer this functionality.

This would be mainly used for the url watching functionality (`UrlJob`), but could also be useful for features like proposed in #246. After having played around with this for a while, I'm convinced that this can be a huge bandwith and performance saver.

I'm happy to work on this, although I need some guidance. To my understanding of the code and database structure this would require a change to the database, e.g. an etag column, which would contain the etag of the last request and could be send along with any new request.

**Comment by thp** [comment]
This is now merged.
