### ISSUE TITLE
Add support for posting to configured Slack channel

### ISSUE THREAD

**Issue by shan23** [thp/urlwatch#251]
Hi,

I was wondering if you could add slack integration, so that a change can be posted to a particular slack's specified channel? The implementation should be very similar to the Telegram Reporter IMO - let me know if I'm missing something.

I understand you may be extremely busy/reluctant to do this on the main project - please let me know if thats the case, and I'll start working on a PR for it. Any pointers you may have regarding the ideal implementation would greatly simplify the task for me then.

**Comment by thp** [comment]
Yes, feel free to create a pull request. This seems to be the go-to library for Slack + Python: https://slackapi.github.io/python-slackclient/

**Comment by huxiba** [comment]
PR #309 created for this

**Comment by Behner** [comment]
@thp @huxiba Would you expect the Slack integration to be working at this time?

**Comment by Behner** [comment]
> @thp @huxiba Would you expect the Slack integration to be working at this time?

Sorry, I see this is not in the tagged version of 2.15, which is what I am using.

**Comment by thp** [comment]
Merged #309 and available since urlwatch 2.16.
