### ISSUE TITLE
running urlwatch fails with error "ValueError: not enough values to unpack (expected 3, got 2)"

### ISSUE THREAD

**Issue by urishab** [thp/urlwatch#267]
running on Windows, python 3.6
installed all dependencies and also urlwatch via pip install

Getting the following message:

    Migrating cache: C:\Users\Uri\AppData\Local\urlwatch\urlwatch\cache -> C:\Users\Uri\AppData\Local\urlwatch\urlwatch\Cache\cache.db

Error is from storage.py where calling self.load on the database returns just (data,timestamp) and not the additional parameter "tries"

Output:
Traceback (most recent call last):
  File "urlwatch", line 107, in <module>
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "C:\Python36\lib\site-packages\urlwatch\main.py", line 66, in __init__
    self.urlwatch_config.migrate_cache(self)
  File "C:\Python36\lib\site-packages\urlwatch\migration.py", line 80, in migrate_cache
    urlwatcher.cache_storage.restore(old_cache_storage.backup())
  File "C:\Python36\lib\site-packages\urlwatch\storage.py", line 379, in restore
    for guid, data, timestamp, tries in entries:
  File "C:\Python36\lib\site-packages\urlwatch\storage.py", line 375, in backup
    data, timestamp, tries = self.load(None, guid)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by m1k3241** [comment]
Have the same issue is there a advice ?

**Comment by cfbao** [comment]
This issue is related to #223. See [my comment there](https://github.com/thp/urlwatch/issues/223#issuecomment-431543111).

Migration is not needed for new installs of urlwatch 2, but urlwatch treats filenames case-sensitively, whereas Windows treats filenames case-INsensitively, resulting in superfluous migration and errors.

**Comment by thp** [comment]
There's now a fix for #223 in git (master branch, not yet in a release), maybe @urishab can test this fix also?
