### ISSUE TITLE
Add support for a HTML filter using CSS selectors

### ISSUE THREAD

**Issue by thp** [thp/urlwatch#273]
Split off from #226, it was suggested that there should be a filter option for using CSS selectors to pick something from the document.

We probably can't use anything from the standard Python library, but something like this should work:
https://cssselect.readthedocs.io/en/latest/

Note that with Requests-HTML (which we already have as an optional dependency for the "browser" job) it would also work: https://html.python-requests.org

**Comment by thp** [comment]
This can likely be implemented on top of #274 using the `cssselect` module (which itself outputs XPath expressions).

**Comment by maximbaz** [comment]
@thp would you please consider cutting a new release soon? So keen on starting to use css filters!
