### ISSUE TITLE
always prompt for password by python keyring

### ISSUE THREAD

**Issue by fabienmorin** [thp/urlwatch#277]
I updated to the last version and now each time I launch urlwatch, a password is prompt.
If I put the password it works, but as it is used in a crontab, how to deal without password ?

**Comment by cvhight** [comment]
I believe I'm having this same issue.  Running from the command line, I'm prompted for a keyring password, but running from cron it doesn't appear to run.  Running on a rpi, latest release.  is there a way to either use a non-protected keyring or to somehow address the password requirement when running via cron?

**Comment by m2ch35** [comment]
Hi,
I'm having the same issue too.

I tried two things, not at the same time:
1- in mailer.py, added kr.keyring_key = "your_password"

**Comment by m2ch35** [comment]
Hi,
I'm having the same issue too.

I tried two things, not at the same time:

1- in mailer.py, added kr.keyring_key = "your_password"

2- if self.auth and keyring is not None:
            passwd = keyring.get_password(self.smtp_server, self.smtp_user)
I replaced with passwd = your_password

But doesn't work either

Would it be a good idea to set 
passwd=your_password 
after those 2 lines :

class SMTPMailer(Mailer):
    def __init__(self, smtp_user, smtp_server, smtp_port, tls, auth):

any help would be appreciated :-)

**Comment by thp** [comment]
@fabienmorin @cvhight @m2ch35 I've created #431, can you give it a try and tell me if this works for you?

**Comment by m2ch35** [comment]
Hi,

Thanks for #431 !
...however I've got an error now that says :

Traceback (most recent call last):
  File "urlwatch", line 54, in <module>
    from urlwatch.command import UrlwatchCommand
  File "/home/pi/scripts/urlwatch/lib/urlwatch/command.py", line 39, in <module>
    from .handler import JobState
  File "/home/pi/scripts/urlwatch/lib/urlwatch/handler.py", line 38, in <module>
    from .reporters import ReporterBase
  File "/home/pi/scripts/urlwatch/lib/urlwatch/reporters.py", line 47, in <module>
    from .mailer import SMTPMailer
  File "/home/pi/scripts/urlwatch/lib/urlwatch/mailer.py", line 83
    def send(self, msg):
                       ^
IndentationError: unindent does not match any outer indentation level

**Comment by thp** [comment]
Are you sure you don't have any local modifications? The version in Git shouldn't have this issue.

**Comment by m2ch35** [comment]
Hi,
Sorry for the late reply !
I did a proper git clone and it fixed my issue so yes I guess I messed up some files.
Thanks for your help !
