### ISSUE TITLE
Visual comparison with external renderer

### ISSUE THREAD

**Issue by nspo** [thp/urlwatch#285]
The proposed functionality would be similar to https://visualping.io, which compares websites by comparing the cropped screenshots of the rendered page. Of course this would need an external renderer ([e.g. selenium + driver](https://medium.com/@ronnyml/website-screenshot-generator-with-python-593d6ddb56cb)). A stored and a freshly rendered image could then be compared to detect changes.

Would this be at all acceptable to be integrated into urlwatch? I'm open to writing code myself, but would like to know in advance if it has no chance at all to be integrated. Though users would not need to install the additional packages and have a slower urlwatch if they do not want to use the new feature.

I'm currently working on a small Qt application to load and select the area of interest in the web page. My application could create a urlwatch command like

`urlwatch --add url=http://example.org,name=Example,filter=visual:x100-y100-w80-h60`
(or something cleaner)

**Comment by nspo** [comment]
I just found out that this can actually be done with a simple shell filter and using wkhtmltoimage/wkhtmltopdf. Example:

`command: wkhtmltoimage google.de - 2>&1|md5sum
kind: shell
name: foo
`

The call to wkhtmltoimage would need to be a little more complicated, but this should work. Also, of course this is only a comparison whether the former and current screenshots are 100% the same. The latter could be changed my using something like [libpuzzle](https://www.pureftpd.org/project/libpuzzle) and storing an image to compare with.

**Comment by nspo** [comment]
[pyvisualcompare](https://github.com/nspo/pyvisualcompare) can help set up urlwatch to monitor visual changes.

**Comment by thp** [comment]
Getting something like this integrated would actually be nice, instead of just having a hash of the image data, maybe it can be done via HTML mails and in image attachment, so that the actual change is shown visually (a HTML part and an image part in the MIME message). Also, some reporters like e.g. Telegram could actually support attaching an image to the message.

Anybody want to work on this?

**Comment by cfbao** [comment]
This can probably be more easily implemented in the new (yet to be merged) browser job using pyppeteer's screenshot methods [[1]](https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.page.Page.screenshot)[[2]](https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.element_handle.ElementHandle.screenshot).

**Comment by thp** [comment]
I just read the issue description again, and noticed that `pyvisualcompare` is actually a thing and a frontend/config generator for `urlwatch`, so I decided to document it in the "advanced usage" documentation, so other people can more easily find it.

If anybody feels motivated to use `pyppeteer` for this and/or port (parts of) `pyvisualcompare` into `urlwatch`, please do so. In any case, a GUI to select the area to watch like `pyvisualcompare` has is definitely something useful, and pointing interested users to `pyvisualcompare` sounds like a doable solution for now :+1:
