### ISSUE TITLE
cannot use comma in xpath filters

### ISSUE THREAD

**Issue by cfbao** [thp/urlwatch#287]
Commas are recognized as separators between filters, and cannot be used in XPath expressions such as 
`//div[contains(., 'Download')]`
This severely limits the power of XPath.

There's an escape sequence `\054` for grep, but it doesn't seem to work for XPath expression.

**Comment by cfbao** [comment]
I've figured out how to use comma in filters by reading the code and YAML specs. Filters need to be written as a YAML sequence:
```
filter:
    - xpath: //div[contains(., 'Download')]
```

This should be noted in documentations so it's easier to use.

**Comment by thp** [comment]
There are now two examples of how to use xpath filters with the dict-based specification at the end of the `README.md`.
