### ISSUE TITLE
'browser' job does not render with javascript

### ISSUE THREAD

**Issue by cfbao** [thp/urlwatch#293]
https://github.com/thp/urlwatch/blob/2d4e513d38d279cbbc09cf367aef78bafa39b0fc/lib/urlwatch/jobs.py#L288-L292
`response.html.render()` is needed before returning `response.html.html`

**Comment by cfbao** [comment]
A fix is complicated by kennethreitz/requests-html#155

**Comment by cfbao** [comment]
Currently, 'browser' jobs are no different from 'url' jobs, because requests-html simply uses requests to retrieve web pages, and retrieved pages are not rendered. Chromium browsers are never launched.

However, requests-html can only launch a Chromium browser instance in the main thread ([on Windows at least](https://docs.python.org/3/library/asyncio-eventloops.html#windows)), and `request_html.HTML.render` must have its own event loop (one that isn't already running). Basically, we must render web pages sequentially in the main thread.

I have a working local branch that does just that. It picks out all non-browser jobs, and put them in the thread pool, while running browser jobs sequentially in the main thread. If @thp is fine with this idea, I can open a pull request.

---

In the (near?) future, requests-html will have async API  (kennethreitz/requests-html#77, kennethreitz/requests-html#146), and we can probably run browser jobs asynchronously.

Either way, browser jobs need to be moved out of the thread pool to render pages with javascript properly.

**Comment by thp** [comment]
Yes, feel free to create a pull request.

**Comment by gbonett** [comment]
Hi, this feature is still broken - correct? As far as I can tell, "browser" and "url" jobs give the same result using version 2.17.
