### ISSUE TITLE
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bones78** [thp/urlwatch#302]
Hi all,
I have tried to updates urlwatch using pip3 install --upgrade urlwatch on a rasperry pi 3b+.
Now, if i start urlwatch I receive the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 54, in <module>
    from urlwatch.command import UrlwatchCommand
  File "/home/pi/.local/lib/python3.5/site-packages/urlwatch/command.py", line 38, in <module>
    from .filters import FilterBase
  File "/home/pi/.local/lib/python3.5/site-packages/urlwatch/filters.py", line 42, in <module>
    from lxml import etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
`
How can I fix this?

**Comment by thp** [comment]
According to the [Debian package index search for libxslt.so.1](https://packages.debian.org/search?searchon=contents&keywords=libxslt.so.1&mode=exactfilename&suite=stable&arch=any) (which is "close enough" to what Raspbian ships with), this should fix it:

    sudo apt install libxslt1.1

How this can be done for similar issues:

1. Go to https://packages.debian.org/
2. Scroll down to "Search the contents of packages"
3. Enter the file name you're looking for
4. Select "packages that contain files named like this"
5. Search (possibly changing the "Distribution")

Note that this is not always 1:1 with what's in Raspbian on the Raspberry Pi, but usually it gives you a hint where to look for next. If you want to do it without the website, there's [`apt-file`](https://wiki.debian.org/apt-file), although I'm not sure if it works in Raspbian.

**Comment by bones78** [comment]
thanks a lot for the help and the explanation. Now it runs without problems. Great software and support!
