### ISSUE TITLE
Support web pages in non-Unicode & non-Western-European encoding

### ISSUE THREAD

**Issue by cfbao** [thp/urlwatch#306]
Currently `UrlJob` cannot handle non-Unicode & non-latin1 encoding if they're not declared in HTTP headers. Such websites are not so rare, especially CJK sites.
Example: http://music.yule.sohu.com

A quick & lazy solution would be to use `requests.Response.apparent_encoding` (which uses [chardet](https://github.com/chardet/chardet)) if encoding is not declared in HTTP headers.

A more careful solution would also need to detect the `charset` declaration in the web page. A parsing package like [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/) (which is already an optional dependency for html2text filter) is probably needed for this.

A nice discussion can be found here: buriy/python-readability#42

**Comment by thp** [comment]
Also, I guess what browsers do is interpret what they can as latin-1 and if there's a `<meta http-equiv="Content-type" content="text/html; charset=...">` in there, it takes this as encoding.

Maybe something like this? https://stackoverflow.com/a/36454703/1047040

**Comment by thp** [comment]
#312 is merged.
