### ISSUE TITLE
URLs config file not checked after editing

### ISSUE THREAD

**Issue by ftruzzi** [thp/urlwatch#316]
While editing the jobs file with `--edit`, the newly edited copy does not get parsed/checked and an incorrect file may be saved.

I believe this is because the `parse` [method](https://github.com/thp/urlwatch/blob/6079cbdb74524af9cf04ba9c6298c9e753a92f4c/lib/urlwatch/storage.py#L254) that implements the parse checking is in `BaseTxtFileStorage`, not a parent class of `UrlsYaml` (whose own `parse` method is called when editing the file)

**Comment by cfbao** [comment]
It is `UrlsYaml.parse` that's called. Problem is `yaml.load_all` is lazy. It only returns a generator and doesn't evaluate.

For a proper check, perhaps do what `UrlsYaml.load` does.
