### ISSUE TITLE
Database Cleanup?

### ISSUE THREAD

**Issue by nille02** [thp/urlwatch#319]
Hello, is there a automated way to cleanup the database? I experiment some time now with it and the database was 11MB big but only one URL in the config. 

To delete everything what is not in the urls-config is not a good way. For example if i use more that on url file (what i'm planning to group my monitored websites (now over 1000) ) 

Maybe to check for urls and delete everything without a url would a possibility if we create for each url-config his own cache database. 
e.g. urls.yaml.cache.db and urls2.yaml.cache.db

**Comment by cfbao** [comment]
You can use separate databases with the `--cache` command line option.

**Comment by nille02** [comment]
Thank you for the answer. 
That leave just the question for a cleanup method.

**Comment by cfbao** [comment]
Have you tried `--gc-cache`? If you have a separate database for each urls file, you should be able to clean the database without losing data.

**Comment by nille02** [comment]
Now i feel stupid. Thank you for you help, answers and time.
