### ISSUE TITLE
urlwatch fails with future.exception

### ISSUE THREAD

**Issue by protist** [thp/urlwatch#324]
Recently, urlwatch has been failing for me with the following
```
$ urlwatch
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 260, in <module>
    raise exception
IndexError: list index out of range
```
I checked this line (and the few before) in the code:
```
            exception = future.exception()
            if exception is not None:
                raise exception
```
but I don't totally understand what's going on.

urlwatch started failing at Nov 8 08:00. I had updated `urls.txt` just before then (Nov 8 07:58), commenting out a single url. I attempted to revert this file, but it still failed as above. I'm not familiar with the internals of urlwatch, so I reverted the entire `~/.urlwatch` directory, in case timestamps were important, but this still failed.

FWIW I also checked my system update logs, but nothing had updated around this time.

I'm using the current Debian package, which is way back at urlwatch 1.15. I understand if you don't want to spend too much time troubleshooting this extremely old version, so I'm happy to upgrade manually if necessary.

## EDIT
I have urlwatch on a crontab every hour. Oddly enough, it worked once at 2 am this morning, but failed every other scheduled and manually-triggered time.

**Comment by thp** [comment]
Yes, would be great if you could upgrade to the latest version of `urlwatch` :)

**Comment by protist** [comment]
FWIW I checked the modification date on `~/.urlwatch/lib/hooks.py`, and it was four days before the failure in the original post, so I don't think it was to blame. I also tried reverting to an even earlier version and running the original debian-packaged urlwatch, and I still get the errors as the original post.

**Comment by cfbao** [comment]
The problem is almost certainly in your hooks though. This is the only place where this specific error message could originate from.

It's possible that the web page you're monitoring changed in a way that triggered a different part of the code in your hooks. This can explain why you didn't see this error previously.

**Comment by cfbao** [comment]
Oh yeah, that line of code is problematic.
If `re.findall` can't find at least one result, then calling `[0]` will result in an index error, which is exactly what you saw. You should check the length of the list before indexing it.

**Comment by protist** [comment]
> Oh yeah, that line of code is problematic.

Ahhhh yes, thank you for that. This makes sense now. Sorry for the noise. Thanks again for all your help @cfbao and @thp.
