### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by brbsix** [thp/urlwatch#33]
What are your thoughts on having the hard dependencies (minidb and PyYAML) installed upon installation? This could be especially helpful for people installing or upgrading directly through the Python Package Index as I was. Personally I like to keep my pip dependency tree accurate so that at some later date I'm able to easily check what unused packages I'm able to uninstall without causing problems.

I'm not familiar with how to do this with distutils (or whether it is even possible) so I used setuptools to do the following:

    diff --git a/setup.py b/setup.py
    index 7d9707c..ee1a825 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -3,7 +3,7 @@
     # Minimalistic, automatic setup.py file for Python modules
     # Copyright (c) 2008-2016 Thomas Perl <thp.io/about>
     
    -from distutils.core import setup
    +from setuptools import setup
     
     import os
     import re
    @@ -29,5 +29,6 @@ m['scripts'] = [PACKAGE_NAME]
     m['package_dir'] = {'': 'lib'}
     m['packages'] = ['.'.join(dirname.split(os.sep)[1:]) for dirname, _, files in os.walk('lib') if '__init__.py' in files]
     m['data_files'] = [(dirname, [os.path.join(dirname, fn) for fn in files]) for dirname, _, files in os.walk('share')]
    +m['install_requires'] = ['minidb', 'PyYAML']
     
     setup(**m)

**Comment by thp** [comment]
Very good idea, thanks. Will be part of the next release.
