### ISSUE TITLE
Python 3.3 not tested in CI

### ISSUE THREAD

**Issue by cfbao** [thp/urlwatch#338]
This is perhaps more of a question than an issue - why is Python 3.3 removed from Travis CI (in 1c9e644b06aee69a0fcb82f28a49c2c6c41b49d4)?

I'm not at all against dropping support for python 3.3 entirely (actually I'm in favor of dropping it). But if python 3.3 is to be supported, having it in CI is quite meaningful, because it (being quite old) is the most likely python version to give surprising errors during development.

**Comment by thp** [comment]
New minimum requirement is Python 3.5 since urlwatch 2.18.
