### ISSUE TITLE
Timeout connection 

### ISSUE THREAD

**Issue by vesidorov** [thp/urlwatch#340]
Might be worth using timeout? 
timeout_from_config=(3.05, 27)

response = requests.request(url=self.url,
                                    data=self.data,
                                    headers=headers,
                                    method=self.method,
                                    verify=(not self.ssl_no_verify),
                                    cookies=self.cookies,
                                    proxies=proxies,
                                    timeout=timeout_from_config)

If you specify a single value for the timeout, like this:

r = requests.get('https://github.com', timeout=5)
The timeout value will be applied to both the connect and the read timeouts. Specify a tuple if you would like to set the values separately:

r = requests.get('https://github.com', timeout=(3.05, 27))
If the remote server is very slow, you can tell Requests to wait forever for a response, by passing None as a timeout value and then retrieving a cup of coffee.

r = requests.get('https://github.com', timeout=None)

Many Thanks!

**Comment by cfbao** [comment]
Good point. I'm facing the same issue where an unreliable site can hang the process forever.
I'll probably implement this soon.

**Comment by vesidorov** [comment]
Thanks

**Comment by snowman** [comment]
How to change `timeout` globally? The default value `60` is waiting too much, for me `8` or `12` is the expected value.

**Comment by thp** [comment]
https://urlwatch.readthedocs.io/en/latest/configuration.html#job-defaults

```
job_defaults:
  all:
    timeout: 12
```
