### ISSUE TITLE
Excluding elements by class, id, style or tag

### ISSUE THREAD

**Issue by Markus00000** [thp/urlwatch#350]
I would like to exclude elements by class, id, style or tag because headers, sidebars and footers often contain dynamic content like suggested articles. For example:

    url: "https://example.com/"
    filter: !element-by-id:sidebar,html2text

(This was proposed in #329 but subsequently closed.)

**Comment by cfbao** [comment]
This is implemented as part of the XPath and the CSS selector filters in #333. Just waiting to be approved and merged.

**Comment by thp** [comment]
#333 is now merged, released in urlwatch 2.17, released on 2019-04-12.
