### ISSUE TITLE
Make MAX_LENGTH in SlackReporter configurable

### ISSUE THREAD

**Issue by nscaife** [thp/urlwatch#353]
Some Slack-compatible webhooks (i.e., [Discord](https://discordapp.com/developers/docs/resources/webhook#execute-webhook-jsonform-params)) have different maximum message lengths.  Discord has a maximum message length of 2,000 characters for webhooks.

I verified that Discord rejects >2,000 character messages from urlwatch and that manually adjusting `MAX_LENGTH = 2000` in SlackReporter corrects the issue.  Can this be made into a configurable value for this reporter?

**Comment by thp** [comment]
Please create a pull request with the proposed change.
