### ISSUE TITLE
How URLWatch can be fed by a SSL certification?

### ISSUE THREAD

**Issue by Hitaro** [thp/urlwatch#356]
The site is using a SSL certification for itself that is not general, Even in browsers, it should be added as an exception to let you get access to the site. How a cert file can be read by `urlwatch`?

`sample.cert`:

    -----BEGIN CERTIFICATE-----
    DKkjhnUkjljN098KvgB...

    -----END CERTIFICATE-----

---
Generally there's two Situations:
 
- if the machine uses a self signed certificate, or
- if we are on a network with a proxy that re-encrypts all https connections

**Comment by thp** [comment]
So apparently it's possible with `requests` (the library that we use for HTTP requests):
http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

Would this be per job (URL) or would this be a global setting?

**Comment by thp** [comment]
As a temporary workaround, you can use the per-job option `ssl_no_verify` (but of course this then disables verification, so it might not be what you want/need).
