### ISSUE TITLE
Disable empty lines in messages

### ISSUE THREAD

**Issue by spvkgn** [thp/urlwatch#357]
With `line_length: 0` odd empty lines are shows in messages. It would be useful if there is an option like `line_length: -1` for completely disable it.

![50](https://user-images.githubusercontent.com/4147135/52031393-13173980-253e-11e9-8908-fb8a9a19322f.jpg)

**Comment by thp** [comment]
Good point, I think we should just remove the extra spacing in case of `line_length` = 0. See #358.
