### ISSUE TITLE
Unable to send mail to multiple recipients

### ISSUE THREAD

**Issue by nittolese** [thp/urlwatch#363]
Hi,
I have problems with multiple recipients when sending e-mails.
I've read https://github.com/thp/urlwatch/issues/216 but it seems it doesn't work for me.

`to: 'email1@domain.com,email2@domain.com'`

The curious fact is that the mail is delivered only to the first address, but in my inbox I can see the other address I have sent mail to.

Any help with this?
Thank you!

**Comment by isnotnull** [comment]
I’m facing this issue too.

**Comment by gersilex** [comment]
Hey @scottmac ! As you implemented #443 can you maybe help us out here? I can also reproduce this. The Mail headers look correct. Comma-seperated addresses in the `To: ` section.

**Comment by scottmac** [comment]
@gersilex you need to be on 2.18 which just came out.
