### ISSUE TITLE
Query: output to MQTT? 

### ISSUE THREAD

**Issue by lancelon** [thp/urlwatch#364]
I'm trying to figure out how I could use urlwatch in an automation. It seems designed (quite logically!) to notify HUMANS of a website having changed. I'd like to use it to notify youtube-dl running on another machine to start downloading a podcast. Am I barking up the wrong tree? :-)

**Comment by cfbao** [comment]
This seems similar to #330.
You can write a custom reporter to trigger whatever action you want.

**Comment by thp** [comment]
Using `diff_filter` and `shellpipe` (not yet in a release, just in Git master) you can trigger to run an external tool when urlwatch detects changes:

https://urlwatch.readthedocs.io/en/latest/advanced.html#pass-diff-output-to-a-custom-script
