### ISSUE TITLE
filter: element-by-id

### ISSUE THREAD

**Issue by lancelon** [thp/urlwatch#365]
Filter by element ID doesn't seem to work - seems to only work with very select div class and especially not if there are any spaces or hyphens?

Also (wasn't sure whether to create separate issue...) I have two urls in my urls.yaml, one of them "works" (so long as I've found a compatible element) the other url doesn't, even though it's exactly the same format as the first. I get 

`Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 111, in <module>
    urlwatch_command.run()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/command.py", line 293, in run
    self.handle_actions()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/command.py", line 179, in handle_actions
    sys.exit(self.test_filter())
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/command.py", line 121, in test_filter
    job = job.with_defaults(self.urlwatcher.config_storage.config)
AttributeError: 'NoneType' object has no attribute 'with_defaults'
root@raspbx:~# urlwatch --test-filter 1`

**Comment by cfbao** [comment]
1. Do you have a minimal working example of the `element-by-id` error? It works fine in my tests.
Also, an HTML id attribute should not contain any space.

2. Yes, it's better to create a separate issue.
