### ISSUE TITLE
YAMLLoadWarning with PyYAML version 5.1

### ISSUE THREAD

**Issue by spleiner** [thp/urlwatch#366]
Updated PyYAML to latest version (5.1) and started receiving the following errors on each urlwatch-run:

[removedfullpath]/python3.5/site-packages/urlwatch/storage.py:291: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(fp)

[removedfullpath]/python3.5/site-packages/urlwatch/storage.py:321: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return [JobBase.unserialize(job) for job in yaml.load_all(fp) if job is not None]

**Versions:**
urlwatch==2.16
PyYAML==5.1

**Comment by MrR0bo7** [comment]
I am getting this warning too.

It looks like the fix for this issue is already merged into master: #367

So lets wait for the next release.

**Comment by thp** [comment]
Fix released in urlwatch 2.17, which has been released on 2019-04-12.
