### ISSUE TITLE
Can we add sleep?

### ISSUE THREAD

**Issue by cattlehound** [thp/urlwatch#370]
I've got a number of pages hosted on the same site, and I'm running up against "429 Client Error: Too Many Requests for url"

Can we add a delay via sleep. If so, where?

**Comment by thp** [comment]
How often do you run urlwatch? Or do you mean that in a single run, you are running into this issue?

**Comment by cfbao** [comment]
This seems similar to #331.

**Comment by thp** [comment]
Yes, duplicate of #331.
