### ISSUE TITLE
Pushover/chump ValueError with empty device string

### ISSUE THREAD

**Issue by nscaife** [thp/urlwatch#372]
Opened an issue at karanlyons/chump#20 for this problem.

The default Pushover device selection in `urlwatch.yaml` is `device=''`.  In chump versions <1.6.0 this would send to all devices, but now chump appears to expect `None` for delivering to all devices.  As a result, this empty string causes a ValueError as chump now verifies the device name.  Opening here as well since I'm not sure what the desired fix is.

**Comment by rtgoodwin** [comment]
I made a tiny patch to support this. If @thp doesn't prefer to merge, it's a simple edit to `reporters.py`, adding the second line:

```
device = self.config['device']
if device == 'All': device = None
```

**Comment by oxivanisher** [comment]
This is still an issue today. Please consider merge the patch.

**Comment by thp** [comment]
For the YAML configuration, you should be able to do:
```
report:         
    pushover:
        device: null
```

**Comment by thp** [comment]
Ended up doing it slightly differently from @rtgoodwin's change, since the magical string "All" isn't needed, but left their README change in there, slightly improving it to be in line with how it works now. Please check if that's correct and let me know if this needs more updating.

**Comment by oxivanisher** [comment]
Thanks, this works grat! <3

**Comment by jprokos** [comment]
The comments here are in a language I don't understand, excuse my ignorance. Running `urlwatch `in my terminal I am getting an error when using "null" for device to report to all devices. I have two devices in pushover—Safari and iPhone.

`ValueError: Bad device: must be in ('Safari', 'iphone'), was 'null'`

**Comment by jprokos** [comment]
> The comments here are in a language I don't understand, excuse my ignorance. Running `urlwatch `in my terminal I am getting an error when using "null" for device to report to all devices. I have two devices in pushover—Safari and iPhone.
> 
> `ValueError: Bad device: must be in ('Safari', 'iphone'), was 'null'`

Because I didn't remove the tick marks thinking those were supposed to remain. Silly but understandable mistake.
