### ISSUE TITLE
Only Change notification telegram

### ISSUE THREAD

**Issue by luluhoc** [thp/urlwatch#374]
Hello,

I've successfully installed urlwatch on my google cloud vps with telegram notification. 

I'm monitoring Avengers End Game Cinemas if the tickets I want are for sale.

Is it possible to disable all the HTML output that urlwatch sends to telegram(it's enormous amount of HTML and I didn't find the way to filter only desired releases), so I can only have the notification that there was some change on the website and I'll check if the desired release has come out manually?

Thanks

**Comment by thp** [comment]
In the config file, under `report / text / details` -> set this to `false`

**Comment by luluhoc** [comment]
Thank you
