### ISSUE TITLE
how to completely remove a job

### ISSUE THREAD

**Issue by foice** [thp/urlwatch#375]
I have used the --delete option, but I have noted that if I add it back urlwatch does not recognize it as new, somehow has kept memory of it! (I am trying to debug my sendmail notification, so this is standing in the way)

**Comment by cfbao** [comment]
The `--delete` option doesn't remove data saved in the cache database.
Currently you can only remove all cached history by manually editing the cache database.

This can (and probably should) be improved.

**Comment by foice** [comment]
So we are talking about
`rm .cache/urlwatch/cache.db`
correct?

**Comment by cfbao** [comment]
Yes.
If you want to delete the entire cache database, there's already a command for it: `--gc-cache`.

I thought you wanted to delete cache entries for one job without changing cache entries for other jobs.

**Comment by foice** [comment]
Thanks for your reply. At least for me the --gc-cache does not really reset
it, only deleting the file does.

**Comment by nille02** [comment]
@foice with a sqlite browser you can open the database and remove the entry by yourself. 

The guid in the database is the sha-1 hash from the in urls.yaml 

for example: 5545f2b73c613bb02228f42413767c5aecac6a8e is for "https://thp.io/2008/urlwatch/" from the urls.yaml.example

On Windows u use "DB Browser for SQLite" to edit the Database.
