### ISSUE TITLE
YAMLLoadWarning in urlwatch

### ISSUE THREAD

**Issue by bones78** [thp/urlwatch#377]
Hi all,
I am receiving the following text, when executing urlwatch: 
`/home/pi/.local/lib/python3.5/site-packages/urlwatch/storage.py:291: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(fp)
/home/pi/.local/lib/python3.5/site-packages/urlwatch/storage.py:321: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return [JobBase.unserialize(job) for job in yaml.load_all(fp) if job is not None]`
According to the linked site, I have to inform you about it so you are hopefully enabled to fix it.

**Comment by cfbao** [comment]
This is already fixed in the latest version 2.17.

**Comment by rrik** [comment]
Fresh install today, am getting the same error. 

`/usr/lib/python3/dist-packages/urlwatch/storage.py:333: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return [JobBase.unserialize(job) for job in yaml.load_all(fp) if job is not None]`
