### ISSUE TITLE
Attach the diff with the appropriate Content-Type

### ISSUE THREAD

**Issue by Chris00** [thp/urlwatch#384]
The text diff could be attached with a header such as
```
Content-Type: text/x-diff; charset="utf-8"
Content-Disposition: inline
```
so that mail clients understanding `text/x-diff` may display it with appropriate colors.

**Comment by cfbao** [comment]
`text/x-diff` isn't a standard mime type, and it seems that most email clients don't understand it and cannot even render it at all.

**Comment by Chris00** [comment]
So maybe, 1. diffs could be attached (using _Content-Disposition: inline_) and a configuration variable would allow to change `text/plain` into `text/x-diff`?

**Comment by tomaszn** [comment]
Just a note: GitHub supports `application/vnd.github.v3.diff` and `application/vnd.github.v3.patch`:
https://developer.github.com/v3/media/#commits-commit-comparison-and-pull-requests

**Comment by thp** [comment]
If you want to see it happen, propose the change in a pull request.
