### ISSUE TITLE
Shorter headings for text report details

### ISSUE THREAD

**Issue by lolilolicon** [thp/urlwatch#385]
With this `urls.yaml`:

    name: Firefox for Android
    command: "curl -s -I -o /dev/null -w '%{redirect_url}' 'https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi'"

`urlwatch` produces:

    ===========================================================================
    01. NEW: Firefox for Android
    ===========================================================================

    ---------------------------------------------------------------------------
    NEW: Firefox for Android (curl -s -I -o /dev/null -w '%{redirect_url}' 'https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi')
    ---------------------------------------------------------------------------

You'll agree with me that the second heading is much too long.

There're two aspects to consider. First, the part within the parentheses is
really long, because `jobs.ShellJob.get_location` returns the full `command`.
I think the URL alone is sufficient. We'd then get this:

    ---------------------------------------------------------------------------
    NEW: Firefox for Android (https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi)
    ---------------------------------------------------------------------------

Still too long. The second thing we can do is put the URL on its own line.
We now have this:

    ---------------------------------------------------------------------------
    NEW: Firefox for Android
    https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi
    ---------------------------------------------------------------------------

Much nicer, isn't it?

We don't have to stop there. Did you know about `ls --hyperlink`? If your
terminal supports it, you can right click on the file names and "open link"!
Find out more here: [Hyperlinks (a.k.a. HTML-like anchors) in terminal emulators](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda).

For our example, try this in your terminal:

    printf '\e]8;;https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi\e\\Firefox for Android\e]8;;\e\\\n'

So for the `stdout` report, when stdout is a terminal, the heading can be
shortened to this clickable text:

    ---------------------------------------------------------------------------
    NEW: Firefox for Android
    ---------------------------------------------------------------------------

**Comment by lolilolicon** [comment]
A much simpler solution: simply provide an option, which says that if `name` of a job is specified, the `command` or `url` or whatever will not be added to the heading.

**Comment by thp** [comment]
Closing this as feature request. There are some other requests for customizing text output (e.g. #456, #429) that maybe will be tackled in the future.

**Comment by thp** [comment]
Yeah, I guess best would be to supply that as a string that can be used with [`str.format()`](https://docs.python.org/3/library/stdtypes.html#str.format) and named fields to produce a string.

**Comment by E1k3** [comment]
While I agree, that a format string gives the most customizability, I don't know how to replicate the current behavior of not showing the location in some cases when the title for example would defined as `"{pretty_name} ({location})"`.

TextReporter: 
```py
pretty_name = job_state.job.pretty_name()
location = job_state.job.get_location()
if pretty_name != location:
    location = '%s ( %s )' % (pretty_name, location)
```

HtmlReporter:
```py
if job.location_is_url():
    title = '<a href="{location}">{pretty_name}</a>'
elif job.pretty_name() != job.get_location():
    title = '<span title="{location}">{pretty_name}</span>'
else:
    title = '{location}'
```

**Comment by thp** [comment]
> While I agree, that a format string gives the most customizability, I don't know how to replicate the current behavior of not showing the location in some cases when the title for example would be defined as `"{pretty_name} ({location})"`.
> 
> [TextReporter](https://github.com/thp/urlwatch/blob/d57ae4ea3d2a70562ffa532bfa3d3c94c276f2b2/lib/urlwatch/reporters.py#L298):
> 
> pretty_name = job_state.job.pretty_name()
> location = job_state.job.get_location()
> if pretty_name != location:
>     location = '%s ( %s )' % (pretty_name, location)
> [HtmlReporter](https://github.com/thp/urlwatch/blob/d57ae4ea3d2a70562ffa532bfa3d3c94c276f2b2/lib/urlwatch/reporters.py#L223):
> 
> if job.location_is_url():
>     title = '<a href="{location}">{pretty_name}</a>'
> elif job.pretty_name() != job.get_location():
>     title = '<span title="{location}">{pretty_name}</span>'
> else:
>     title = '{location}'
> Defining one title template for each occasion does not seem intuitive to me:
> 
> title: "{pretty_name} ({location})"
> locationless_title: "{pretty_name}"
>  pretty_name = job_state.job.pretty_name()
> location = job_state.job.get_location()
> title =  cfg["locationless_title"].format(pretty_name=pretty_name)
> if pretty_name != location:
>     title = cfg["title"].format(pretty_name=pretty_name, location=location)

You could have in the template:

```
old_title = ...  # generate like now, conditionally

{
   "default": old_title,
   "location": job_state.job.get_location(),
   "pretty": job_state.job.pretty_name(),
}
```

The default format string would be `{default}`, and have the same behavior as before. If you wanted to just have the pretty name, you could set the value to `{pretty}`.

Actually, now that I think of it, it might not be so useful to actually specify the format string, and just have a few choices. These could actutally be the ones listed above:

- `default`: Current behaviour
- `location`: Unconditionally use the location always
- `pretty`: Unconditionally use the pretty name always

**Comment by thp** [comment]
..which of course basically boils down to having an option to disable it, but not as a boolean, but rather an (extensible-in-the-future, and self-explanatory) enumeration with those 3 values.

**Comment by E1k3** [comment]
I added the 3 options in https://github.com/thp/urlwatch/pull/842. Would be great if you could have a short look and give some feedback.
