### ISSUE TITLE
URL in e-mail has a ')' appended to link

### ISSUE THREAD

**Issue by felmey** [thp/urlwatch#387]
I receive the e-mail when I run urlwatch but the link in the e-mail had a close parentheses appended to the end. When you click on the link it fails to load the proper page, but if you then just delete the ")" at the end of the URL it works.  

Hopefully I'm describing this adequately.  The open parentheses that is at the beginning of the URL in the e-mail is not included in the actual link.  It's just the close parentheses at the end that appears to be added on in error.

**Comment by cfbao** [comment]
This issue is with your email client rather than with urlwatch.
The default config sends pure text emails. The conversion to clickable hyperlink is done by your email client.

To have better built-in handling of hyperlinks from within urlwatch, set the `report/email/html` key to `true`.

**Comment by felmey** [comment]
That worked.  I was using K-9 mail on Android.  Running 'urlwatch --edit-config' and setting the report/email/html key to true as suggested by cfbao above resolved the problem I was having completely.  Thanks.
