### ISSUE TITLE
Add beautifulsoup4 as requirement in the Readme

### ISSUE THREAD

**Issue by ohaessler** [thp/urlwatch#388]
Thanks for this amazing tool. It really helps to stay on top of webpage updates.

I tried to install urlwatch2 on RHEL 8 and for me, it was complaining that beautifulsoup4 was missing. So I installed it with:

python3 -m pip install beautifulsoup4 --user

Would be good if beautifulsoup4 could be added to the "The dependencies can be installed with..." list.

Thanks
Oliver

**Comment by thp** [comment]
This is now documented here: https://urlwatch.readthedocs.io/en/latest/dependencies.html#optional-packages
