### ISSUE TITLE
How can we display results on html?

### ISSUE THREAD

**Issue by princebhatia09** [thp/urlwatch#392]
Like instead of command line, how can we display results on html comparing two html with red and yellow colors?

**Comment by cfbao** [comment]
Check the `CustomHtmlFileReporter` in [urls.yaml.example](https://github.com/thp/urlwatch/blob/master/share/urlwatch/examples/urls.yaml.example).

**Comment by princebhatia09** [comment]
How to use it? Any example?

**Comment by princebhatia09** [comment]
it does not highlight the difference in html.. just plain html

**Comment by cfbao** [comment]
It does have highlighting colours.
How were you using it?
