### ISSUE TITLE
I get error when I add some filters: "handler.py - string indices must be integers"

### ISSUE THREAD

**Issue by Hitaro** [thp/urlwatch#394]
`filter: css:<something_here>` works fine. But the format below produces errors:

    filter:
      - css:<something_here>
      - alarm [1]
      - html2text:
          method: pyhtml2text
          unicode_snob: true
          ignore_images: true
          ignore_links: true
          pad_tables: true
          body_width: 160
          skip_internal_links: true
          ignore_anchors: true

Errors:
`> .\python.exe .\Scripts\urlwatch`

    =========================
    01. ERROR: <NAME>
    =========================
    -------------------------------------------
    ERROR: <NAME>(http://ADDRESS)
    -------------------------------------------
    Traceback (most recent call last):
      File "C:\Python37\lib\site-packages\urlwatch\handler.py", line 90, in process
        filter_kind, subfilter = key, item[key]
    TypeError: string indices must be integers
    -------------------------------------------
    urlwatch 2.17, Copyright 2008-2019 Thomas Perl

[1] https://github.com/thp/urlwatch/issues/393#issuecomment-489212450

**Comment by nille02** [comment]
you don't need to enable the alarm. its a reporter and not a filter.

**Comment by Hitaro** [comment]
Ah, Ok. But without the alarm line, I still get same error!

**Comment by cfbao** [comment]
When specifying filters in the list format, each filter must be a YAML map.
A YAML map must have a space after the colon.

So your filter list should be
```yaml
filter:
    - css: <something_here>
    ...
```

**Comment by Hitaro** [comment]
Ah, such a little missing. Thanks a lot!
