### ISSUE TITLE
how to use grep -v ? (to negate search term)

### ISSUE THREAD

**Issue by foice** [thp/urlwatch#398]
I want to pass the `-v` option to invert the search criteria

I have tried `filter:grep:-v\040mystring` and grep:"-v identifier" but none works. They give empty result from the --filter option, while there should be.

 How one should be the correct way to use the -v option of grep?

**Comment by cfbao** [comment]
It's not supported.

The "grep" filter doesn't actually use the Unix utility grep. It's a call to the python regular expression function [re.search](https://docs.python.org/3/library/re.html#re.search).

**Comment by cfbao** [comment]
Use the inverse grep filter `grepi`

The "grep" and "grepi" filters don't actually use grep. They use calls to the python regular expression function [re.search](https://docs.python.org/3/library/re.html#re.search).

**Comment by foice** [comment]
it works! I navigated a bit into `filters.py` but did not get that was all python and no bash!
