### ISSUE TITLE
Prevent printing of information on the console screen

### ISSUE THREAD

**Issue by parsedarweb** [thp/urlwatch#399]
I don't need to see the changed part on screen. Is there any option to disable printing the result of "diff"?

**Comment by cfbao** [comment]
In your config `urlwatch.yaml`, disable details:
```yaml
report:
  text:
    details: false
```

**Comment by parsedarweb** [comment]
Thanks, but it still prints these:

```
===========================================================================
01. CHANGED: NAME
===========================================================================

--
urlwatch 2.17, Copyright 2008-2019 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 1 URLs in 1 seconds
```

**Comment by cfbao** [comment]
You asked for disabling printing results of "diff", so that's what I thought you wanted.

Do you want any report to be printed at all? You can also disable reporters completely:
```yaml
report:
  stdout:
    enabled: false
```
