### ISSUE TITLE
urlwatch --test-smtp option

### ISSUE THREAD

**Issue by jackwilsdon** [thp/urlwatch#400]
It'd be nice to have an option to test SMTP to ensure it's configured correctly (similarly to `--test-slack`).

**Comment by thp** [comment]
Pull requests gladly accepted.

**Comment by thp** [comment]
Merged in Git, not yet part of a release. The command is `--test-reporter email`, since it's now possible to test any configured/enabled reporter, not just Slack and E-Mail.
