### ISSUE TITLE
Feature request: string replace/substitute filter

### ISSUE THREAD

**Issue by n-st** [thp/urlwatch#401]
Just a quickly described feature request:

It would be useful to have a `replace` (or `substitute`) filter to replace strings (or, even better, regular expressions) in the page content.
My current use case was to split the page into lines on a certain string to get more useful line-wise diffs, but I can imagine other scenarios where this would be useful (cutting out unimportant parts from an otherwise interesting line, for example).

**Comment by killua-eu** [comment]
I'm interested as well

**Comment by nille02** [comment]
you can achieve this with a simple filter hook. 

A Basic filter would be look like this 

```python
class SimpleFilter(filters.FilterBase):
    __kind__ = 'simple-filter'
    def filter(self, data, subfilter=None):
        return data
``` 

subfilter is the data that you pass to the filter in your urls config. 

if you want to to it with regex, i guess we need 2 parameters for it. one to search and one for replacing.
i choose a dict for this. 

our urls config would be look like this 

```
url: "https://example.tld/latest"
kind: url
filter:
  - simple-filter:
        search: 'look-for'
        replace: 'replace-with'
name: 'Website'
```

the filter gets as subfilter now a dict with 2 keys, search and replace

so alter our filter a bit to

```python
import re
import urlwatch
from urlwatch import filters

class SimpleFilter(filters.FilterBase):
    __kind__ = 'simple-filter'
    def filter(self, data, subfilter=None):
        data = re.sub(subfilter.get('search'), subfilter.get('replace'), data)
        return data
``` 

Note: i didn't test anything of this and there should be some checks if the input is valid or you should be sure that it is.

**Comment by nille02** [comment]
did this help you both? or was it something else?

**Comment by n-st** [comment]
@nille02 Your filter code looks useful (haven't tested it yet), but I'm advocating for including it in urlwatch instead of manually adding it each time it's needed.

**Comment by thp** [comment]
This is possible in urlwatch 2.18 and newer via the `re.sub` filter.
