### ISSUE TITLE
You need to create /root/.config/urlwatch/urls.yaml in order to use urlwatch

### ISSUE THREAD

**Issue by birdbrainsolutions** [thp/urlwatch#405]
I installed urlwatch and can see the urls.yaml file in filezilla, however when I run urlwatch I get this message:

You need to create /root/.config/urlwatch/urls.yaml in order to use urlwatch.
    Use "urlwatch --edit" to open the file with your editor.

Please help, thank you!

**Comment by nille02** [comment]
you can specify the path to your urls.yaml with `--urls path/to/urls.yaml` or if you add a job the files get created automatically.
