### ISSUE TITLE
Some help for a noob please

### ISSUE THREAD

**Issue by darkufo** [thp/urlwatch#406]
If this is the wrong place please let me know and I'll post somewhere else.

I'm currently migrating my systems from Windows to Ubuntu. So far so good. With 1 exception.

I use a windows tool called Website Watcher that monitors web site changes via a gui and some nice UI friendly tools.

I've moved most of the URLs that I want to check over to urlwatch. However I would like a little help if possible.

1) In WSW I could specify an item of text on a particular page and WSW would ignore any changes BEFORE that text was found on the page. This is useful for ignoring dynamic menus etc.  I Could not find anything similar so far in urlwatch

2) Similar to the above WSW lets me specify an item of text and then any changes AFTER that text would be Excluded. Again useful for dynamic footers/dates/time/years at the end of pages etc

3) Sometimes the underlying CSS/HMTL changes on a page. Is there a way so that these changes do not get flagged as changed. I'm typically only interested visible readable text on the page. eg lots of Google based sites use generated class names/ids. These normally change but the text etc on the readable page stays the same. So far urlwatch is flagging these css/html changes.

Many thanks in advance or any help/links/examples

**Comment by thp** [comment]
Most of these can be done with filters. See here for how to configure filters:
https://urlwatch.readthedocs.io/en/latest/filters.html
