### ISSUE TITLE
Beautifulsoup and script tags

### ISSUE THREAD

**Issue by maugch** [thp/urlwatch#412]
It seems that BS doesn't strip away scripts which give the annoying problem of SSID or any other session identificator to be seen as a change of the page. 

A soultion seems to be posted here:
https://stackoverflow.com/questions/22799990/beatifulsoup4-get-text-still-has-javascript

for script in soup(["script", "style"]):
            script.decompose()

**Comment by thp** [comment]
You can use other filters before going with BS4 to strip away script tags, or do it in a variety of other ways.
