### ISSUE TITLE
Formatting email

### ISSUE THREAD

**Issue by krishna36** [thp/urlwatch#418]
Is it possible to format the email output ?

I am searching on a table content in a website and wanted to send email of there are any changes. I do not need to know what changes were done. I just wanted email saying some changes in website.
Right now using urlwatch I am getting the table contents in unformatted zigzag way. Is there a way to format the same or ignore the differences and just send the email URL which was changed ?

**Comment by cfbao** [comment]
In the config file `urlwatch.yaml`, set
```yaml
report:
  text:
    details: false
```

**Comment by thp** [comment]
Since #429 has more infos, closing this as duplicate.
