### ISSUE TITLE
Documentation could be improved

### ISSUE THREAD

**Issue by sunilw** [thp/urlwatch#425]
urlwatch is great. But it's a little mysterious.

Currently when I run 'urlwatch' manually from the terminal, the output indicates that it has parsed the urls.yaml that I've created.

The output also indicates that it has read and parsed another config file, that I'm having trouble locating: urlwatch is providing me with reporting on urls from http://example.com

Currently the user discovers urlwatch behaviours by experimenting with the examples and stumbling across behaviour that isn't documented. 

I propose the creation of additional documentation that fleshes out descriptions of urlwatch behaviour and how to modify it.

**Comment by jprokos** [comment]
Wouldn't a wiki page be helpful? A place to share knowledge. I have many questions that I don't care to burden the developer with because I know they are too simplistic.

**Comment by thp** [comment]
@jprokos Feel free to start writing documentation (using https://www.sphinx-doc.org/en/master/) and submit a PR.

**Comment by jprokos** [comment]
Thanks, but I am exactly the wrong person to do this.

I did add urlwatch as an alternative to many popular GUI apps that track website changes.

John

**Comment by thp** [comment]
There is now detailed documentation at https://urlwatch.readthedocs.io/en/latest/
