### ISSUE TITLE
--quiet flag

### ISSUE THREAD

**Issue by kyrias** [thp/urlwatch#43]
It would be useful if support for the `--quiet` flag was added back in. I sometimes run urlwatch manually, which is why I want reporting on stdout enabled, but I also run it in a cronjob, where I don't want it to write anything to stdout so that I won't get unnecessary emails from the cron daemon.

This could be worked around by keeping a duplicate config file, but I'd really rather not have one unnecessarily.

**Comment by thp** [comment]
Would a configuration option that outputs to stdout only when it is a terminal help?

**Comment by kyrias** [comment]
That should work, yeah.

**Comment by thp** [comment]
Come to think of it, you could just do `1>/dev/null` in the cron job, no? Closing for now...
