### ISSUE TITLE
re.sub filter causes "unknown filter kind" error

### ISSUE THREAD

**Issue by herrsimon** [thp/urlwatch#430]
Hello, 

for many websites that I monitor, html2text randomly adds whitespace at the beginning of some lines, causing urlwatch to report changes (actually, I think the webserver inserts these spaces randomly, but this is irrelevant). I wanted to overcome this problem using the following configuration ($vars replaced by actual strings):

```
url: $url
filter:
  - element-by-class: $class
  - html2text: re
  - re.sub:
      pattern: '^\s+(.+)'
      repl: '\1'
```

The error reported by urlwatch is
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urlwatch/handler.py", line 91, in process
    data = FilterBase.process(filter_kind, subfilter, self, data)
  File "/usr/lib/python3.8/site-packages/urlwatch/filters.py", line 88, in process
    raise ValueError('Unknown filter kind: %s:%s' % (filter_kind, subfilter))
ValueError: Unknown filter kind: re.sub:{'pattern': '^\\s+(.+)', 'repl': '\\1'}
```
Am I doing something wrong? All I want to achieve is to remove whitespace at the beginning of a line. 

Thanks in advance for any help!

PS: I'm running version 2.17 (Archlinux package).

**Comment by herrsimon** [comment]
Also, 

```
filter: element-by-class:$class,strip,html2text,strip
```

or 

```
filter: element-by-class:$class,html2text,strip
```

does not remove the whitespace.  I tried investigating via `urlwatch --test-job` and there are always a few lines with random whitespace at the beginning of the line. 
One of the pages where this happens is
```https://www.cambridge.org/core/browse-subjects/mathematics/listing?sort=canonical.date%3Adesc&aggs%5BproductTypes%5D%5Bfilters%5D=BOOK&aggs%5BproductDate%5D%5Bfilters%5D=Last+12+months&searchWithinIds=FA1467C44B5BD46BB8AA6E58C2252153```,

the full filter string is 

```
filter: element-by-class:product-listing-with-inputs-content,strip,html2text,strip
```

**Comment by securechicken** [comment]
As for your first issue regarding `Unknown filter kind: re.sub:`, it is probably because you do not use a version which actually includes this filter...
2.17 as available from pip or some OSes packages does NOT contain the filter yet, you have to clone urlwatch from GitHub.

**Comment by djstrong** [comment]
Why html2text randomly adds whitespace at the beginning of some lines?

**Comment by djstrong** [comment]
Probably `- re.sub: '(?m)^ +'` is the right filter to apply for each line separately.
