### ISSUE TITLE
Image Filter

### ISSUE THREAD

**Issue by lusseyarmet** [thp/urlwatch#437]
Hi, 

Is there any way to check if any extra images load compared to the previous version?
So say I load a website and there are 2 images, and then the next time there are 3, have that be detected? And limit the comparison to that? 
I noticed you can exclude images easily with html2text, but I'm trying to focus on them. 

Thanks!

**Comment by cfbao** [comment]
You can filter by HTML elements using any of `element-by-tag`, `css`, or `xpath` filters.
