### ISSUE TITLE
will urlwatch help me to notify the changes in the website

### ISSUE THREAD

**Issue by s1782662** [thp/urlwatch#440]
HI,

Will url watch help me to notify the changes in website. Suppose, if an article is added or if the pdf link is updated, then i want a notification saying "something has changed"

For example I have a website https://home.kpmg, I would like to be notified if any article is introduced in the website 

If so, can you help me how to do it. please

**Comment by thp** [comment]
Yes, that's the point of urlwatch. Note that by default, any linked files are not watched, so PDFs linked from the website are not checked for changes, only the website itself (but if the link is updated on the page, of course you will get an update).
