### ISSUE TITLE
Can't use method PURGE

### ISSUE THREAD

**Issue by anhhtbk** [thp/urlwatch#441]
When I use method PURGE, I received error `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url`

**Comment by cfbao** [comment]
Have you tried PURGE using another tool?
The web server can simply refuse any requests, and there's nothing urlwatch (or any other client side tool) can do.

**Comment by anhhtbk** [comment]
Thanks for your  répone. I will check again.
