### ISSUE TITLE
urlwatch: error: unrecognized arguments: --smtp-login

### ISSUE THREAD

**Issue by aaronmweiss** [thp/urlwatch#442]
Documentation states: 

> Now, for setting the password, it's not stored in the config file, but in your keychain. To store the password, run: urlwatch --smtp-login and enter your password.

However, when I run the following, I get an unrecognized argument 

```
aaron@maria_git:~$ urlwatch --smtp-login
usage: urlwatch [-h] [--version] [-v] [--urls FILE] [--config FILE]
                [--hooks FILE] [--cache FILE] [--list] [--add JOB]
                [--delete JOB] [--edit] [--edit-config] [--edit-hooks]
                [--features] [--gc-cache]
urlwatch: error: unrecognized arguments: --smtp-login
```

**Comment by thp** [comment]
Which version (output of `urlwatch --version`) are you running? The feature was added in urlwatch 2.9 in b96cd037. Chances are, you need to update your urlwatch installation (e.g. by uninstalling the old version and installing the latest one using `python3 -m pip install urlwatch` (add `--user` to install to your home directory).
