### ISSUE TITLE
Running url watch --test-filter returns nothing

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#448]
Some tests return information. Some do not. When they do not does that mean the filter found nothing and I need to rewrite it?

This mostly happens when using:

> element-by-id
> element-by-class

I am trying to monitor only new posts on this page:
https://www.teamunify.com/TeamFeed.jsp?team=ilslsc#/teamfeed

The issue is many objects on the page change every day so I can't monitor the entire page.

This is what I am using now. Testing this returns nothing.

> filter: element-by-class:ng-scope
> kind: url
> name: ISI TeemFeed
> url: https://www.teamunify.com/TeamFeed.jsp?team=ilslsc#/teamfeed

For filter I have tried:

> class:ng-scope
> id:timelineInstance
> class:Content
> class:Description
> class:Purport

**Comment by cfbao** [comment]
> When they do not does that mean the filter found nothing

Yes

> I am trying to monitor only new posts on this page:
> https://www.teamunify.com/TeamFeed.jsp?team=ilslsc#/teamfeed

I'm assuming you want to get the new feed updates. It seems like this page dynamically loads the feed's content. The static content returned by a get request does not contain the feed.

Oftentimes, you can track the dynamically loaded content to another URL, and monitor that instead.

**Comment by jprokos** [comment]
Thank you. Yes, I am looking to be notified of new feed updates.

There are individual links to each post that have an id...  I am not sure how to "track" the dynamically loaded content. Do you mean using a program like Wireshark?

An example of a URL to a specific post on this page. Not sure if it's useful since each post has a post ID.

`https://www.teamunify.com/postviewer.jsp?team=ilslsc&postId=58385`

**Comment by jprokos** [comment]
Question. Shouldn't this feature solve this issue:

```
kind: browser
name: "A Page With JavaScript"
navigate: http://example.org/
```


> I'm assuming you want to get the new feed updates. It seems like this page dynamically loads the feed's content. The static content returned by a get request does not contain the actual feed. That's why while your filter isn't matching anything.

**Comment by cfbao** [comment]
> I am not sure how to "track" the dynamically loaded content.

The "network" tab in developer tools (F12) in your browser should be sufficient.

> Question. Shouldn't this feature solve this issue:
>
> ```kind: browser
> name: "A Page With JavaScript"
> navigate: http://example.org/
> ```

This feature wasn't properly implemented. No browser is actually launched when using this. I have a pending PR #355 to make the "browser" job actually work, but there's issue there as well.

**Comment by jprokos** [comment]
Another example of trying multiple ways and getting nothing:
I am trying to track updated linked PDFs on this site.
https://www.usaswimming.org/Home/times/time-standards

It seems they are inside a jquery. There is a project on GitHub called[ jQuery watch](https://github.com/RickStrahl/jquery-watch). Could this be implemented inside of urlwatch?

**Comment by jprokos** [comment]
Can we use options with grep?
grep -i 
grep -e
html2text,grep:'Apple.*Releases\|Apple.*Seeds',strip

**Comment by jprokos** [comment]
will rss examples work with this page?
https://www.swimmingworldmagazine.com/news/feed/

Examples work on pages ending with rss but not feed.

```
url: 'https://www.swimmingworldmagazine.com/news/feed/'
filter:     
  -xpath:
    path: '//item/title'
```

**Comment by cfbao** [comment]
> It seems they are inside a jquery. There is a project on GitHub called[ jQuery watch](https://github.com/RickStrahl/jquery-watch). Could this be implemented inside of urlwatch?

JQuery is only a small part of the story. That project has almost nothing to do with our problem here.

The only proper solution is launching a browser to fully load a dynamic page. As mentioned before, #355 would solve this. But this is a complex feature, and has issues I'd like to fix before review and merge.

**Comment by jprokos** [comment]
I just know that there are many ways this works and I am a bit clueless on the possibilities.

I read that I can use `curl` to pull a page to load everything but dynamic content. I did this for the page I am having trouble with and see the data in the content but can't get the correct path. Is this the same issue?

here is the div content:

```
<div>
                        <div class="documentList" id="Content_RelatedContent_Index_Div2f22ad89_249d_4628_944b_ada7b7c66b02lstDocument"></div><script>
	jQuery(function(){jQuery("#Content_RelatedContent_Index_Div2f22ad89_249d_4628_944b_ada7b7c66b02lstDocument").kendoListView({"dataSource":{"type":(function(){if(kendo.data.transports['aspnetmvc-ajax']){return 'aspnetmvc-ajax';} else{throw new Error('The kendo.aspnetmvc.min.js script is not included.');}})(),"transport":{"read":{"url":""},"prefix":""},"serverPaging":true,"serverSorting":true,"serverFiltering":true,"serverGrouping":true,"serverAggregates":true,"filter":[],"schema":{"data":"Data","total":"Total","errors":"Errors","model":{"fields":{"Type":{"type":"string"},"ItemType":{"type":"string"},"Id":{"type":"string"},"Title":{"type":"string"},"PublicationDate":{"type":"date"},"LastModifiedDate":{"type":"date"},"CoverImageDefaultUrl":{"type":"string"},"CoverImageAltText":{"type":"string"},"CoverImageThumbnailUrl":{"type":"string"},"ItemDefaultUrl":{"type":"string"},"DateCreated":{"type":"date"},"LinkHref":{"type":"string"},"CategoryIds":{"type":"string"},"SocialMediaBar":{"type":"object"},"Url":{"type":"string"},"CallToActionText":{"type":"string"},"CallToActionUrl":{"type":"string"},"CallToActionInternalPageUrl":{"type":"string"},"Icon":{"type":"string"},"OriginalContentId":{"type":"string"},"HighlighterResult":{"type":"string"}}}},"data":{"Data":[{"Type":"Document","ItemType":null,"Id":"8c2c4efa-6cbc-6a0a-9b57-ff00009030c2","Title":"2020 Speedo Summer Championships Time Standards","PublicationDate":"\/Date(1575395341000)\/","LastModifiedDate":"\/Date(-62135571600000)\/","CoverImageDefaultUrl":null,"CoverImageAltText":null,"CoverImageThumbnailUrl":null,"ItemDefaultUrl":null,"DateCreated":"\/Date(-62135571600000)\/","LinkHref":null,"CategoryIds":null,"SocialMediaBar":null,"Url":"//www.usaswimming.org/docs/default-source/timesdocuments/time-standards/2020-speedo-summer-championships-time-standards.pdf","CallToActionText":null,"CallToActionUrl":null,"CallToActionInternalPageUrl":null,"Icon":"PDFicon.png","OriginalContentId":"00000000-0000-0000-0000-000000000000","HighlighterResult":null},{"Type":"Document","ItemType":null,"Id":"e5cb4bfa-6cbc-6a0a-9b57-ff00009030c2","Title":"2020 Speedo Sectionals Time Standards","PublicationDate":"\/Date(1569875392203)\/","LastModifiedDate":"\/Date(-62135571600000)\/","CoverImageDefaultUrl":null,"CoverImageAltText":null,"CoverImageThumbnailUrl":null,"ItemDefaultUrl":null,"DateCreated":"\/Date(-62135571600000)\/","LinkHref":null,"CategoryIds":null,"SocialMediaBar":null,"Url":"//www.usaswimming.org/docs/default-source/timesdocuments/time-standards/2020speedosectionalstimestandards.pdf","CallToActionText":null,"CallToActionUrl":null,"CallToActionInternalPageUrl":null,"Icon":"PDFicon.png","OriginalContentId":"00000000-0000-0000-0000-000000000000","HighlighterResult":null},{"Type":"Document","ItemType":null,"Id":"dccb4bfa-6cbc-6a0a-9b57-ff00009030c2","Title":"2020 Futures Championships Time Standards","PublicationDate":"\/Date(1569875391610)\/","LastModifiedDate":"\/Date(-62135571600000)\/","CoverImageDefaultUrl":null,"CoverImageAltText":null,"CoverImageThumbnailUrl":null,"ItemDefaultUrl":null,"DateCreated":"\/Date(-62135571600000)\/","LinkHref":null,"CategoryIds":null,"SocialMediaBar":null,"Url":"//www.usaswimming.org/docs/default-source/timesdocuments/time-standards/2020futureschampionshipstimestandards.pdf","CallToActionText":null,"CallToActionUrl":null,"CallToActionInternalPageUrl":null,"Icon":"PDFicon.png","OriginalContentId":"00000000-0000-0000-0000-000000000000","HighlighterResult":null},{"Type":"Document","ItemType":null,"Id":"fc2444fa-6cbc-6a0a-9b57-ff00009030c2","Title":"2020 Trials Qualifying Times","PublicationDate":"\/Date(1554395700000)\/","LastModifiedDate":"\/Date(-62135571600000)\/","CoverImageDefaultUrl":null,"CoverImageAltText":null,"CoverImageThumbnailUrl":null,"ItemDefaultUrl":null,"DateCreated":"\/Date(-62135571600000)\/","LinkHref":null,"CategoryIds":null,"SocialMediaBar":null,"Url":"//www.usaswimming.org/docs/default-source/timesdocuments/time-standards/2020-trials-qualifying-times.pdf","CallToActionText":null,"CallToActionUrl":null,"CallToActionInternalPageUrl":null,"Icon":"PDFicon.png","OriginalContentId":"00000000-0000-0000-0000-000000000000","HighlighterResult":null}],"Total":4,"AggregateResults":null}},"template":kendo.template(jQuery('#DocumentTemplate').html())});});
</script>

                    </div>
```

I want to grep for 'Time Standard'

**Comment by thp** [comment]
This issue seems to have turned into a support thread. I'm closing it for now, but don't feel discouraged to reopen new issues for new questions (one issue per question).
