### ISSUE TITLE
Can urlwatch process local html pages?

### ISSUE THREAD

**Issue by ASMotionLab** [thp/urlwatch#449]
Hi,
The page I need to watch is behind a login/captcha.
I've worked around this by using a chrome extension which saves the page periodically, and I want to analyse this offline page for changes.

I've tried to substitute url: in urls.yaml to the file path, but I get an error.

Can urlwatch parse offline html pages?

Thank you for any help

**Comment by cfbao** [comment]
Yes, but you should use the [file URL scheme](https://en.wikipedia.org/wiki/File_URI_scheme).

**Comment by ASMotionLab** [comment]
Excellent, thank you so much, it works! :)
Just for other noobs like me - urls.yaml needs to look like:

`
kind: url
url: file://c:/Users/Username/Folder/File.html
`
