### ISSUE TITLE
Windows: add console_scripts entry point?

### ISSUE THREAD

**Issue by ohk2kt3t4** [thp/urlwatch#451]
First time using urlwatch, unfortunately have to use it in a Windows environment.

I installed urlwatch using [pipx](https://github.com/pipxproject/pipx), and it dropped the urlwatch script from the repo parent directory into my local bin dir, however it is not runnable as a command on Windows.

Other python packages, for example `pycowsay`, define a [console entry point](https://github.com/cs01/pycowsay/blob/b60f4f3b688592ea0924dcf5820b0b094fbf2c95/setup.py#L48) which allows for an [executable to be created](https://packaging.python.org/specifications/entry-points/#use-for-scripts) on install. 

I tried adding an entry point to urlwatch's setup.py but it seems like the package structure doesn't allow for an entry point to be created since the urlwatch script is in the same directory as setup.py.

How are other people on Windows using urlwatch?
(For the time being I have installed it in a venv and am manually calling python /path/to/urlwatch)

**Comment by thp** [comment]
That'd be a good addition, yes (the code in the `urlwatch` script mostly would just need to be moved to a module and the `urlwatch` script just call through that, then we can expose an entry point. Patches gladly accepted, if not I might get around to do it at some point in the future ;)
