### ISSUE TITLE
Possible to get the imediate lines before or after grep pattern?

### ISSUE THREAD

**Issue by DazzyWalkman** [thp/urlwatch#458]
Just as what shell grep -A or -B do.
My url source contains blocks of lines like 

> \<p>datetime<\/p>
> \<p>title<\/p>

I grep for a specific title, that have multiple occurrences on that page. Grep only returns the title lines,  that defeats my purpose of update checking.
So I also need the respective datetime line.
Thank you.

**Comment by jprokos** [comment]
You can grep for more than one line by using the pipe.

Example:
`'(//div[contains(@class,"item")]//h3)/a|(//div[contains(@class,"item")]//h4)/a'`

**Comment by thp** [comment]
In the master branch (not yet in a release) there's now the `shellpipe` filter which you can use to pipe the content through a shell command, so you can use the `grep` command line utility with any parameters you want.

This is documented with examples here:
https://urlwatch.readthedocs.io/en/latest/filters.html#using-a-shell-script-as-a-filter

**Comment by thp** [comment]
This is now in urlwatch 2.19.
