### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by poblabs** [thp/urlwatch#460]
In urlwatch 2.17 I get this error `smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError d188sm7700156ywd.24 - gsmtp',`

It fails with Gmail and it fails with Amazon SES

Reading through the issues here, I've done the less-secure password and the removal of captcha and all that, but it's still not happy. Anyone able to get it working in 2.17?

**Comment by poblabs** [comment]
It appears to work if I build from source, but does not work from the pip package

**Comment by thp** [comment]
Maybe a recent change that hasn't been in a release yet?

**Comment by poblabs** [comment]
Yeah could be. I just installed it again on a vanilla machine. Source works, pip doesn't. So I'll stay with source for now. Thanks

**Comment by asusman** [comment]
New user here.  I have the same issue with 2.17 via gmail and yahoo.
