### ISSUE TITLE
Document Installation instructions in readme

### ISSUE THREAD

**Issue by stroebjo** [thp/urlwatch#464]
Maybe you can provide instructions on what is the preferred way to install urlwatch? 

I installed with pip (`$ python3 -m pip install urlwatch`) which got the me v2.17 from April 2019 (and thus missing some features from the readme as well as full Python 3.8 compatibility). 

In my case I uninstalled it with pip again (`$ python3 -m pip uninstall urlwatch`) and installed it directly from the repo: `$ python3 -m pip install git+git://github.com/thp/urlwatch.git#egg=urlwatch`

It worked for me, but I'm not sure if this is the "proper" way of doing things? I think it would also good to highlight that the pip ist not the current version.

**Comment by jprokos** [comment]
@stroebjo Any precautions before doing this uninstall and reinstall. Your configuration, jobs, hooks, files are still intact?

**Comment by cfbao** [comment]
Released versions are behind the latest code in the code base. This is true for virtually all software.

I'm not the maintainer, but I'd say official instruction should still point to the released versions, i.e. installation via pip, in urlwatch's case.

Using the latest code in the repo is like being a beta tester.

**Comment by jprokos** [comment]
Yes except @stroebjo is saying that some features that are mentioned on the readme are not implemented in the current release version. They are only in the latest code. I think the maintainer said as much in one of my Issues when I spoke of error handling not working. I will look for that and add it here.

**Comment by cfbao** [comment]
Yes, I know. But the issue here is that urlwatch still lacks full fledged and versioned documentation.
Related maintainer comment: https://github.com/thp/urlwatch/issues/425#issuecomment-586616386

The readme of a repo stays up-to-date with the latest code. That's just how GitHub works. Ideally, the readme should provide a short high level summary, and shouldn't be where detailed documentations live. It doesn't mean end users should be directed to use the latest code on the master branch.

**Comment by stroebjo** [comment]
> @stroebjo Any precautions before doing this uninstall and reinstall. Your configuration, jobs, hooks, files are still intact?

Yes, in my case everything still worked after the update. But I suppose a backup of your configs never hurts.

**Comment by jprokos** [comment]
@cfbao Thanks for the explanation. Don't mistake my ignorance for judgement.  For rookies like me GitHub and its contents is a whole new world—an exciting one but mysterious.
