### ISSUE TITLE
How to specify configuration options in jobs. Example please

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#468]
I see one example of specifying a configuration in a job. There are also display and report configurations. Can we configure these per job? If so what is the format?

The example for job defaults is just one line ```ignore_connection_errors: true```
Would this be the case for reports as well or is it this format?
```
report:
   - text:
       minimal: true
```

**Comment by cfbao** [comment]
Reports cannot be configured per job, yet.

**Comment by thp** [comment]
Closing this (and re-opening #507), because it doesn't make sense to set the reporter per job (as all job changes are combined into a single report.

It can still be done by maintaining a separate config + job list and use `--config` and `--urls` with different invocations.
