### ISSUE TITLE
Send Test Message to All Devices

### ISSUE THREAD

**Issue by bretterism** [thp/urlwatch#478]
I would like a command that would send a test message to all my devices whenever executed.

Example: `urlwatch --test-message`
The result would be a message sent to all my devices currently setup with something along the lines of, "THIS IS A TEST MESSAGE".

I have urlwatch tracking a website that changes maybe every couple of weeks. When it does change, it's important that I know ASAP. This feature would be a sanity check to verify that I have my devices setup correctly and will receive messages when a change occurs.

I haven't looked to see what kind of effort this would take. If it would require a massive overhaul, is there any alternative way to test my devices?

**Comment by thp** [comment]
Being able to send a test message probably makes sense.

However, if you anyway want to basically have a "watchdog" service that sends regular notifications that it's still running, you can for example watch the output of the shell job: `date +%U` (this prints the week number), this way you'll get a notification every week.

Alternatively, you can use e.g. `date +%F` (full date) to get daily notifications, etc.. -- you could even just have a text file that you are watching and append to it (or just change it) whenever you want a notification sent.

Or if you have access to a web server, trigger it by watching some URL on it.

Here's the "weekly watchdog" example:

```
name: "Weekly Watchdog Job"
kind: shell
command: "date +%U"

**Comment by bretterism** [comment]
That is a great idea! I will try that out today. Since I have urlwatch running every 30 minutes, I'll just create a second cron job that runs once a day and updates a file with the timestamp.

Unless there's another good use case for adding the --test-message feature, I think your solution should work.

**Comment by bretterism** [comment]
Got it working. For those who stumble on this issue I did two things:

Set a new cron job with the following settings: `59 12 * * * date > /home/pi/watchdog.txt`
This puts a new date in my file once every day at 12:59PM.

Created a new job in urlwatch:
```
kind: shell
name: Test Endpoints Daily
command: "cat /home/pi/watchdog.txt"
```
Not sure if there's an alternate way to watch files, but this worked for me.

**Comment by thp** [comment]
Cool!
