### ISSUE TITLE
URLs ending with space are changed by XPath filter

### ISSUE THREAD

**Issue by mborsetti** [thp/urlwatch#485]
I monitor a site that (incorrectly, I guess) once in a while adds a space to the `href` in the a `tag`, like so:
```html
<a href="https://test.com/this-url-ends-with-space ">test</a>
```

While a browser has no problem with a space at the end of an URL, and neither does the Python `html2text` library, when I use _urlwatch_'s XPath filter (by itself or before the Python `html2text` library) I end up with a different URL: https://test.com/this-url-ends-with-space%20. When clicked this URL leads to a (typically) inexistent resource and not to the intended place.

I tracked this error down to this statement:
https://github.com/thp/urlwatch/blob/0ec5f2d596431f634dc1c11e8ded60693a4cbbcf/lib/urlwatch/filters.py#L430 
Specifically to the parameter `method=self.method`, which evaluates to `method='html'`.  If I remove this parameter and allow lxml.etree to use its defaults, all works well.

I am not too familiar with lxml, its [documentation](https://lxml.de/api/lxml.etree-module.html#tostring) isn't clear, and I see that the filter is built to handle xml as well, so don't really know what's the best way to code a fix for this issue.

**Comment by thp** [comment]
The default method (if not specified) is `xml` (as mentioned in the documentation):

> The keyword argument 'method' selects the output method: 'xml', 'html', plain 'text' (text content without tags), 'c14n' or 'c14n2'. Default is 'xml'.

One can use this to get the desired behavior:

```yaml
  filter:
    - xpath:
        path: /body
        method: xml
```
