### ISSUE TITLE
reverse a list 

### ISSUE THREAD

**Issue by ghost** [thp/urlwatch#497]
I wonder how to reverse a list (not sort a list in a descending order, e.g. https://github.com/thp/urlwatch/commit/4009a55a57b6d51c4066b190b57a090f4a61511d). Thank you.

**Comment by thp** [comment]
There was an issue/PR at some point for this, but I can't find it anymore.

**Comment by vuwjzl17985** [comment]
Thank you for your information.
I create a pull request for this issue https://github.com/thp/urlwatch/pull/503.
