### ISSUE TITLE
error: unrecognized arguments: my_file_path/Library/Application Support/urlwatch/urls.edit.yaml Parsing failed:

### ISSUE THREAD

**Issue by irisdemented** [thp/urlwatch#508]
Hi there, 

I've been attempting to install URL watch for a few days now and clearly i'm missing something or doing something wrong because I keep getting this same error, though i've uninstalled and reinstalled it a number of times.  I appreciate any help anyone can give! Thanks much.
edit - this is my first time asking a question on github and i don't know why the formatting is so crazy, i tried to fix it but was unsuccessful - sorry!! 

1) I installed via 'python3 -m pip install --upgrade urlwatch' and the screen then said:

"A default config has been written to my_file_path/Library/Application Support/urlwatch/urlwatch.yaml.
    Use "urlwatch --edit-config" to customize it.
      
    You need to create my_file_path/Library/Application Support/urlwatch/urls.yaml in order to use urlwatch.
    Use "urlwatch --edit" to open the file with your editor."

2) So then I ran "urlwatch --edit" and received the following: 

"urlwatch: error: unrecognized arguments: my_file_path/Library/Application Support/urlwatch/urls.edit.yaml
Parsing failed:
======
Command '['urlwatch', 'my_file_path/Library/Application Support/urlwatch/urls.edit.yaml']' returned non-zero exit status 2.
======

The file my_file_path/Library/Application Support/urlwatch/urls.edit.yaml was NOT updated."

**Comment by irisdemented** [comment]
Bumping this - still trying to figure out how to resolve! 
After installing I try to run urlwatch --edit and I keep getting the following errors: 

urlwatch: error: unrecognized arguments: /Users/val/Library/Application Support/urlwatch/urls.edit.yaml
Parsing failed:
======
Command '['urlwatch', '/Users/val/Library/Application Support/urlwatch/urls.edit.yaml']' returned non-zero exit status 2.
======

I have not been able to resolve. Any help is much appreciated.

**Comment by thp** [comment]
What is your `$VISUAL` and `$EDITOR` variable set to? It looks like it's trying to run `urlwatch` as text editor (with the file to  be edited as first argument) which obviously doesn't work.

Try this:

    env EDITOR=nano VISUAL=nano urlwatch --edit
