### ISSUE TITLE
Warn when user has POSIX locale and suggest using UTF-8 instead

### ISSUE THREAD

**Issue by thp** [thp/urlwatch#51]
If the system locale is set to POSIX (or C), then some features won't work properly. Suggest to the user that they set the environment to UTF-8 (or fallback to UTF-8 in any case?).

**Comment by katylava** [comment]
Any idea how to work around this in a cron job? I have `15 * * * * LC_ALL=en_US.UTF-8 && urlwatch` but still getting "UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 172: ordinal not in range(128)". It seems to work fine outside of cron.

Here's my config:

```
kind: url
name: lumo lift android
url: http://www.lumobodytech.com/support/lumo-lift-troubleshoot-android/
filter: element-by-id:cant-connect-lumo-lift
```

**Comment by thp** [comment]
Try:

    env LC_ALL=en_US.UTF-8 urlwatch
