### ISSUE TITLE
Url with lazy load content (does not load until scroll)

### ISSUE THREAD

**Issue by ASL07** [thp/urlwatch#514]
Hi,

I'm trying to get data from a url that only loads some content after scrolling. 

Is there a way to force urlwatch to scroll, or force the url to load all content without scrolling?

I have tried using the `navigate` method, but it doesn't work either

This is an example where only the two first jobs are loaded and the next ones do not load until after scrolling. `urlwatch` only gets the first two jobs:
https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=c%2B%2B&normalizedJobTitleIds=&provinceIds=&cityIds=&categoryIds=&workdayIds=&educationIds=&segmentId=&contractTypeIds=&page=1&sortBy=&onlyForeignCountry=false&countryIds=&sinceDate=ANY&subcategoryIds=

Thanks

**Comment by cfbao** [comment]
It's not currently possible.
The `browser` (`navigate`) job type may be extended to support scrolling in future, but it's broken at the moment, and it'd probably be some time before it can be fixed.

**Comment by thp** [comment]
Marking as enhancement for the scrolling part.

The fact that `browser` jobs don't work properly at the moment is already reported as #293.

**Comment by thp** [comment]
As mentioned in the docs, it seems like for this page, the things that the JavaScript loads is obtained via a REST API, so you might want to monitor this URL instead:

https://www.infojobs.net/webapp/offers/search?keyword=c%2B%2B&normalizedJobTitleIds=&provinceIds=&cityIds=&categoryIds=&workdayIds=&educationIds=&segmentId=&contractTypeIds=&page=2&sortBy=&onlyForeignCountry=false&countryIds=&sinceDate=ANY&subcategoryIds=

While this works in the browser (at least when accessing the "normal" page), it doesn't seem to work in urlwatch (user-agent/cookies/...)?
