### ISSUE TITLE
Feature Request - Diff to Script

### ISSUE THREAD

**Issue by Shaav** [thp/urlwatch#515]
Forgive me if there's already a way to accomplish this that I overlooked—I don't think that it's possible right now...

I was thinking it would be really useful to have the ability to pass the diff output of a job to custom script. The specific use-case I had in mind is a webpage I monitor for additional links. I would like to pull the new links added and then trigger wget on them. What I'm imagining is pretty simple I think—something like:

    name: "My Job"
    url:https://example.com/links.html
    filter: element-by-tag:a
    script: /<path-to-script>/process_new_links.sh

I guess it's kind of like a custom reporter, but I wouldn't want to run all my jobs through it.  I think it would also be useful to optionally have the output of the script be passed back to the reporter or to ignore it and just report the diff like usual.

**Comment by thp** [comment]
Why not use the `stdout` reporter and pipe urlwatch output into your custom script? You can have a separate configuration and jobs file for the job you want to do this for and keep the rest of the configuration separate.

**Comment by Shaav** [comment]
> Why not use the `stdout` reporter and pipe urlwatch output into your custom script? You can have a separate configuration and jobs file for the job you want to do this for and keep the rest of the configuration separate.

Thanks for the suggestion, I'll give that a try.

It's actually 10 or 12 different jobs so that becomes a lot of overhead keeping and calling that many different configuration files. Or I guess parsing through the output based on the titles.

**Comment by thp** [comment]
As an alternative, you can set `diff_tool` on the job and it gets the old a new content as filename parameters (the files will be temporary files that contain the old and new page content) and you can do whatever you want there as a side effect.

**Comment by thp** [comment]
In the Git master branch (not yet in any release) it's now possible to specify a `diff_filter` that can - in combination with `shellpipe` be used for that. As an added bonus, the output of the script is the thing that urlwatch reports as the diff contents, so if the script outputs the results of processing, you can use urlwatch to send the processing results to any of the supported reporters.

This is now also documented as "Advanced Topic" here:
https://urlwatch.readthedocs.io/en/latest/advanced.html#pass-diff-output-to-a-custom-script

**Comment by Shaav** [comment]
Awesome! You are a scholar and a gentleman!  Thanks! :)
