### ISSUE TITLE
cssbeautifier/jsbeautifier conflicts

### ISSUE THREAD

**Issue by captbrando** [thp/urlwatch#526]
I realize this is likely an upstream problem, but I cannot get URLWatch to load all the proper packages. Seems like some kind of cssbeautifier/jsbeautifier conflict. 

Here's the output from the setup:

```
$ sudo python3 -m pip install pyyaml minidb requests keyring appdirs lxml cssselect beautifulsoup4 jsbeautifier cssbeautifier
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyyaml
  Downloading https://www.piwheels.org/simple/pyyaml/PyYAML-5.3.1-cp37-cp37m-linux_armv6l.whl (44kB)
    100% |████████████████████████████████| 51kB 172kB/s
Collecting minidb
  Downloading https://www.piwheels.org/simple/minidb/minidb-2.0.4-py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.21.0)
Requirement already satisfied: keyring in /usr/lib/python3/dist-packages (17.1.1)
Collecting appdirs
  Downloading https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting lxml
  Downloading https://www.piwheels.org/simple/lxml/lxml-4.5.2-cp37-cp37m-linux_armv6l.whl (6.0MB)
    100% |████████████████████████████████| 6.0MB 13kB/s
Collecting cssselect
  Downloading https://files.pythonhosted.org/packages/3b/d4/3b5c17f00cce85b9a1e6f91096e1cc8e8ede2e1be8e96b87ce1ed09e92c5/cssselect-1.1.0-py2.py3-none-any.whl
Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/66/25/ff030e2437265616a1e9b25ccc864e0371a0bc3adb7c5a404fd661c6f4f6/beautifulsoup4-4.9.1-py3-none-any.whl (115kB)
    100% |████████████████████████████████| 122kB 460kB/s
Collecting jsbeautifier
  Downloading https://www.piwheels.org/simple/jsbeautifier/jsbeautifier-1.11.0-py3-none-any.whl (89kB)
    100% |████████████████████████████████| 92kB 253kB/s
Collecting cssbeautifier
  Downloading https://files.pythonhosted.org/packages/0f/64/f3cdac9461be42f6c359810ba4cbe23363d1edfafad7a3d49b5fe8a58d2a/cssbeautifier-1.11.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uw5eveem/cssbeautifier/setup.py", line 7, in <module>
        from jsbeautifier.__version__ import __version__
    ModuleNotFoundError: No module named 'jsbeautifier'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-uw5eveem/cssbeautifier/
```

**Comment by captbrando** [comment]
Also manifests itself while trying to build a Docker container.

```
❯ docker build .
Sending build context to Docker daemon  1.242MB
Step 1/10 : FROM python:3.8.2
3.8.2: Pulling from library/python
152c1d0ea8a0: Pull complete
b6bff79e1c1f: Pull complete
4a316208b086: Pull complete
d0ab435daaee: Pull complete
d15a0da8a934: Pull complete
dd6d524414ff: Pull complete
0061afb0b085: Pull complete
fec66b4d4ecb: Pull complete
5d4fc5be84b9: Pull complete
Digest: sha256:8c98602bf4f4b2f9b6bd8def396d5149821c59f8a69e74aea1b5207713a70381
Status: Downloaded newer image for python:3.8.2
 ---> a0781731ff0f
Step 2/10 : RUN python3 -m pip install pyyaml minidb requests keyring appdirs lxml cssselect beautifulsoup4 jsbeautifier cssbeautifier
 ---> Running in 8dc1812b53f5
The command '/bin/sh -c python3 -m pip install pyyaml minidb requests keyring appdirs lxml cssselect beautifulsoup4 jsbeautifier cssbeautifier' returned a non-zero code: 139
```

**Comment by thp** [comment]
According to [this page](https://github.com/beautify-web/js-beautify#python), `jsbeautifier` needs to be already installed at `cssbeautifier` install time:

> To install the Python version of the beautifier:
> ```    $ pip install jsbeautifier```
> Unlike the JavaScript version, the Python version can only reformat JavaScript. It does not work against HTML or CSS files, but you can install css-beautify for CSS (jsbeautifier needs to be installed already)
> ```    $ pip install cssbeautifier```

This is likely an [upstream packaging issue](https://github.com/beautify-web/js-beautify/tree/master/python), because both packages live in the same repo, but the `setup.py` file of the packages (`setup.py` is for `jsbeautifier`, `setup-css.py` is for `cssbeautifier`) always refers to `jsbeautifier` to get the version number.

See also: https://github.com/beautify-web/js-beautify/issues/1808

**Comment by thp** [comment]
I have submitted https://github.com/beautify-web/js-beautify/pull/1815 upstream as a way of fixing this.

Local workaround in the meantime:

    python3 -m pip install jsbeautifier
    python3 -m pip install cssbeautifier

(because at the time `cssbeautifier`'s `setup.py` is run, it will already be able to import `__version__` from `jsbeautifier`)

**Comment by thp** [comment]
https://github.com/beautify-web/js-beautify/pull/1815 has been merged, this will hopefully be resolved once upstream creates a new release (no new release yet). I'm closing this already now, but please feel free to reopen if it is still an issue once the new version of `jsbeautifier` / `cssbeautifier` is out.

**Comment by captbrando** [comment]
Still didn't work for me (tried the workaround as well as the docker build). I wonder if I need to remove all my python plugins and start over. At any rate, I'll poke around.
