### ISSUE TITLE
urlwatch convience script fails if cwd is different

### ISSUE THREAD

**Issue by e-dschungel** [thp/urlwatch#531]
Hi,

the urlwatch convience script fails if the cwd is not equal to the dir the script lives in. The error message is:
```
Traceback (most recent call last):
  File "urlwatch/urlwatch", line 7, in <module>
    from urlwatch.cli import main
ImportError: No module named 'urlwatch'
```
My solution is to construct an absolute path to import from:
```
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'lib'))
from urlwatch.cli import main
main()
```
That works for me but there are [different use cases](https://stackoverflow.com/a/50025581) where this is not enough.

Regards
e-dschungel

**Comment by thp** [comment]
Thanks, fixed. The use case described in your link talk about `cx_Freeze` and `IDLE`, which don't apply here, since the only point of the script is to run it from the shell in a Git checkout, the "urlwatch" command that gets installed is created via `entry_points` in `setup.py`.
