### ISSUE TITLE
Allow MULTILINE mode for re.sub filter

### ISSUE THREAD

**Issue by protist** [thp/urlwatch#532]
If I am correct, the `re.sub` filter doesn't use `MULTILINE` mode. From my testing, `^` won't match with the beginning of lines. For example, with the following config:
```
kind: url
url: https://software.broadinstitute.org/software/igv/download
filter:
  - re.sub: '^jQuery.*'
```
The filter does not match:
```
$ urlwatch --test-filter 17 | grep jQuery
jQuery.extend(Drupal.settings, { "basePath": "/software/igv/", "cron": { "basePath": "/software/igv/poormanscron", "runNext": 1595878126 } });
```
Whereas if I replace `^` with `\n`, it works. It would be useful to enable `MULTILINE` mode for the `re.sub` filter, or at least to allow users the option. Personally, I think using it by default is fine, because we always have `\A` and `\Z` anyway. Also, users familiar with other programming languages (e.g. `sed`, `awk`) might reasonably expect `^` and `$` to match per line.

```
$ urlwatch --version
urlwatch 2.19
```

**Comment by thp** [comment]
Note that with version 2.19, you can use the `shellpipe` filter and actually use `sed` or `awk`:

https://urlwatch.readthedocs.io/en/latest/filters.html#using-a-shell-script-as-a-filter

**Comment by thp** [comment]
If you want to remove lines starting with `jQuery`, use this:

    filter:
      - grepi: ^jQuery

I wasn't able to remove lines even with `re.MULTILINE` in my testing. According to [its documentation](https://docs.python.org/3/library/re.html#re.MULTILINE) it can also be enabled with the inline flag `(?m)`.

**Comment by protist** [comment]
Thanks for the other options, especially the pointer to `grepi`. That's a far more elegant solution than using `re.sub` in any case.

FWIW I tested the following change and it seemed to work for me.
```
--- a/urlwatch/filters.py	2020-07-21 19:59:47.338521485 +1000
+++ b/urlwatch/filters.py	2020-07-21 19:59:20.429027433 +1000
@@ -721,7 +721,7 @@
             raise ValueError('{} needs a pattern'.format(self.__kind__))
 
         # Default: Replace with empty string if no "repl" value is set
-        return re.sub(subfilter['pattern'], subfilter.get('repl', ''), data)
+        return re.sub(subfilter['pattern'], subfilter.get('repl', ''), data, flags=re.MULTILINE)
 
 
 class SortFilter(FilterBase):
```

**Comment by thp** [comment]
Weird, it doesn't work for me even when using directly in Python code:

```
% python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.sub('^jQuery.*', '', "A\njQuery B\nC\n", re.MULTILINE)
'A\njQuery B\nC\n'
```

**Comment by thp** [comment]
Nevermind, I accidentally set the "count", not the flags :)

**Comment by protist** [comment]
Haha nice. That's the advantage of my relative ignorance in python… I have to look everything up.

**Comment by thp** [comment]
Indeed, it works:
```
>>> re.sub('^jQuery.*', '', "A\njQuery B\nC\n", flags=re.MULTILINE)
'A\n\nC\n'
>>> re.sub('^jQuery.*', '', "A\njQuery B\nC\n")
'A\njQuery B\nC\n'
>>> re.sub('(?m)^jQuery.*', '', "A\njQuery B\nC\n")
'A\n\nC\n'
```

Because it's possible to opt-in (using `(?m)`) but not to opt-out, I'd leave the default as-is,

**Comment by thp** [comment]
Improve the `re.sub` filter documentation with an example how to use it (+ added a unit test to verify it works):

https://urlwatch.readthedocs.io/en/latest/filters.html#remove-or-replace-text-using-regular-expressions

**Comment by protist** [comment]
Sounds good to me. Thank you for the quick responses!
