### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by jaan143** [thp/urlwatch#534]
can you please guide me where i can add my webpages and where i can and needed words ?
thank you soo much please

**Comment by Markus00000** [comment]
How to add your webpages is explained here:

https://urlwatch.readthedocs.io/en/latest/jobs.html

This may answer the second part of your question:

https://urlwatch.readthedocs.io/en/latest/filters.html

**Comment by jaan143** [comment]
i cant find this file in project folder (urls.yaml)

**Comment by thp** [comment]
It is not in the project folder. Use `urlwatch --edit` to open the editor.
