### ISSUE TITLE
Do jobs sequential

### ISSUE THREAD

**Issue by JsBergbau** [thp/urlwatch#549]
I monitor different URLs on one site. I don't want to generate too much load on the site. So I'd like to fetch the urls sequential. So when URL1 is done, urlwatch requests the second URL and so on. Is this possible?

**Comment by thp** [comment]
This is not possible at the moment, see #331 and #171 for related issues.

One way to do it would be to have a separate urls.yaml for each job and have separate cron jobs for those, e.g.:

    10,30,50 * * * * urlwatch --urls /path/to/job1.yaml
    0,20,40  * * * * urlwatch --urls /path/to/job2.yaml

**Comment by thp** [comment]
(closed because #331 mostly deals with this)
