### ISSUE TITLE
Content missing

### ISSUE THREAD

**Issue by SHU-red** [thp/urlwatch#554]
Sorry for another question (which is maybe simple to answer)
Im trying to watch this url:
```
name: "Android Developers - OTA files"
url: "https://developers.google.com/android/ota/"
```
The feedback i get by using
`urlwatch --test-filter FILTER#`
differs very much from the source-code of the page which i can view in my browser

--> The tables listing the new OTA-files are completely missing in the urlwatch-feedback
--> Sorry im not in too deep into this stuff but i dont know why stuff is missing if im not applying any filter

And if im not completely wrong, the content im trying to watch is replaced by this code
```
<p><a tabindex="0" class="button button-primary devsite-acknowledgement-link"
   data-globally-unique-wall-id="nexus-ota-tos">Acknowledge</a>
I have read and agree with the above terms and conditions.</p>
```

Maybe the Google page is somehow recognising that its not a browser and hiding all of the other stuff?

Thank you in advance!

**Comment by SHU-red** [comment]
Update,
i now tried using the browser method
```
name: "Android Developers - OTA files"
navigate: "https://developers.google.com/android/ota/"
```
Had a hard time to get pyppeteer running on my rpie 3 but with the change of code in browser-py from
```
    @asyncio.coroutine
    def _launch_browser(self):
        browser = yield from pyppeteer.launch()
        for p in (yield from browser.pages()):
            yield from p.close()
        return browser
```
to

```
    @asyncio.coroutine
    def _launch_browser(self):
        browser = yield from pyppeteer.launch(executablePath = '/usr/bin/chromium-browser')
        for p in (yield from browser.pages()):
            yield from p.close()
        return browser
```
i got pyppeteer running!

But the result is still the same as im using url --> Table content of https://developers.google.com/android/ota is completely missing so i still cant watch the content which im looking for

**Comment by SHU-red** [comment]
One last info.
Maybe its very helpful for you to see the different results i get --> Attatched as .log-files to this post

1. Result from my Brave-Browser > Right-Click > Show SourceCode of site
2. Result from parsing with urlwatch url:
3. Result from parsing with urlwatch navigate:

Sorry i have no idea where the difference between browsing on the site via browser, and parsing content with urlwatch is

Maybe someone can give me a tip

Thanks a lot guys

[BraveBrowser_SiteSourceCode.log](https://github.com/thp/urlwatch/files/5076533/BraveBrowser_SiteSourceCode.log)
[Url.log](https://github.com/thp/urlwatch/files/5076534/Url.log)
[Browser_Navigate.log](https://github.com/thp/urlwatch/files/5076535/Browser_Navigate.log)

**Comment by scottmac** [comment]
Google requires login to view the page, view it in incognito mode and it matches urlwatch's output

`<p><a tabindex="0" class="button button-primary devsite-acknowledgement-link"
   data-globally-unique-wall-id="nexus-ota-tos">Acknowledge</a>
I have read and agree with the above terms and conditions.</p>`

**Comment by SHU-red** [comment]
Hello scottmac,
thanks a lot! You are absoluely right ...

Seems that i have no chance to get beyond the point where the "accept" button has to be pressed.

Thank you
