### ISSUE TITLE
pygments dependency?

### ISSUE THREAD

**Issue by sbraz** [thp/urlwatch#570]
Hi,
I don't really understand why pygments is listed under test dependencies, it doesn't seem to be used anywhere.

**Comment by thp** [comment]
It's used for documentation generation.

**Comment by sbraz** [comment]
Hi Thomas,
In that case, it's not really a test dependency, it also gets pulled by Sphinx [here](https://github.com/sphinx-doc/sphinx/blob/008d0201e1b3475a60daffd6211dab8b501e3964/setup.py#L25) so I doubt it needs to be listed.
