### ISSUE TITLE
test-diff-filter outputs the date and time the command was run instead of state-capture date and time

### ISSUE THREAD

**Issue by jamesquilty** [thp/urlwatch#573]
I've noticed that the latest version of `urlwatch` shows the same date and time, the date when the command was run:

```shell
% urlwatch --version
urlwatch 2.21
% urlwatch --test-diff-filter 2
=== Filtered diff between state 0 and state 1 ===
--- @   Fri, 18 Sep 2020 16:16:28 +1200
+++ @   Fri, 18 Sep 2020 16:16:28 +1200
...
=== Filtered diff between state 2 and state 3 ===
--- @   Fri, 18 Sep 2020 16:16:28 +1200
+++ @   Fri, 18 Sep 2020 16:16:28 +1200
...
=== Filtered diff between state 3 and state 4 ===
--- @   Fri, 18 Sep 2020 16:16:28 +1200
+++ @   Fri, 18 Sep 2020 16:16:28 +1200
...
etc.
```

which is unexpected. I'd expect the date the page content was saved to the database to be displayed for each state, and I think that was the behaviour of earlier versions. It would be great if the state capture date and time could be displayed instead.

**Comment by thp** [comment]
Fixed, thanks for the report.
