### ISSUE TITLE
Automatically cleaning up cached content

### ISSUE THREAD

**Issue by Immortalin** [thp/urlwatch#58]
Does urlwatch automatically clean up its cache? i.e. keep only the latest version of a page and delete any old versions.

**Comment by brbsix** [comment]
*cache.db* is a SQLite 3.x database. You can open it up and review previous versions of any particular page. I don't know off the top of my head whether anything is ever removed though I can check.

**Comment by Immortalin** [comment]
@brbsix [this function](https://github.com/thp/urlwatch/blob/master/lib/urlwatch/storage.py#L287) seems to suggest auto clean up but my python skills are not good enough to figure out exactly where is it implemented

**Comment by brbsix** [comment]
I just checked, everything is kept indefinitely unless you call the command-line option `--gc-cache` to remove old cache entries.

**Comment by Immortalin** [comment]
@brbsix can a feature be added to only retain the latest version of the page?

**Comment by brbsix** [comment]
Sure... See the following diff of *urlwatch* if you want to add it. Essentially it just runs `--gc-cache` upon completion.

```
diff --git a/urlwatch b/urlwatch
index 4878c13..328cb6d 100755
--- a/urlwatch
+++ b/urlwatch
@@ -341,6 +341,9 @@ def main(args):
     # Output everything
     report.finish()
 
+    # Remove old cache entries
+    cache_storage.gc([job.get_guid() for job in jobs])
+
     # Close cache
     cache_storage.close()
```

Also if you don't want it to squawk at you about removed entries, you can incorporate the following:

```
diff --git a/lib/urlwatch/storage.py b/lib/urlwatch/storage.py
index 43463c7..20fa415 100644
--- a/lib/urlwatch/storage.py
+++ b/lib/urlwatch/storage.py
@@ -240,13 +240,10 @@ class CacheStorage(object):
 
     def gc(self, known_guids):
         for guid in set(self.get_guids()) - set(known_guids):
-            print('Removing: {guid}'.format(guid=guid))
             self.delete(guid)
 
         for guid in known_guids:
-            count = self.clean(guid)
-            if count > 0:
-                print('Removed {count} old versions of {guid}'.format(count=count, guid=guid))
+            self.clean(guid)
 
 
 class CacheDirStorage(CacheStorage):
```

**Comment by thp** [comment]
It might be useful to provide this as a config option. For now, I don't do it automatically so we can at some point maybe have a version browser and detect pages that change between multiple states (see #22), although this is not yet implemented.

Might also make sense to have some default cache clearing (e.g. clear entries older than X days) and just make the timeout configurable, with the value 0 meaning "clear all old entries".

**Comment by Immortalin** [comment]
@brbsix thanks
