### ISSUE TITLE
Question How to create a Placeholder Job?

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#584]
I append an index number to my jobs so I can easily associate them with notices I receive in Pushover. 

`name: 01_urlwatch update released`

Sometimes the html on a page will change so I can't monitor it, or I no longer wish to monitor that page. If I erase that job from `urls.yaml` I have to manually change the index number for every other job - a PITA.

If possible is there a way to edit those jobs so they do nothing? So I don't have to remove them and upset the rest of the job numbers? I know I can comment them out but this causes my index numbers to be off.

If a feature can not be added there is a way to accomplish this with command line tools using `awk` on MacOS using GNU `awk`
```
gawk -i inplace '/^name/{sub(/[0-9]{2}/,sprintf("%02d", ++c))}1' /path/to/file
```

**Comment by thp** [comment]
Use either awk as described in your question or write a small Python script that loads the `urls.yaml` and re-writes the names. In theory, just leaving the numbers as-is is not an option? IMHO it's better if job 42 is still job 42, even if job 33 goes away, the holes shouldn't matter? I don't really see the point in having an index number there if the index number changes every time a job is added or removed.

**Comment by jprokos** [comment]
Thanks again.  I guess I forgot to mention the main reason. When testing jobs it’s handy when the index numbers match.
