### ISSUE TITLE
'kind' not set with 'navigate'

### ISSUE THREAD

**Issue by Shaav** [thp/urlwatch#587]
My understanding is that 'kind' should not need to be specified because it is implied by the job type?

When I try to use a 'navigate' job without explicitly setting 'kind' to browser, I get the following error:

`ValueError: Kind is not specified, and no job matches:`

**Comment by thp** [comment]
Which urlwatch version are you using?
Can you post the full contents of `urls.yaml` that you are using? (possibly reduced to a [Short, Self Contained, Correct Example](http://sscce.org))

**Comment by Shaav** [comment]
Just removed the "kind" declarations and the problem appears to have gone away.

Now on 2.21—possibly updated in the interim; not 100% sure.
