### ISSUE TITLE
Add Mattermost reporter

### ISSUE THREAD

**Issue by jamesquilty** [thp/urlwatch#596]
Mattermost <https://mattermost.com> is a workplace messaging app similar to Slack. Mattermost incoming webhooks are similar enough that the existing Slack reporter successfully posts to an incoming webhook on a Mattermost server. I presently use a Slack entry in the configuration file as a synonym for Mattermost, but it would be a "nice-to-have" if urlwatch could please be extended to supported a separate Mattermost reporter in the configuration file.

**Comment by thp** [comment]
Patches glady accepted.

**Comment by jamesquilty** [comment]
Thank you very much for acting on my request! Writing a patch was something I'd like to do but even this simple thing is beyond me at this point. I very much appreciate your spending your time on this.
