### ISSUE TITLE
dict based config 

### ISSUE THREAD

**Issue by e-dschungel** [thp/urlwatch#605]
Converting an older string based config to the new dict based I fell over 3 issues:

Indentation:
In the urls.yaml no tabs are allowed for indenting the filters. If the parser cannot be improved to handle that by itself that should be in the [docs]( https://urlwatch.readthedocs.io/en/latest/deprecated.html).

Spacing:
In the dict based config there must be a space between the colon and the argument otherwise the filter is reported as unknown:
`ValueError: Unknown filter kind: element-by-id:content-section (subfilter {}`)
Thats surprising because in the string base it was without a space and the error message isn't really gives a hint in the right direction. If the parser cannot be improved that should be in the [docs]( https://urlwatch.readthedocs.io/en/latest/deprecated.html).

Unnamed arguments:
The [comment on the unnamed arguments](https://github.com/thp/urlwatch/issues/560#issuecomment-678819228) should be [here]( https://urlwatch.readthedocs.io/en/latest/deprecated.html) too.

**Comment by cfbao** [comment]
I find that most users reported confusions around the config file can be addressed by learning a bit more about the YAML format.

urlwatch doesn't have its own config format or parser per se. It uses the standard YAML format with a standard YAML parser, as mentioned in the [introduction](https://urlwatch.readthedocs.io/en/latest/introduction.html).

Issues you reported are just standard syntax of YAML, e.g. YAML only allows indentation with spaces, and YAML requires that dictionary keys are followed by `: ` with a space.

**Comment by thp** [comment]
Closing as "works for me", YAML syntax can be looked up at [yaml.org](https://yaml.org).
