### ISSUE TITLE
self-supervision of jobs when errors are ignored

### ISSUE THREAD

**Issue by kongomongo** [thp/urlwatch#606]
Hi there,

I love urlwatch, thanks for everyone contributing!

One thing I found myself between a rock and a hard place:

Theres one site, that always reports 404 during 3:00 and 4:00 AM (probably due to maintenance) and another that has regular timeouts, then continues to work normally etc.

My interval is 5 minutes for these jobs.

When I put ignore_timeout_errors and ignore_http_error_codes: 404 in there, I have that bad feeling of: "what if that 404 or that timeout goes permanent in the future?". I will not be notified and this could be bad.

I know that this is not really the focus of the urlwatch project, but can you guys point me in the right direction here?

I was thinking of making a daily urlwatch job (command, shellpipe, etc.) that just scans the " age of last successful runtime" of all jobs and simply reports that. That age should never change so I would only get a report from urlwatch if a job didnt run successfully for a significant amount of time.

Is there anything in urlwatch cli that gives me that? Or do I need a sqlite3 client and some SQL-fu?

Many thanks in advance.

**Comment by cfbao** [comment]
This doesn't seem to be documented, but you can specify a [`max_tries`](https://github.com/thp/urlwatch/blob/4eb9391829267f42e669988a91cff6cbe112d067/lib/urlwatch/jobs.py#L183) > 1 in job config, so urlwatch will only report error when the job failed a consecutive number of times.

**Comment by kongomongo** [comment]
cfbao,

Unfortunately I do not know how many times it fails. Could be up to 30x in a row for 3hours in the night.

**Comment by cfbao** [comment]
Then set it to 30+?
If like you said, a daily scan would be sufficient for your purpose, then I don't see the harm in setting `max_tries` large enough so that it only reports the error after failing for 12 hours.

**Comment by kongomongo** [comment]
alright, lets follow through on this

I have a crontab running every 5 minutes.

If i set maxtries to 30 I guess it doesn't abort the first try and increases counter one the next launch in 5 minutes but rather it will try 30 times (let's say timeout 60 secs, 30 tries would be try for 30 minutes to connect?). Then 5 mins later next urlwatch instance is launched and will also try for 30 minutes, and so on?

If that's the case I don't think it's very economical? If it just increases the counter then yes I think it could work, haven't thought about all the scenarios...

**Comment by cfbao** [comment]
It doesn't work like this.

When it fails, it increases the counter and stops. No retries. 5 min later when the job fires again, it'll use the counter from the last time.
Errors are reported only if the counter reaches or exceeds `max_tries`. The counter is reset to 0 when the job succeeds.

**Comment by kongomongo** [comment]
What can I say, it works perfect for my case. Awesome, thank you!
