### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by ahmad82pkn** [thp/urlwatch#614]
I am monitoring 700 Sublinks of a main website and sometime its not working due to captcha presented by website.

Is there any if condition or setting i can implement to not do comparison or dont generate email if there is captcha presented by website? and re try later?

This is what i see in email.

 <p class="a-last">Our servers are getting hit pretty hard right now. To continue shopping, enter the characters as they are shown 
-                    in the image below.</p>

**Comment by thp** [comment]
The website using captchas doesn't want you to use automated tools. There's nothing we can do here. You can ask the webpage provider to disable captchas or to provide you with a direct API feed of the data.
