### ISSUE TITLE
How to start a shellpipe command in background and continue?

### ISSUE THREAD

**Issue by martinjo** [thp/urlwatch#617]
Hi!

I'm using a diff_filter and shellpipe to start a script that takes some time to complete.
Ideally I'd like urlwatch to start the job and then continue (sending me a message via the pushover reporter).
The job starts fine, but it seems urlwatch waits for the job to finish however I try to start it in the background

diff_filter:
 - shellpipe: '(python3 scriptthattakessometime.py &)'
 - shellpipe: 'echo "script that takes some time was started"'

Is there a way to do this? Perhaps my understanding of bash scripts is lacking :/

Any tips would be appreciated :)

**Comment by kongomongo** [comment]
What exactly is not working as you want?

**Comment by martinjo** [comment]
The problem is that urlwatch always waits for tithe command to finish. It makes sense in the context of a filter, but less so when you only want a command to launch and then let urlwatch continue working. I solved it by starting a new process with the command that I want to run.

**Comment by thp** [comment]
urlwatch has to wait for the command to finish, as it needs to read its complete stdout to diff against previous invocations. As you have figured out, if you are only interested in the side effect (launching a script) and not in the actual script output, launching a new process is the way to go.
