### ISSUE TITLE
Installation Issue: "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oi9et1lq/cryptography/

### ISSUE THREAD

**Issue by monkeydust** [thp/urlwatch#628]
Get this error during install. 

Have googled around to make sure all dependencies installed and lost to what the issue might be. 

Help appreciated.

**

3-none-any.whl
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring->urlwatch)
  Using cached https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4
.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oi9et1lq/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oi9et1lq/cryptography/

**

**Comment by thp** [comment]
```
 ModuleNotFoundError: No module named 'setuptools_rust'
```

Try upgrading `pip` to the latest version.
