### ISSUE TITLE
This is an awesome project

### ISSUE THREAD

**Issue by proxseas** [thp/urlwatch#639]
I really have to give praises to this project. I was looking into a solution for monitoring webpage changes and the most common self-hosted recommendation was Huginn. While it's a very capable system, it is quite a beast and takes some time to set up. Meanwhile, urlwatch is quite modular and very lightweight (no Ruby behemoth and it uses SQL Lite). I set it up to use PushOver as the reporter, crontab as the scheduler, and pyhtml2text for much of the parsing. But I have tons of other choices if I want that. This is really an awesome utility and I wish it was better known.

**Comment by kongomongo** [comment]
full ack!

**Comment by boison-ranga** [comment]
Thank you to this project and contributors from me as well.

Don't want to sound too prophetically, but: this is the future of privacy-friendly notifications and subscriptions.

**Comment by thp** [comment]
Thanks :)
