### ISSUE TITLE
Running urlwatch on Github using Github Actions

### ISSUE THREAD

**Issue by huwan** [thp/urlwatch#644]
Hi all,

I want to share my configurations for running urlwatch on github with github actions. In this way, we can update job list file directly on GitHub using the file editor and get notified via e-mail of web changes.

Here is the demo repo: https://github.com/huwan/urlwatch-actions-demo

This repo shows
 - Install dependencies and setup urlwatch;
 - Use action secrets to pass password to workflow;
 - Run urlwatch workflow when specific activity on GitHub happens (e.g., push), at a scheduled time (using posix cron syntax), or you can manually trigger workflow runs;
 - Store workflow data, i.e., database file for change history, as workflow artifact.

Note that this demo uses cleartext [app password](https://urlwatch.readthedocs.io/en/latest/reporters.html#smtp-login-without-keyring) for [e-mail reporter (via gmail)](https://urlwatch.readthedocs.io/en/latest/reporters.html#e-mail-via-gmail-smtp
) in urlwatch.yaml file. To prevent password leaks, use a private github repository or use [encrypted secrets](https://docs.github.com/en/actions/reference/encrypted-secrets) if you want to run urlwatch via github actions.

**Comment by elliottback** [comment]
This is pretty cool, thanks for sharing!
