### ISSUE TITLE
Run Jobs In Parallel?

### ISSUE THREAD

**Issue by elliottback** [thp/urlwatch#648]
From the log output when running with --verbose, it seems that the jobs in my configuration (a bunch of URL jobs) all run sequentially.  It would be nice to schedule them in parallel, as it takes around 60s for a cycle.

**Comment by thp** [comment]
It's already running the jobs in parallel (up to 10 workers). There are some cases (e.g. navigate jobs i think) that cannot run in parallel (yet).
