### ISSUE TITLE
Add a csv2text filter

### ISSUE THREAD

**Issue by Sveder** [thp/urlwatch#656]
Is there any interest in adding a csv2text filter?
I'm sure this can be achieved with `shellpipe` and `awk`/`sed` magic, but I think an elegant way to do it is using a format string with the header or the column number.
See basic implementation here:
https://github.com/Sveder/urlwatch/pull/3/

@thp wdyt? Should I prepare a rebased pr?

**Comment by thp** [comment]
Yes, I think that would be a good addition. We have to make it use defaults and stuff and have some examples and maybe also expose the option to allow setting the delimiter, quoting, etc.. -- but if you want to work on that, please open a PR and let's continue the discussion there.

**Comment by Sveder** [comment]
I've added a rebase with my quick and dirty solution:
https://github.com/thp/urlwatch/pull/658

Will wait till your comments on it.
Thanks again for your time :)

**Comment by thp** [comment]
Closing this as, #658 is now merged. Thanks!
