### ISSUE TITLE
VACUUM locking issues when running two instances concurrently

### ISSUE THREAD

**Issue by sbraz** [thp/urlwatch#66]
I have two URL lists with different polling frequencies but they both run at the same time once a day.
When this happens, there is a locking issue when minidb runs  `VACUUM`:

```
 Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/urlwatch", line 375, in <module>
    main(parser.parse_args())
  File "/usr/lib/python-exec/python3.5/urlwatch", line 345, in main
    cache_storage.close()
  File "/usr/lib64/python3.5/site-packages/urlwatch/storage.py", line 299, in close
    self.db.close()
  File "/usr/lib64/python3.5/site-packages/minidb.py", line 170, in close
    self._execute('VACUUM')
  File "/usr/lib64/python3.5/site-packages/minidb.py", line 153, in _execute
    return self.db.execute(sql)
sqlite3.OperationalError: cannot VACUUM - SQL statements in progress
```

A file-level lock with `fcntl.LOCK_EX` would fix the problem but I don't really know where it should be used.

**Comment by brbsix** [comment]
I looked into this a little bit and didn't see a really obvious place to implement it. minidb already uses a thread lock, but it can't just be replaced with a file lock.

Maybe @thp will know a better way to do it, but in the meantime this should work as a quick hack:

https://github.com/brbsix/minidb/commit/55a1b05efed15cc110a81d64b80c9f2cd4468199

**Comment by thp** [comment]
Can you turn that into a minidb pull request? Not yet sure if this should be merged (maybe the application can take care of locking, or file-based locking is optional when creating the minidb storage object?) but might be a good starting point.
