### ISSUE TITLE
UnboundLocalError: local variable 'passwd' referenced before assignment

### ISSUE THREAD

**Issue by JulienPalard** [thp/urlwatch#667]
In https://github.com/thp/urlwatch/blob/edf687c98d4a700ef4528512443da1c618737652/lib/urlwatch/mailer.py#L98, when the `if` and the `elif` are false we hit `s.login(` no `passwd`.

Full traceback:

```
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 33, in <module>
    sys.exit(load_entry_point('urlwatch==2.22', 'console_scripts', 'urlwatch')())
  File "/usr/lib/python3/dist-packages/urlwatch/cli.py", line 112, in main
    urlwatch_command.run()
  File "/usr/lib/python3/dist-packages/urlwatch/command.py", line 410, in run
    self.urlwatcher.close()
  File "/usr/lib/python3/dist-packages/urlwatch/main.py", line 97, in close
    self.report.finish()
  File "/usr/lib/python3/dist-packages/urlwatch/handler.py", line 212, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 125, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 423, in submit
    mailer.send(msg)
  File "/usr/lib/python3/dist-packages/urlwatch/mailer.py", line 98, in send
    s.login(self.smtp_user, passwd)
UnboundLocalError: local variable 'passwd' referenced before assignment
```

I don't know how I can have `self.auth` being truthy with my conf though, I hope I can run urlwatch with `python -m pdb` soon to give more information.

**Comment by JulienPalard** [comment]
Got is using `python -m pdb`! So I have `self.auth == True`, `self.insecure_password == None`, and `keyring == None`.

So I'm trying to understand why I have `self.auth` being true, this is because:

```
(Pdb) p self.config['smtp']
{'host': 'localhost', 'user': '', 'port': 25, 'starttls': False, 'auth': True}
```

which looks strange at first because my yaml config is:
```
smtp:
  host: localhost
  port: 25
  starttls: false
```

but it's not because `auth` is True by default in storage.py's `DEFAULT_CONFIG`.

**Comment by corrafig** [comment]
> but it's not because `auth` is True by default in storage.py's `DEFAULT_CONFIG`.

Yep. Quick fix in configuration:
```
report:
  email:
    smtp:
      auth: false
    ...
```

**Comment by JulienPalard** [comment]
Yes, that's what I did. Should urlwatch raise a more verbose exception in this case?

**Comment by thp** [comment]
Having a `UnboundLocalError` there is ugly, so now there's a `ValueError` that describes why this is happening. This should hint at the 3 possible ways of fixing this:

1. Disable `auth` explicitly
2. Set `insecure_password`
3. Install `keyring` (+ configure it)

**Comment by JulienPalard** [comment]
Thanks @thp!
