### ISSUE TITLE
How can I pass a variable to 'data' for a job?

### ISSUE THREAD

**Issue by piejanssens** [thp/urlwatch#669]
`data: "token=$TOKEN&otherData=true`

**Comment by mborsetti** [comment]
You can find documentation on using this key for the [webchanges](https://pypi.org/project/webchanges/) fork (optimized for HTML) [here](https://webchanges.readthedocs.io/en/stable/jobs.html#data); it should work the same way here.  

Please let me know if the documentation isn't clear enough.
