### ISSUE TITLE
stmp setting has problem, gmail cannot forward email

### ISSUE THREAD

**Issue by A6669** [thp/urlwatch#673]
This is yaml file.
> display:
>   error: true
>   new: true
>   unchanged: false
> job_defaults:
>   all: {}
>   browser: {}
>   shell: {}
>   url: {}
> report:
>   email:
>     enabled: ture
>     from: 'AAA@gmail.com'
>     html: ture
>     method: smtp
>     sendmail:
>       path: sendmail
>     smtp: 
>       auth: true
>       host: smtp.gmail.com
>       port: 587
>       starttls: true
>       user: ''
>       # insecure_password:
>     subject: '{count} changes: {jobs}'
>     to: 'BBB@gmail.com'
>   html:
>     diff: unified
>   mailgun:
>     api_key: ''
>     domain: ''
>     enabled: false
>     from_mail: ''
>     from_name: ''
>     region: us
>     subject: '{count} changes: {jobs}'
>     to: ''
>   markdown:
>     details: true
>     footer: true
>     minimal: false
>   matrix:
>     access_token: ''
>     enabled: false
>     homeserver: ''
>     room_id: ''
>   pushbullet:
>     api_key: ''
>     enabled: false
>   pushover:
>     app: ''
>     device: null
>     enabled: false
>     sound: spacealarm
>     user: ''
>   slack:
>     enabled: false
>     webhook_url: ''
>   stdout:
>     color: true
>     enabled: true
>   telegram:
>     bot_token: ''
>     chat_id: ''
>     enabled: false
>   text:
>     details: true
>     footer: true
>     line_length: 75
>     minimal: false
> 

when I run urlwatch
it has error

> `urlwatch 2.23, Copyright 2008-2021 Thomas Perl
> Website: https://thp.io/2008/urlwatch/
> Buy me a coffee: https://ko-fi.com/thpx86
> watched 5 URLs in 3 seconds
> Traceback (most recent call last):
>   File "/usr/local/bin/urlwatch", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/cli.py", line 112, in main
>     urlwatch_command.run()
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/command.py", line 410, in run
>     self.urlwatcher.close()
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/main.py", line 97, in close
>     self.report.finish()
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/handler.py", line 212, in finish
>     ReporterBase.submit_all(self, self.job_states, duration)
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/reporters.py", line 136, in submit_all
>     subclass(report, cfg, job_states, duration).submit()
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/reporters.py", line 426, in submit
>     mailer.send(msg)
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/mailer.py", line 84, in send
>     s = smtplib.SMTP(self.smtp_server, self.smtp_port)
>   File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 255, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 343, in connect
>     (code, msg) = self.getreply()
>   File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 405, in getreply
>     raise SMTPServerDisconnected("Connection unexpectedly closed")
> smtplib.SMTPServerDisconnected: Connection unexpectedly '

I use mac big sure 11.6
can you help me?
thanks in advance.

**Comment by thp** [comment]
Please use triple-backticks for quoting code blocks, this way the formatting is preserved (formatting is important in YAML).

Have you configured your GMail according to the docs?
https://urlwatch.readthedocs.io/en/latest/reporters.html#e-mail-via-gmail-smtp

**Comment by thp** [comment]
Closing after no response for some months. Please re-open and answer the questions in [this comment](#issuecomment-962564299) if you still need support.
