### ISSUE TITLE
Parametrized test names are not stable across versions

### ISSUE THREAD

**Issue by sbraz** [thp/urlwatch#676]
Hi,
I noticed that you append a number to all parametrized tests. However, this number changes when you add a new test. For instance, `lib/urlwatch/tests/test_filter_documentation.py::test_url[https://example.net/ocr-test.png-job28]` used to be `lib/urlwatch/tests/test_filter_documentation.py::test_url[https://example.net/ocr-test.png-job27]` (and 26) in older versions.

We at Gentoo maintain a list of skipped test which we often have to update because of this: https://github.com/gentoo/gentoo/blob/24396dbde5e3e7fafd5f3a1ff91be6ea8b88cd8c/www-misc/urlwatch/urlwatch-2.23.ebuild#L39

Could you please look for a way to make the names more stable?

**Comment by thp** [comment]
This is implemented now, thanks for noticing (this means that with the next release, the ignored tests probably break once more (as the IDs are removed), but then it's stable.

**Comment by sbraz** [comment]
Very nice, thanks!
