### ISSUE TITLE
Optimizing request for telegram reporter

### ISSUE THREAD

**Issue by zackdvd** [thp/urlwatch#691]
Hi,

first things first: Thanks for this great project! Very useful, especially watching for corona test results ;-)

My request: Would it be possible to change the formatting of telegram messages? There are multiple lines of "====" and that could be (hopefully) an easy task to reduce them and make a way more better UX.
![telegram - 1](https://user-images.githubusercontent.com/19238490/152527233-58aad4ce-8c63-4ed0-b80c-57ee5d594dc7.jpeg)

Thank you all!

**Comment by neutric** [comment]
You can change this aspect yourself by modifying the `line_length` setting with `urlwatch --edit-config`. Note: This affects all reporters that inherit from `TextReporter`, which matters if you also receive notifications through other channels such as email. If this is indeed a problem, don't edit the default config but create a separate one for the targets you want reporting through telegram for as described in https://github.com/thp/urlwatch/issues/507.

**Comment by mborsetti** [comment]
The [webchanges](https://webchanges.readthedocs.io/en/stable/migration.html) fork may be what you're looking for as it is optimized for HTML. It has an improved telegram reporter that uses MarkdownV2 and preserves most HTML formatting, including clickable links, bolding, underlining, italics and strikethrough.
