### ISSUE TITLE
Reporter is called even when diff_filter returns an empty string

### ISSUE THREAD

**Issue by SaskiaTon** [thp/urlwatch#692]
I watch a site where sometimes content is added and sometimes content is removed. I am only interested in specific addings. I managed to filter what I want with "filter". Then I added the diff_filter, according to https://urlwatch.readthedocs.io/en/latest/advanced.html to:
```
diff_filter:
  - grep: '^[@+]'
```
Situation: When there is a change in the site. After filtering there are only deletions
With diff_filter I filter out the deletions, because I am interested in the additions.
What I expect: No alert, since there has been no change for me
What happens: There is an alert with "CHANGED" and then an empty line. 

I also tried the diff_filter
`  - grep: '^[+]'
  - grepi: '^[+++]'
  - grepi: '^\s*$'
 `
In the hope to filter out the empty line, but this doesn't work.

It appears that first it is determined by "filter" if there is a change, and if so the "diff_filter" is only applied for visualisation.

**Comment by mborsetti** [comment]
The [additions-only](https://webchanges.readthedocs.io/en/stable/diff_filters.html#additions-only) filter on the [webchanges](https://webchanges.readthedocs.io/en/stable/migration.html) fork may be what you're looking for.

**Comment by thp** [comment]
This is now implemented in master using an additional configuration option (because there are use cases where one wants to have a notification even if the diff filter returns the empty string), including new documentation how to use it.
