### ISSUE TITLE
Only show URL, but not details, when a change is reported

### ISSUE THREAD

**Issue by krishna36** [thp/urlwatch#694]
I am looking to just send the URL when the content changed. I am trying to us URL watch but I am getting all the list of contents which are getting changed ?

Is there a way just to get the URL which got changed ? 

I am using email service and Prowl to send notifications. If I send all the content which changed then it fails due length issues.
Will wdiff help me with this ?

**Comment by thp** [comment]
If you are using plaintext mail, the `report` / `text` / `details` setting can be set to `false` to avoid details and report just a summary. You can also set `report` / `text` / `footer` to `false` to make the report even shorter.

If you remove the `name` from the job, just leaving the `url`, then it's even shorter. Starting with urlwatch 2.24, you can set `user_visible_url` to customize what's visible (e.g. watching a REST API endpoint, but wanting to show the "web-visible" URL in the report).

`urlwatch --edit-config`, set those:

```
...
report:
  ...
  email:
    html: false
    ...
  text:
    details: false
    footer: false
    ...
```

**Comment by krishna36** [comment]
Thank you. This helps.
