### ISSUE TITLE
Some mails can't be sent due to header length limitation

### ISSUE THREAD

**Issue by JulienPalard** [thp/urlwatch#702]
Since a few days I spotted:

    smtplib.SMTPDataError: (550, b'maximum allowed line length is 998 octets, got 1110')

I traced it to the subject line:

    Subject: 14 changes: (followerd by 14 urls)

So a quick fix can be to change the subject setting, in the `report.email` section to:

    subject: '{count} changes.'

**Comment by JulienPalard** [comment]
I bet the issue should be reported cpython side, maybe `email.base64mime.header_encode` should split the line?

**Comment by thp** [comment]
Merged, thanks!
