### ISSUE TITLE
error instaling Urlwatch on my Ubuntu linux

### ISSUE THREAD

**Issue by aliefchandra** [thp/urlwatch#71]
i am newbie on ubuntu linux, but i am interet abaut urlwatch. so i am instaling ubuntu to try urlwatch on my ubuntu linux.
i have done install urlwatch 1.x, i have a question : 
1. how to upgrade or update urlwatch 1.x to 2 ?
a am try to installing urlwatch 2 using console and run `python setup.py install` but error
anyone can give me step by step to installing urlwatch 2 on my ubuntu linux ?

**Comment by brbsix** [comment]
Do you have `pip` installed? If not, download https://bootstrap.pypa.io/get-pip.py then run `python3 ./get-pip.py --user`. `pip` will allow you to easily manage Python packages.

Then, to install the latest release of urlwatch, run `pip3 install --user urlwatch`.

Lastly, ensure *$HOME/.local/bin* is on your PATH if it is not already. Add something along the lines of `PATH=$HOME/.local/bin:$PATH` to your *.profile* or *.bashrc* file.

**Comment by aliefchandra** [comment]
yes,, great , tanks brbsix it's WORK for me.
