### ISSUE TITLE
How to get around client 403 error?

### ISSUE THREAD

**Issue by AKSoo** [thp/urlwatch#711]
A web page I'm watching for weekly updates recently started to block urlwatch with 403 errors. I tried editing the job to provide the request with the same cookie and user-agent as my browser, but I still can't get around the 403. Is there anything else I could try?

```
name: "ABCD publications"
url: "https://abcdstudy.org/publications/"
cookies:
  {key}: {value}
headers:
  User-Agent: {Mozilla...}
```

**Comment by thp** [comment]
It depends on how they block you, User-Agent is only one possible method.

Best is to get in touch with the website author/hoster and figure out a way to handle watching the page that is acceptable to them.

**Comment by AKSoo** [comment]
It appears Javascript was required, but pyppeteer + chromium gets stuck. Fortunately, I found a fork named [webchanges](https://github.com/mborsetti/webchanges) that uses playwright + chrome mborsetti/webchanges and this worked.
