### ISSUE TITLE
Running urlwatch on pages that send an HTTP 404 status code

### ISSUE THREAD

**Issue by ameeps** [thp/urlwatch#72]
Urlwatch always sends an error when checking a page that transmits a HTTP 404 code (page not found).

The response text is as follows:

```
01. ERROR: 404 test
===========================================================================

---------------------------------------------------------------------------
ERROR: 404 test (http://tickets.sandbagtickets.com/event/UY8831935ji)
---------------------------------------------------------------------------
404 Client Error: Not Found
---------------------------------------------------------------------------


-- 

```

However, http://tickets.sandbagtickets.com/event/UY8831935ji is a real page, it's just temporarily not available. Is there any way to have urlwatch watch a page that transmits a 404, and alert when it no longer transmits a 404? As opposed to simply returning an error every time.

**Comment by brbsix** [comment]
Can't you just ignore the errors by configuring *urlwatch.yaml* as follows:

    display:
      error: false

Otherwise you could write a script to test the http code of the url and schedule it with cron or urlwatch.

**Comment by thp** [comment]
Yes, like @brbsix said, you can configure it to not display any errors. Maybe it makes sense to treat 404 as something special, but I'm not sure yet..

**Comment by ad-m** [comment]
Do you can workaround that by ``shell` command eg. curl.
