### ISSUE TITLE
Package for APK to run on android

### ISSUE THREAD

**Issue by bbeevvoo** [thp/urlwatch#720]
I have it all setup and running on my windows 10. I would like to package it up and move it to my tablet. I have read how to convert a script to apk but it says to start with a PY and move assets into an asset folder. 
My question is what do I bundle into an apk and how do I insert my urls and config into

**Comment by thp** [comment]
urlwatch is not supposed to run on your phone/tablet directly, but rather on a server (VPS, Raspberry Pi, etc..). The notifications that urlwatch sends can go to your Android device.

For running `urlwatch` on an Android device, I'd recommend running it inside [Termux](https://termux.dev/en/)
