### ISSUE TITLE
How Do I Install on Win 10?

### ISSUE THREAD

**Issue by geedogz** [thp/urlwatch#724]
How do i install this on windows 10?

**Comment by thp** [comment]
Easiest is to [install from PyPI](https://pypi.org/project/urlwatch/) via pip:

1. Download [Python 3.10.8](https://www.python.org/downloads/release/python-3108/), you usually want the [Windows installer (64-bit)](https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe)
2. Install it
3. Press <kbd>Win</kbd> + <kbd>R</kbd>, enter `cmd` and press <kbd>Enter</kbd>
4. Type: `py -m pip install urlwatch`
5. This will download urlwatch and all dependencies and install it
6. After this, `urlwatch` should be available as a command (if not, [read the docs](https://docs.python.org/3/using/windows.html))

When urlwatch is installed, see the [Quick Start](https://urlwatch.readthedocs.io/en/latest/introduction.html#quick-start) guide on how to configure things.
