### ISSUE TITLE
RequestsDependencyWarning: urllib3

### ISSUE THREAD

**Issue by Jmuccigr** [thp/urlwatch#734]
Getting the following when running v. 2.25 on my mac. Seems still to work in the end:

```
/opt/homebrew/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (None)/charset_normalizer (3.0.1) doesn't match a supported version!
```

**Comment by thp** [comment]
This can be fixed with:

```
python3 -m pip install --upgrade urllib3
```

**Comment by Jmuccigr** [comment]
Nope, same error. I've urllib3 installed already, as the warning indicates and no update occurs when I issue the command.

**Comment by thp** [comment]
Try this: https://stackoverflow.com/a/73199422/1047040

**Comment by Jmuccigr** [comment]
> Try this: https://stackoverflow.com/a/73199422/1047040

Yep, that did it. Not sure why, but I'll take it. :-)
