### ISSUE TITLE
--gc-cache does not delete unused keys from redis db

### ISSUE THREAD

**Issue by trevorshannon** [thp/urlwatch#743]
When using a redis cache, the `--gc-cache` option successfully removes old entries, but does not delete old keys (despite claiming to do so).  This seems to be due to a string/bytes type issue somewhere around [here](https://github.com/thp/urlwatch/blob/25269fb6a788316b4f89b931cb40d763f7467230/lib/urlwatch/storage.py#L632).

When deleting unused keys, the system attempts to remove e.g. `"guid:b'27687e4f702f8547973bc60451b4f1539ee3d428'"` instead of `"guid:27687e4f702f8547973bc60451b4f1539ee3d428"`

**Comment by thp** [comment]
Yeah, the problem with the Redis support is that at least I don't test it regularly.

It was added by @scottmac in #491. I don't have an overview of how popular the Redis support is.

If it's not easy to test/verify, then maybe eventually removing the Redis support is a good idea?

(cc'd @scottmac to chime in)

**Comment by scottmac** [comment]
I’ll fix it, looks straightforward
