### ISSUE TITLE
Atom feed reporter

### ISSUE THREAD

**Issue by fstirlitz** [thp/urlwatch#76]
I'd love to have urlwatch output an Atom feed which I'd then be able to import into my feed reader.

Liferea supports reading feeds generated by a command-line program; it could work great together with urlwatch.

**Comment by thp** [comment]
Closing as duplicate of https://github.com/thp/urlwatch/issues/76 -- whether we use RSS or Atom should just be an implementation detail, feed readers can usually handle both.
