### ISSUE TITLE
Pushover reporter: Implement possibility to override `priority` on url configuration

### ISSUE THREAD

**Issue by oxivanisher** [thp/urlwatch#760]
It would be really nice to be able to override the `priority` setting of the pushover reporter on the url entry in `urls.yaml`. This would make it possible to choose how important a change on a URL is.

**Comment by thp** [comment]
Patches gladly accepted, or considering sponsoring the implementation of this feature ([get in touch](https://thp.io)).

**Comment by oxivanisher** [comment]
I tried to create a corresponding PR, but I was not able to get it working. If anybody is interested in the future, my try and reasons for not working can be found here: https://github.com/thp/urlwatch/compare/master...oxivanisher:urlwatch:feature/pushover_settings_url
