### ISSUE TITLE
Wait for selector?

### ISSUE THREAD

**Issue by yuis-ice** [thp/urlwatch#763]
As #548, some websites don't load properly (one serious example would be jp.mercari.com/) with just a `wait_until`. I think it'd be better to enable users to use `wait_for` to wait for a selector, or enables users to inject/eval a custom JavaScript script within the filter chain so it allows users much more capability more than the waiting issue. Thanks.

**Comment by thp** [comment]
With urlwatch 2.28, the docs say: https://urlwatch.readthedocs.io/en/latest/jobs.html#browser

> wait_until: Either load, domcontentloaded, networkidle, or commit (see [Advanced Topics](https://urlwatch.readthedocs.io/en/latest/advanced.html#advanced-topics))

See also: [Configuring how long browser jobs wait for pages to load](https://urlwatch.readthedocs.io/en/latest/advanced.html#configuring-how-long-browser-jobs-wait-for-pages-to-load)

Related docs: https://dev.to/checkly/avoiding-hard-waits-in-playwright-and-puppeteer-272

**Comment by Jamstah** [comment]
Have put a very naive implementation in as #810
