### ISSUE TITLE
Socks proxy

### ISSUE THREAD

**Issue by pdostal** [thp/urlwatch#767]
Hello,

first of all, thank you for awesome product!

Would it be possible use urlwatcher with SOCKSv4 proxy?

Thanks a lot!

**Comment by thp** [comment]
It should be possible using the `http_proxy` and `https_proxy` per-job settings. For SOCKSv5, the URL scheme is `socks5://user:pass@host:port`, for SOCKSv4 it might be `socks4://`, but this is untested.

**Comment by thp** [comment]
Documentation improved in #768, thanks!
