### ISSUE TITLE
Error when piping to less

### ISSUE THREAD

**Issue by polyzen** [thp/urlwatch#77]
Sometimes a stack trace occurs after quitting less (apparently only when there's actual output):

```
~ > urlwatch |less                                                                     
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 375, in <module>
    main(parser.parse_args())
  File "/usr/bin/urlwatch", line 342, in main
    report.finish()
  File "/usr/lib/python3.5/site-packages/urlwatch/handler.py", line 128, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3.5/site-packages/urlwatch/reporters.py", line 89, in submit_all
    cls(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3.5/site-packages/urlwatch/reporters.py", line 304, in submit
    print(self._green(line))
BrokenPipeError: [Errno 32] Broken pipe
zsh: exit 1     urlwatch | 
zsh: done       less
```

urlwatch 2.2
less 481
Arch Linux Arm

**Comment by brbsix** [comment]
Can you insert the following near the top of */usr/bin/urlwatch* and report back?

    import signal

    # ignore broken pipe
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)

I wasn't able to reproduce the issue, but that's typically what I use for this error.

**Comment by thp** [comment]
Looks like when a SIGPIPE for a socket is received, the network send will return an error, so that should be good. I guess I'll add this to Git now.

**Comment by polyzen** [comment]
Glad this could get sorted so quickly! Thank you both.

**Comment by DerEineDa** [comment]
I get this on my Fedora 24 workstation after installing urlwatch with pip:

```
$ urlwatch   File "/usr/bin/urlwatch", line 93
  ...
  ^
```

because of the "..." in commit 9c675de .

**Comment by thp** [comment]
@DerEineDa as you probably have already noticed in your edit, you need to install urlwatch using Python 3's PIP.
