### ISSUE TITLE
error: no such option --edit-config

### ISSUE THREAD

**Issue by shuntera** [thp/urlwatch#78]
Have set up virtualenv on a Raspberry Pi and activated that and installed urlwatch.
On attempting to edit the config I get the following.

(urlwatch)pi@pi:~ $ urlwatch --edit-config
Usage: urlwatch [options]

Watch web pages and arbitrary URLs for changes

urlwatch: error: no such option: --edit-config
(urlwatch)pi@pi:~ $

Looking to use urlwatch with PushOver.

**Comment by thp** [comment]
Which version of urlwatch is installed? Chances are this is an old version and you need to upgrade to a newer one.

**Comment by shuntera** [comment]
Decided to abandon that and try it on my Mac instead - I am using version 2.2.
Seems to work OK, except having a problem when attempting to set it up run every few minutes. I am using LaunchControl to make a launchd entry and when it runs I get this error in the error log:

env: python3: No such file or directory
env: python3: No such file or directory
env: python3: No such file or directory
env: python3: No such file or directory

I have python3 on my system - as urlwatch runs manually.  Any ideas?

**Comment by brbsix** [comment]
That sounds like a system configuration issue rather than a urlwatch one. I'd guess that python3 or urlwatch is not on the PATH available to launchd. So either use the full absolute path of python3/urlwatch or find a way to pass your PATH to launchd.

**Comment by thp** [comment]
Yes, as @brbsix said, this is more an environment issue than urlwatch issue. Please make sure "python3" is in your PATH, or change the shebang line to have the complete path to python3.
