### ISSUE TITLE
Cache inconsistency creating new items from nowhere

### ISSUE THREAD

**Issue by mhalano** [thp/urlwatch#800]
I execute urlwatch from a cron command every 30 minutes, but I'm getting actually old new entries, so it's quite spamming my email inbox. I'm using a wheel from e7a4d004425bdb275201ec5af45b24ac8c8d1946 commit because I need the support to Python 3.12.

**Comment by bb6** [comment]
It seems you are also experiencing the same issue as [Issue 779](https://github.com/thp/urlwatch/issues/779), where "NEW" blank reports without any changes or additions will fire on every cron command.

**Comment by Jamstah** [comment]
Does this happen every time, or is it intermittent?
