### ISSUE TITLE
Shell job "security" check is fundamentally broken

### ISSUE THREAD

**Issue by K900** [thp/urlwatch#828]
Sorry for the sensationalist title, but it really is. I was trying to figure out why urlwatch would refuse to run systemwide installed scripts (owned by root, but read only), and found https://github.com/thp/urlwatch/blob/b67aeab845208ab03119e7c7f2d32d03d3deb011/lib/urlwatch/storage.py#L308-L329, and that code is ... not very practically secure. I understand the intent behind it, but in practice it's bypassable in a variety of trivial ways (just swapping out the parent directory, symlinks, ACLs, fchmodat, getuid instead of geteuid, etc, etc), and an even wider variety of somewhat less trivial ways (FUSE filesystem that lies to you? SELinux?). My real end goal here is to run root owned, read-only scripts, but I think the correct thing is to just remove the check.

**Comment by thp** [comment]
What are you trying to do that's prevented by this check? This check deals with the jobs configuration file, not a script. The jobs configuration file should be owned by the user running urlwatch, not by root (except when running urlwatch as root).

The point is not about it not being easily bypass-able, but having some basic/obvious sanity checks in place, as urlwatch is often run in an automated fashion, and a jobs file containing shell jobs or shell commands might cause arbitrary commands to be executed.

If you try to run it as normal user, but with the configuration file owned by root, my first question would be: Why not just let the user who runs urlwatch own it? Alternatively (but I really don't see the point of wanting to to it like that), any file owned by root is probably fine to pass the check, even if the current user isn't root (i.e. changing the last check to `file_st.st_uid != current_uid and file_st.st_uid != 0`). But again, this configuration file is probably better owned by the user running the tool.

**Comment by K900** [comment]
Oh god, I misread the code horribly. My actual use case here is running urlwatch as a systemd unit, and passing in the config file as a credential, which makes it root owned, but ACLed to provide read access to the service user.

**Comment by thp** [comment]
Can you check if a patch like the following would fix your use case?

```patch
diff --git a/lib/urlwatch/storage.py b/lib/urlwatch/storage.py
index 0424506..cdc5b54 100644
--- a/lib/urlwatch/storage.py
+++ b/lib/urlwatch/storage.py
@@ -310,14 +310,14 @@ class UrlsBaseFileStorage(BaseTextualFileStorage, metaclass=ABCMeta):
         dir_st = os.stat(dirname)
         if (dir_st.st_mode & (stat.S_IWGRP | stat.S_IWOTH)) != 0:
             shelljob_errors.append('%s is group/world-writable' % dirname)
-        if dir_st.st_uid != current_uid:
-            shelljob_errors.append('%s not owned by %s' % (dirname, get_current_user()))
+        if dir_st.st_uid not in (current_uid, 0):
+            shelljob_errors.append('%s not owned by %s or root' % (dirname, get_current_user()))
 
         file_st = os.stat(self.filename)
         if (file_st.st_mode & (stat.S_IWGRP | stat.S_IWOTH)) != 0:
             shelljob_errors.append('%s is group/world-writable' % self.filename)
-        if file_st.st_uid != current_uid:
-            shelljob_errors.append('%s not owned by %s' % (self.filename, get_current_user()))
+        if file_st.st_uid not in (current_uid, 0):
+            shelljob_errors.append('%s not owned by %s or root' % (self.filename, get_current_user()))
 
         return shelljob_errors
```

**Comment by Jamstah** [comment]
> Why not just let the user who runs urlwatch own it?

Just as an aside here - that's pretty standard for system services. The files in /etc are owned by root and the processes that are configured by them explicitly run under least-privilege accounts and do not have access to change their own configuration.

Allowing config owned by root does seem like a good solution here.

**Comment by K900** [comment]
Thanks, the patch works!
