### ISSUE TITLE
Reports flipping between adding and removing all data

### ISSUE THREAD

**Issue by bb6** [thp/urlwatch#829]
Been experiencing an issue the past few days where urlwatch reports are flipping back and forth- between reporting 0 characters of data in a report, and back on the next report to containing all of the data again. There hasn't been any recent adjustments to the job or report configuration.

The source webpage shows consistently that there are no changes being made, however these reports still pop every few hours switching between 0 data and full data. Right now, the report is stuck reporting that the page is blank (despite the job having ran multiple times) and all of the source data is still present on the webpage.

This is similar to Issue #779 (which is still not fixed!!), however in that case, the reports all just show blank. I know from Issue #779 that urlwatch has been having bugs with its caching- could this be related? 

Only change to the urlwatch setup is to [adjust MAX_WORKERS in worker.py from 10 to 1](https://github.com/thp/urlwatch/issues/779#issuecomment-1978814538), the current workaround to eliminate Issue #779. If the MAX_WORKERS is adjusted to the default, Issue #779 **immediately** reappears.

Reports below, showing 8 reports of data flipping between removed and added. Right now the report is stuck empty.

---------------------------------------------------------------------------
CHANGED: ####
---------------------------------------------------------------------------
--- @ Fri, 06 Sep 2024 23:07:38 -0400
+++ @ Wed, 18 Sep 2024 09:03:10 -0400
@@ -1,160 +0,0 @@

---------------------------------------------------------------------------
CHANGED: ####
---------------------------------------------------------------------------
--- @ Wed, 18 Sep 2024 09:03:10 -0400
+++ @ Wed, 18 Sep 2024 16:09:48 -0400
@@ -0,0 +1,160 @@

---------------------------------------------------------------------------
CHANGED: ####
---------------------------------------------------------------------------
--- @ Wed, 18 Sep 2024 16:09:47 -0400
+++ @ Wed, 18 Sep 2024 16:39:51 -0400
@@ -1,160 +0,0 @@

---------------------------------------------------------------------------
CHANGED: ####
---------------------------------------------------------------------------
--- @ Wed, 18 Sep 2024 16:39:51 -0400
+++ @ Wed, 18 Sep 2024 17:39:56 -0400
@@ -0,0 +1,160 @@

---------------------------------------------------------------------------
CHANGED: ####
---------------------------------------------------------------------------
--- @ Wed, 18 Sep 2024 17:39:56 -0400
+++ @ Wed, 18 Sep 2024 20:10:04 -0400
@@ -1,160 +0,0 @@

---------------------------------------------------------------------------
CHANGED: ####
---------------------------------------------------------------------------
--- @ Wed, 18 Sep 2024 20:10:04 -0400
+++ @ Wed, 18 Sep 2024 20:40:07 -0400
@@ -0,0 +1,160 @@

---------------------------------------------------------------------------
CHANGED: ####
---------------------------------------------------------------------------
--- @ Wed, 18 Sep 2024 20:40:07 -0400
+++ @ Wed, 18 Sep 2024 22:10:13 -0400
@@ -1,160 +0,0 @@

**Comment by Arturron** [comment]
maybe this will help
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by bb6** [comment]
> maybe this will help (insert scam link here) I put the necessary dlls in the archive

Scam alert. Bitly shows that this link leads to a ZIP file on Mediafire. Please do not click on user [Arturron](https://github.com/Arturron)'s links. They will contain viruses. Account reported.

**Comment by Jamstah** [comment]
#799 is fixed by an update to minidb.

How is your urlwatch installed?

**Comment by thp** [comment]
Homebrew formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/u/urlwatch.rb

When installing 2.28_7 (which seems to be the latest on brew):

```
% find /opt/homebrew/Cellar/urlwatch | grep minidb
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb-2.0.8.dist-info
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb-2.0.8.dist-info/LICENSE
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb-2.0.8.dist-info/WHEEL
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb-2.0.8.dist-info/top_level.txt
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb-2.0.8.dist-info/REQUESTED
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb-2.0.8.dist-info/INSTALLER
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb-2.0.8.dist-info/METADATA
/opt/homebrew/Cellar/urlwatch/2.28_7/libexec/lib/python3.12/site-packages/minidb.py
```

This has been fixed in: https://github.com/Homebrew/homebrew-core/pull/172472

Looking at the commit history of urlwatch in Brew:

https://github.com/Homebrew/homebrew-core/commits/master/Formula/u/urlwatch.rb

You need at least 2.28_6 to get minidb-2.0.8, versions 2.28_4 and 2.28_5 in Homebrew don't include minidb 2.0.8.

Can probably fixed on your end via:

```
brew update
brew upgrade urlwatch
```

So this is likely #779 after all.
