### ISSUE TITLE
urlwatch 2.29 is missing from PyPI

### ISSUE THREAD

**Issue by sbraz** [thp/urlwatch#832]
Hi,
I just noticed the existence of v2.29 by chance because it was never uploaded to PyPI. Could you please do it? The Gentoo package relies on it at the moment.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added necessary configuration in setup.py to facilitate uploading to PyPI. This includes adding 'setuptools' to install_requires, specifying 'long_description_content_type', and ensuring 'long_description' is read from README.md file.

You can review changes in this commit: https://github.com/mnmnk43434/thp-urlwatch-832/commit/66a6cc342e8828b83012c81951f2062b9e848126.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by thp** [comment]
Thanks for noticing, this is now done: https://pypi.org/project/urlwatch/2.29/
