### ISSUE TITLE
Storage layer abstraction

### ISSUE THREAD

**Issue by lechuckcaptain** [thp/urlwatch#92]
It would be really useful to have the possibility to dinamically change the storage layer of urlwatch. For example the configuration could be stored into a DB instead of a yaml file. Same idea could be applied to urls configuration or cache storage. This would allow to use the tool in different environments and software setups.

In my opinion, in order to implement this feature it's needed to refactor the urwatch main script into extendable and reusable classes (on this point of view it's a request similar to #57, but it requires a more complete refactoring). I'm working on a draft example, please take it as a simple concept:
https://gist.github.com/lechuckcaptain/a3e7c07b247c38af167a98c41c47ec04

**Comment by thp** [comment]
Yes, might make sense. Might also make testing easier, since it could be redirected to an in-memory database. Feel free to draft something up and make a pull request and we can discuss how we can get this done.

**Comment by lechuckcaptain** [comment]
OK perfect! I started working on the refactoring and you can find a draft here:

https://github.com/lechuckcaptain/urlwatch/tree/urwatch_class_objectification

Unfortunately the coverage of unit tests is small and to check for regressions requires a lot of manual testing (hopefully the problem could be easily addressed after the refactoring). 

Please let me know if you have any feedback or if you want to create a development branch where we can work together.

**Comment by thp** [comment]
This is now done, right? Closing.
