### ISSUE TITLE
Continous edit failt to parse file

### ISSUE THREAD

**Issue by ad-m** [thp/urlwatch#99]
Hello,

I like urlwatch a very much. I used urlwatch 1.x, but today I upgraded to 2.x, so I have convert my rules. Many of them fails, so I have very offen edit yaml files. If I fail to edit yaml file:

I suggest changes to update them like crontab or visudo as standard unix way:
```
crontab: installing new crontab
"/tmp/crontab.5S9mhB/crontab":23: bad minute
errors in crontab file, can't install.
Do you want to retry the same edit? (y/n) 
```

Now it works in this way, so fix of typo is a bit poor:
```
Parsing failed:
======
while scanning a simple key
  in "/home/adam/.urlwatch/urls.edit.yaml", line 9, column 1
could not find expected ':'
  in "/home/adam/.urlwatch/urls.edit.yaml", line 10, column 1
======

The file /home/adam/.urlwatch/urls.yaml was NOT updated.
Your changes have been saved in /home/adam/.urlwatch/urls.edit.yaml
```

Greetings,

**Comment by thp** [comment]
Now that #100 is merged, I consider this done. Please reopen if it still needs work.

**Comment by ad-m** [comment]
It's done. Thanks!
